### ISSUE TITLE
[Request] Allow zplugin to manage commands.

### ISSUE THREAD

**Issue by iladin** [zdharma/zplugin#10]
I currently use zplugin to manage my zsh zplugins.

I also use zplug to manage my commands.

It seems a bit silly to have two zsh plugin managers, could you add the ability to manage commands to zplugin? Really doesn't need to be any more complicated than downloading a file to a writable location in $PATH and making it executable.

**Comment by psprint** [comment]
OK, will do, maybe even before my planned return to Zplugin which is 1 month. I relied on following thing: plugin providing commands should do `path+=( ... )` so that its commands are found.

**Comment by psprint** [comment]
Finally got back to the project. I've added what you requested:

```zsh
% zplg snippet --command https://github.com/b4b4r07/httpstat/blob/master/httpstat.sh
% httpstat.sh
too few arguments
```

Full list of changes: https://github.com/zdharma/zplugin#news

More is coming, I'm open for suggestions
