### ISSUE TITLE
zplugin update --quiet flag

### ISSUE THREAD

**Issue by quintrino** [zdharma/zplugin#100]
**Is your feature request related to a problem? Please describe.**
Very minor, but when I run zplugin update I often miss the actual updates because my screen has many lines of
```
Updating plugin pluginname
Already up to date. 
```

**Describe the solution you'd like**
When the zplugin update command is run with a --quiet flag it only prints information about plugins that have updates and prints no information about plugins that are already up to date.

**Comment by robobenklein** [comment]
Related to this, I've sometimes had changelogs / commit lists taller than the screen height that cause the pager to wait for input and stop the update process until I quit the pager. Perhaps this could be a `--silent` option?

**Comment by psprint** [comment]
I've coded the `-q`/`--quiet flags`. This wasn't that easy as it turned out. Any support welcomed.

@robobenklein: yeah that's an issue, I'll think about on the `--silent` option and about other possibe solutions, like fixing the pager.

**Comment by quintrino** [comment]
Thanks so much, working great.

**Comment by psprint** [comment]
I've throwed in also muting of the all remaining status messages, like "Warning: updating also unloaded plugins", or "Warning: plugin doesn't have a remote set...", etc.

**Comment by psprint** [comment]
@robobenklein: I've added a feature: the time that the pager is allowed to run is  20 seconds now. So if someone runs `zplugin update --all` and leave it in background, it will eventually fully run and finish.

**Comment by quintrino** [comment]
Hmm, so now I'm getting 

```
 -zplg-update-or-status:kill:78: kill 24776 failed: no such process
-zplg-update-or-status:kill:78: kill 25008 failed: no such process
-zplg-update-or-status:kill:78: kill 25068 failed: no such process
-zplg-update-or-status:kill:78: kill 25086 failed: no such process
-zplg-update-or-status:kill:78: kill 25135 failed: no such process
-zplg-update-or-status:kill:78: kill 25161 failed: no such process
-zplg-update-or-status:kill:78: kill 25206 failed: no such process
```
From running `zplugin update --all --quiet`

**Comment by quintrino** [comment]
If anyone else has the same error the following commands worked. 
```
cd $ZPLG_HOME/bin/
git reset --hard origin/master
```
Seems I pulled down the changes just before the latest commit go overwritten with new changes.
