### ISSUE TITLE
install PZT::modules/completion blocked

### ISSUE THREAD

**Issue by fcying** [zdharma/zplugin#101]
**Describe the bug**
When I install PZT::modules/completion, it blocked
```
zplugin ice svn wait"0" silent pick"init.zsh" blockf
zplugin snippet PZT::modules/completion
```
the `~/.zplugin/snippets/PZT::modules/completion` are pulled down, but `external @ cf56525` not pulled down.

```
root@an:~ # Setting up snippet           PZT::modules/completion
Downloading `PZT::modules/completion' (with Subversion)...
```

**Versions:**
```
 - $ZSH_VERSION zsh 5.3.1 (x86_64-debian-linux-gnu)
 - Operating system name and version (uname -a): Linux an 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

**Comment by fcying** [comment]
It not blocked. just not display `PROMPT`, after I press `enter`. `PROMPT` display again

**Comment by laggardkernel** [comment]
I'm not sure if this is what you want. 

There's a submodule included in Prezto module `completion`. Cloning a sub-folder within a git repo using `svn` is not that perfect. You need to git clone the submodules **manually**. 

```zsh
zplugin ice svn blockf \
atclone'git clone https://github.com/zsh-users/zsh-completions.git external'
zplugin snippet PZT::modules/completion
```

Another problem is that, `prezto/modules/completion` does `compinit` for u. If you need to control the timing of `compinit`, you'd better use `zsh-users/zsh-completions` and do `compinit` by yourself. `prezto/modules/completion` module is just plugin `zsh-users/zsh-completions` with some custom configurations .

**Comment by fcying** [comment]
tks, This is exactly what I want. Just switch from prezto, I'm used to it's config.
```
zplugin ice wait"0" lucid svn blockf \
    atclone'git clone --depth 3 https://github.com/zsh-users/zsh-completions.git external'
zplugin snippet PZT::modules/completion
```
