### ISSUE TITLE
[question]Can I run a function after all plugins are loaded?

### ISSUE THREAD

**Issue by fcying** [zdharma/zplugin#102]
Now I am setting up a plugin wait '2' and atload,  Is there a better way?
```
zplugin ice svn wait'2' lucid pick"init.zsh" blockf atload'type LoadAfter >/dev/null 2>&1 && LoadAfter'
zplugin snippet PZT::modules/completion
```

**Comment by laggardkernel** [comment]
You need to control the loading order by yourself to make sure the plugin bound with `atload` is loaded as the last one. Use `zplg times` to check the loading orders.

BTW, I don't think there's function named `LoadAfter` defined within [Prezto module `completion`](https://github.com/sorin-ionescu/prezto/blob/master/modules/completion/init.zsh). If the `LoadAfter` exists, it must be defined in other plugins. In this situation, separating the command and plugin is a better approach. See #68 .

**Comment by fcying** [comment]
`LoadAfter` is my own defined function, it has some slow command.
`#68` same as my problem.
```
_null_plug_dir=${ZPLGM[PLUGINS_DIR]}/_local---null
if [[ ! -d $_null_plug_dir ]]; then
    echo "Creating zplugin 'null' plugin directory at: $_null_plug_dir"
    mkdir -p -- "$_null_plug_dir"
fi
unset _null_plug_dir
zplugin ice wait"0" lucid atload'LoadAfter'
zplugin light null
```
I test the work-around in `#68`, but it still need clone from github, not use local data..
```
Downloading null...

Cloning into '/home/fcying/.zplugin/plugins/null'...
remote: Not Found
fatal: repository 'https://github.com/null/' not found
```

**Comment by fcying** [comment]
use `zplugin light _local/null` not clone from github.
I see the description of the readme does not need `_local`?
```
The special user name _local is optional also for other commands, e.g. for load (i.e. zplugin load myplugin is sufficient, there's no need for zplugin load _local/myplugin).
```

**Comment by psprint** [comment]
Thanks, I've updated the README. Indeed, after adding the `id-as''` ice, the user `_local` is mandatory.
