### ISSUE TITLE
High CPU usage in tmux

### ISSUE THREAD

**Issue by JonnyHaystack** [zdharma/zplugin#107]
**Describe the bug**
I'm having a strange bug on a machine where I have built tmux from source. When I run tmux and create a vertical split pane, the CPU usage for the zsh process goes to 100% and stays there. It seems to be the zsh process for the pane that was already there before the split, not the new pane.
If I comment out the line `source "$ZPLUGIN"` from my zshrc, the problem does not occur. I have tried with only this line (and of course the line which sets $ZPLUGIN) in my .zshrc and the problem still occurs.
I've tried commenting out different lines in ~/.zplugin/bin/zplugin.zsh, and it seems that commenting out the line `functions -M -- zplugin_scheduler_add 1 1 -zplugin_scheduler_add_sh 2>/dev/null` is enough to stop the problem as well. Although if I do that, obviously zplugin won't work, so it doesn't solve anything.

**To Reproduce**
1. Build and install tmux release 2.8 from source
2. Be using zsh as default shell with zplugin enabled
3. Open a new tmux session
4. Create a vertical split
5. Check CPU usage

**Expected behavior**
CPU usage should remain normal

**Versions:**
 - $ZSH_VERSION == 5.0.2
 - Operating system name and version (uname -a): Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JonnyHaystack** [comment]
Update: Apparently it's with every version of tmux and it didn't matter that I built it from source. I thought the version of tmux from the CentOS 7 repositories wasn't having the issue but I just checked again and it is.
My laptop running Arch doesn't seem to have the issue at all, and neither of my raspberry pis do either, but I've verified it on both of my CentOS 7 servers over SSH and also verified it in a TTY on one of them.

**Comment by psprint** [comment]
I've occurred this ~2 times, it was completely irrational, was looking like a bug in Zsh. Thanks for the details, maybe I'll be able to track this down.

**Comment by JonnyHaystack** [comment]
Well, good to know it's not just me :smile:
What distro were you on when it happened to you? I've tested on Arch and Raspbian but it only seems to happen on CentOS. And it's not because of outdated packages in the repos or anything, because I built it from source. It's weird how it seems to be related to both CentOS and zplugin at the same time.
I created a thread on the CentOS forums just in case: https://www.centos.org/forums/viewtopic.php?f=48&t=69939&sid=626172169fcd2134589bc17d68271502

**Comment by psprint** [comment]
I was on OS X when this happened to me

**Comment by JonnyHaystack** [comment]
Ok so looks like it's definitely not just tmux that causes it because it also happens when I use JuiceSSH on Android to connect to any of my CentOS 7 servers. It happens every single time without fail.

**Comment by JonnyHaystack** [comment]
Oh well I just built zsh from source on one of my servers and it works fine now so it must simply be a bug in the version of zsh in the CentOS 7 repos.. Gotta love outdated buggy packages :^)

**Comment by psprint** [comment]
Thanks Im in a hospital right now but I have a laptop and what's missing is
only an internet connection what should be solved in 2 days

sob., 27 kwi 2019, 22:52 użytkownik Jonathan Haylett <
notifications@github.com> napisał:
