### ISSUE TITLE
Wrong architecture is picked from GH releases without `bpick` (aarch64 instead of x86_64)

### ISSUE THREAD

**Issue by igorepst** [zdharma/zplugin#108]
Wrong architecture is picked from GH releases without `bpick` (`aarch64` instead of `x86_64`)
`zplugin ice from"gh-r" as"program" bpick"*x86_64*" mv"bat* -> bat" pick"bat/bat"`
`zplugin light sharkdp/bat`

If `bpick"*x86_64*"` is omitted from the above code the version that is picked from [this page](https://github.com/sharkdp/bat/releases) is 
`bat-v0.10.0-aarch64-unknown-linux-gnu.tar.gz` instead of `bat-v0.10.0-x86_64-unknown-linux-gnu.tar.gz`

**Versions:**
 - $ZSH_VERSION == 5.6.2
 - Operating system name and version (uname -a): 
`Linux igore 4.20.11-200.fc29.x86_64 #1 SMP Wed Feb 20 15:56:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` (Fedora 29)
 - Zplugin version: latest
` git log                                                                                                                                        
commit 43ac67ff4ee9ecc80134a7cb96d4a97aec48f5e7 (HEAD -> master, origin/master, origin/HEAD)`

Thank you for the great Zplugin!

**Comment by robobenklein** [comment]
Wishing I still had my aarch64 testbed right about now, but no luck.

Not sure that there's a 100% fix for this, but perhaps we could at least first substring search for `uname --hardware-platform`?

Right now I think aarch64 is selected just because of alphabetical order.

**Comment by psprint** [comment]
There was a bug, fixed it, thanks!

@robobenklein: Zplugin greps for `$CPUTYPE` and `$OSTYPE`, the mistake was: I wanted to make this grepping a little more sophisticated and I've was grepping just for 64, without the `x85_` part :)
