### ISSUE TITLE
Zplugin install script using old ENV variables. 

### ISSUE THREAD

**Issue by quintrino** [zdharma/zplugin#109]
**Describe the bug**
The install script listed at 
https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh
still appears to use ZPLG_HOME, ZDOTDIR variables rather than the new array ZPLGM[HOME_DIR]

**Expected behavior**
The install script should check to see if there's an existing ZPLGM[HOME_DIR] for where it installs zplugin. 

Let me know if I've missed something and thanks.

**Comment by psprint** [comment]
Thanks for the report, the `install.sh` script wasn't updated for a long time. I cannot use `$ZPLGM` hash in an `/bin/sh` script, so the `$ZPLG_HOME` is left without changes. However, I've extended the script to:

 - allow outside source of the ZPLG_HOME variable (i.e. if `$ZPLG_HOME` is exported, it is used as the destination of Zplugin download),
 - fix `.zshrc` updating,

so the `install.sh` script gained some fresh features 😃
