### ISSUE TITLE
Search for completions in the plugin directory tree

### ISSUE THREAD

**Issue by paulhybryant** [zdharma/zplugin#11]
A lot of completions are not located in the root directory of the plugin.

e.g zsh-users/zsh-completions, which is widely used.
The completions are in $PLUGIN_DIR/src, not $PLUGIN_DIR

**Comment by paulhybryant** [comment]
Any comments?

**Comment by psprint** [comment]
I think this can be done. The obstacle is that `zsh-users/zsh-completions` does:

```zsh
fpath+="`dirname $0`/src"
```

But I have a proposed solution: besides extending "_"-files searching from `.../_*` to `.../**/_*`, also a "fpath-guard" can be set up – to revert `$fpath` changes done by plugin.

**Comment by psprint** [comment]
I've implemented this. There is `blockf` (block-fpath) **ice** modifier:

```zsh
% zplg ice blockf
% zplg load zsh-users/zsh-completions
...
Symlinking completion `_ack' to /Users/sgniazdowski/.zplugin/completions
Forgetting completion `_ack'...

Symlinking completion `_afew' to /Users/sgniazdowski/.zplugin/completions
Forgetting completion `_afew'...
...
Compiling zsh-completions.plugin.zsh...
% echo $fpath
/Users/sgniazdowski/.zplugin/completions /usr/local/share/zsh/site-functions /usr/local/share/zsh/5.3.1-dev-0/functions
% zplg cdisable vagrant
Disabled vagrant completion belonging to zsh-users/zsh-completions
Forgetting completion `_vagrant'...

Initializing completion system (compinit)...
```

There are also "from" (github,bitbucket,notabug) and "proto"(col) ice-modifiers.
