### ISSUE TITLE
Zplugin Config Sharing Service

### ISSUE THREAD

**Issue by psprint** [zdharma/zplugin#112]
@leoj3n: after reading #98 and an email with the same request I thought that not only gathering and storing of ready-to-go zplugin configurations could be done, but also a service that would allow browsing of submitted configs via text and tags queries and submitting of own zplugin config. There should be more use cases to it.

I recall that you've been using **[glitch.com](https://glitch.com)**. Can I ask you to evaluate creating of the above service with glitch.com? Is it possible and is it a good idea to use glitch.com for such a service?

**Comment by leoj3n** [comment]
I wonder if you could get Zsh running emulated in the browser... That would be the best option.
