### ISSUE TITLE
Broken completion

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [zdharma/zplugin#113]
**Describe the bug**
Commit https://github.com/zdharma/zplugin/commit/34d13c3762b65503f0bff0e45cd897830dbc0bc9 broke completion.

**To Reproduce**
* Update zplugin to latest version
	* type `zpl`, press `<Tab>` - zplugin completes, directories, not command options
	* exec `zpl compinit` or hard reset `~/.zplugin/bin` to commit https://github.com/zdharma/zplugin/commit/36e5e103e9595776fa020dc06aa3426a74f321c3
	* type zpl, press `<Tab>` - zplugin completes command options

**Expected behavior**
Zplugin complete command options when it needed.

**Screenshots**
[Asciinema](https://asciinema.org/a/jQwa7dXNZ3VT8hnEkFW2c3sZ5)

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): (Arch Linux) Linux arch-soul-pc 5.0.2-zen1-1-zen # 1 ZEN SMP PREEMPT Thu Mar 14 19:01:59 UTC 2019 x86_64 GNU/Linux

**Additional context**
My [.zshrc](https://github.com/Sad-Soul-Eater/dotfiles/blob/master/configs/zshrc)

**Comment by psprint** [comment]
I've found the reason, it's fixed now, thanks!

**Comment by Sad-Soul-Eater** [comment]
Everything works fine now, thanks.
