### ISSUE TITLE
ice flag atinit not respected

### ISSUE THREAD

**Issue by iboyperson** [zdharma/zplugin#114]
**Describe the bug**
It appears the ice flag atinit is no longer respected.

**To Reproduce**
On the most recent zplugin attempt to use the atinit flag on anything.

**Expected behavior**
What is specified in the atinit flag is executed as it used to be.

**Screenshots**
In the below screenshot you see tab completion for `ls -` does not work. This is because compinit is called in a atinit for me. In the second picture we see after calling the function that should have been called by atinit completion works.
![image](https://user-images.githubusercontent.com/10000914/54534288-458fc100-4949-11e9-8527-c393a148cbff.png)
![image](https://user-images.githubusercontent.com/10000914/54534370-6f48e800-4949-11e9-993b-b2270c49e200.png)

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Arch Linux

**Comment by iboyperson** [comment]
Update: Reverting https://github.com/zdharma/zplugin/commit/34d13c3762b65503f0bff0e45cd897830dbc0bc9 fixes this issue. Temporary fix though.

**Comment by psprint** [comment]
Could you add something to the `atinit''` ice, like `atinit'echo Hello1; zpcompinit; echo Hello2'` and report on the effects?

**Comment by psprint** [comment]
I've found the reason, it's fixed now

**Comment by iboyperson** [comment]
Can confirm this is fixed. Closing
