### ISSUE TITLE
Unable to load plugin from Gitlab

### ISSUE THREAD

**Issue by TeChn4K** [zdharma/zplugin#115]
I want to load a plugin from Gitlab with the _from_ ice modifier, but zplugin constantly try to fetch it from Github

```
zplugin ice from"gitlab"
zplugin light foo/bar
```

gives me

```
Downloading foo/bar...
Username for 'https://github.com': 
```

ZSH_VERSION: 5.4.2
Xubuntu 18.04
Zplugin installed today with install.sh script

**Comment by psprint** [comment]
I cannot reproduce. Could you try with `from'gl'`?

**Comment by psprint** [comment]
I've found the reason, it's fixed now

**Comment by TeChn4K** [comment]
It was quick! It's working great now, thank you!
