### ISSUE TITLE
Request: Have an `atload` not in plugin's directory (after cd back)

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#116]
Running the `atload` in the plugin's own directory has caused some weird edge cases while developing asynchronous themes that can depend on other turbo-loaded dependencies...

Right now, `atload` runs in the plugin's own directory, meaning that if a prompt wanted to update the git status of the current repo when dependency X got loaded, it would instead be located inside the plugin git repo and not the user's working directory.

Perhaps there could be another option `afterload` (naming...) that executes the command after the cd back to the working directory is completed.

Here's some example output that shows the problem:
```
>>> build_prompt: zinc_right zinc_opts
<<< render done.
vcs using gitstatus vars: /home/robo/.zplugin/plugins/romkatv---gitstatus 0092b809cd386a78db84a87c159cc265b926c077 master master https://github.com/romkatv/gitstatus  0 0 1 0 0 0 
_ZINC_ASYNC_STATII now: zincs_vcs_async started zincs_battery_async returned

>>> build_prompt: zinc_left zinc_opts
<<< render done.

zincs_vcs working out input: 0,gitstatus;;;master ◌
_ZINC_ASYNC_STATII now: zincs_vcs_async returned zincs_battery_async finished

>>> build_prompt: zinc_left zinc_opts
<<< render done.
running async_complete hook

>>> build_prompt: zinc_left zinc_opts
zincs_vcs_async_started called...
<<< render done.

>>> build_prompt: zinc_right zinc_opts
<<< render done.
_ZINC_ASYNC_STATII now: zincs_vcs_async started zincs_battery_async returned

>>> build_prompt: zinc_left zinc_opts
<<< render done.

>>> build_prompt: zinc_right zinc_opts
<<< render done.
vcs using gitstatus vars: /home/robo/code/zinc bbeccc2ea27cc2246082d53b7df30451e8bd8286 master master git@gitlab.com:robobenklein/zinc.git  0 1 0 0 0 0 
zincs_vcs working out input: 1,gitstatus;;;master ●
_ZINC_ASYNC_STATII now: zincs_vcs_async returned zincs_battery_async finished

>>> build_prompt: zinc_left zinc_opts
<<< render done.
running async_complete hook
```

Here you can see that on the first VCS status fetch, it's looking in the plugin's dir.

This wouldn't be a problem if the command to reload the theme was executed in the user's working directory.

**Comment by psprint** [comment]
I'll add a new ice-mod `nocd` as soon as I'm back from hospital

Wt., 19.03.2019, 02:24 użytkownik Ben Klein <notifications@github.com>
napisał:

**Comment by psprint** [comment]
I've added the ice-mod `nocd`, it prevents cd-ing into plugin's directory right before evaluating `atinit'',atload''`, etc. I'll update the README tomorrow.
