### ISSUE TITLE
Module: Option to disable warnings from write-protected directories

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#118]
Some ZSH source files might be in write-protected directories, (`/etc`) where the attempt to write the `.zwc` file results in a message being displayed.

```
command-not-found.plugin.zsh:ZpluginModule:5: can't write zwc file: /etc/zsh_command_not_found.zwc
```

Either disabling this warning as a whole by an option (envvar?), or being able to whitelist/blacklist patterns for disabling the warning would be great!

I don't want to remove the warning completely, since it does help with debugging, but perhaps it could also be changed so that it's disabled by default?

**Comment by robobenklein** [comment]
More: https://www.reddit.com/r/zplugin/comments/b3kn9c/purpose_of_zpluginmodule_question/

**Comment by psprint** [comment]
Ok I've conditionally silenced the warning, with the condition that `$ZPLG_MOD_DEBUG` is not `1`. Sorry for a long delay.
