### ISSUE TITLE
Feature request: ice mod for binary dependencies

### ISSUE THREAD

**Issue by leotaku** [zdharma/zplugin#122]
**Is your feature request related to a problem? Please describe.**
Many zsh plugins need to call external applications from `$PATH` to function correctly. As I sync my zsh configuration between different machines, these applications might not always be installed. This is annoying because it can cause scripts to mess up and only display unhelpful errors.

**Describe the solution you'd like**
I would like to see a new ice mod that checks if a specific binary can be found in `$PATH`. If so, the module gets loaded normally, otherwise a descriptive error message is displayed.

**Describe alternatives you've considered**
Of course it is possible to individually and manually add these checks for every plugin, but I think the issue is common and generic enough that first-class support for it would be useful to many zplugin users.

**Comment by leotaku** [comment]
see [use-package](https://github.com/jwiegley/use-package#use-package-ensure-system-package) for a Emacs plugin manager that provides a similar feature

**Comment by robobenklein** [comment]
I've been using `if'(( ${+commands[name]} ))'` which always seemed short enough for me, though I'm used to it...

What ice name would you think of first?

**Comment by leotaku** [comment]
Hmmm, maybe one of these?
```zsh
zplugin mod ensure"lua"
zplugin mod has"lua"
zplugin mod depends"lua"
zplugin mod system"lua"
```
But honestly, I don't have strong feelings towards any particular name.

**Comment by psprint** [comment]
I'll add an ice-mod tomorrow (going towards `has`)

**Comment by psprint** [comment]
I've added the new binary-dependence ice-mod – `has'command'`.
