### ISSUE TITLE
Help wanted: a person familiar with http://glitch.com

### ISSUE THREAD

**Issue by psprint** [zdharma/zplugin#124]
I'm thinking about creating a web service for sharing of Zplugin configurations. The service/site https://glitch.com seems to allow creating of such web application. However, I'm not very fluent with `npm` packages etc. that the site (most probably... I'm not seeing the whole picture) is based on (again: ?).

Could someone with good understanding what the [glitch.com](https://glitch.com) is, i.e. getting the whole picture, help with starting of the project?

**Comment by lainiwa** [comment]
It looks like [glitch.com](https://glitch.com/) does not provide any cli-to-web functionality out of the box, thus it is only about running apps that start a web service, which glitch.com then expose to the end user. If I'm right about it, you can not see a shell inside a browser with this site (unless you integrate your app with something like [gotty](https://github.com/yudai/gotty). somehow). So I do not think this service could be used for sharing `zshrc`s the same way it is used for sharing nodejs and python code.

Don't you think a github repo for folks to PR their configs into would be almost as good? With maybe a script to help load the configurations and do cleanups.

**Comment by psprint** [comment]
> So I do not think this service could be used for sharing zshrcs the same way it is used for sharing nodejs and python code.

I was thinking about implementing in nodejs or python (following your statement) a web-application where users could (optionally) register and upload zshrc, to then expose a browsing and searching interface to all users, so that they can traverse and lookup zshrcs from the database. So the inability to share zsh code "the same way it is used for sharing nodejs and python code." isn't a problem.

The repo is an interesting option. I'm just worried about the searching function. I think it is needed to provide it, to e.g. lookup how people load plugin xxx/yyy.

**Comment by lainiwa** [comment]
So you were thinking about making a glitch.com-like website? I think it too much hassle to do, while it is unlikely to be much better then utilizing the existing infrastructure of github.

Let me advocate a github-based approach.
Let's say the repo would look something like this:
```
repo_root
├── contrib
│   └── johndoe
│       ├── johns_completions.zsh
│       └── zshrc
└── run.sh
```
Thus people would PR their configs into the `contrib` folder.
And to use it they would have to `git clone <repo> && cd <repo>` and then `./run.sh johndoe`.

If a user would want to find how to install particular plugin, he would have to
* either search for it via github interface (search "in this repository" is the default search)
* or do it with `grep`, `ack`, `ag`, `ripgrep`, ... on the command line.

As the names of plugins are pretty unique, a simple textual search should be enough and should not be contaminated by irrelevant results.

The `run.sh` should let the user load particular plugin (with zsh and zplugin assigned folders to store their stuff in unique to the plugin). You might also want to add some file manager capabilities to it (something like [fff](https://github.com/dylanaraps/fff) restricted to `contrib` folder) but I think they are not essential (people are likely to use what they used to, ranger/mc/vifm/whatever).

It might also be possible to decorate the repo as a zsh plugin, so users would install it with whatever plugin manager they have along with completions for `run.sh` (should be called differently in that case).

**Comment by robobenklein** [comment]
I feel like putting configs into a git repo is a high-maintenance task, since for myself (and many others) our configs are evolving over time quite unpredictably. I wouldn't like to keep making commits in multiple places for a single change/fix. (Each change/fix would I make another PR to this shared repo?)

What if instead there was a "no changes kept test-drive" of another person's config? I would imagine a site or application where it would have a short list of highlights and special keybinds/plugins on one half, and an interactive session and trial run on the other half.

Then if the user liked something about it, they could open up the zshrc and pick-and-choose out of some marked (automatically?) sections in the file for their own config.

For finding usages of plugin xxx/yyy some kind of list of examples using that plugin could be found and the nearby code could be shown. (Some kind of implementation similar to an `egrep --context=N `?)

**Comment by psprint** [comment]
Nice ideas and good points, @robobenklein. However,, as I have not much time, and the searching-problem is solved (by Github -> Search  /  in this repository), I'm thinking about going with the repo-idea. @lainiwa, you wrote "So you were thinking about making a glitch.com-like website?" – not at all, it was to be a service / app running **on glitch.com**.

**Comment by psprint** [comment]
I just wanted to let you know that [the repository is there](https://github.com/zdharma/zplugin-configs) :)
