### ISSUE TITLE
Only show unloaded snippet warning when it applies

### ISSUE THREAD

**Issue by elony314** [zdharma/zplugin#125]
**Describe the bug**
When I update, I keep seeing this message "Warning: updating also unloaded snippets".

**Comment by robobenklein** [comment]
It means that Zplugin will pull/download snippets even if they aren't currently being used.

If you use a snippet once, but then remove it from the config, zplugin still has the cached/downloaded version in `~/.zplugin/snippets` that it will update, even if it's not being sourced by new shells.

**Comment by elony314** [comment]
But I have already deleted them

**Comment by robobenklein** [comment]
Then I think we should rename this issue to 'Only show unloaded snippet warning when it applies'

Because right now the message is printed whether or not some snippets are unloaded: https://github.com/zdharma/zplugin/blob/4d659a358476505c6de98c3c262f77245bb3c96e/zplugin-autoload.zsh#L1510

**Comment by psprint** [comment]
**Done** – I've added the restriction to not show the warning when there are no snippets downloaded. I guess that I could go further: to check if any snippet is being actually unloaded (but downloaded) and only then show the warning. Is this needed in your opinion?

**Comment by elony314** [comment]
That will be even better, thank you for your hardworking.
