### ISSUE TITLE
mfaerevaag/wd tab completions not working

### ISSUE THREAD

**Issue by jjzmajic** [zdharma/zplugin#126]
**Describe the bug**
`mfaerevaag/wd` completions not working

**To Reproduce**
Load plugin with
```
zplugin ice wait"0" lucid as"program" pick"wd.sh"\
        atload"wd() { source wd.sh }" blockf
zplugin light mfaerevaag/wd
``` 
and note that it runs but no tab completions are offered for the command.

**Expected behavior**
`wd add`, `wd clear` etc being suggested as completions.

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux manjaro 4.20.17-1-MANJARO #1 SMP PREEMPT Tue Mar 19 18:07:36 UTC 2019 x86_64 GNU/Linux

**Additional context**
Config file:
```
source /usr/share/zsh/plugin-managers/zplugin/zplugin.zsh

zplugin ice lucid pick"powerlevel10k.zsh-theme"
zplugin light romkatv/powerlevel10k

zplugin ice wait"0" lucid blockf svn
zplugin snippet PZT::modules/utility

zplugin ice wait"0" lucid blockf
zplugin snippet PZT::modules/completion/init.zsh

zplugin ice wait"0" lucid as"program" pick"wd.sh"\
        atload"wd() { source wd.sh }" blockf
zplugin light mfaerevaag/wd

zplugin ice wait"0" lucid blockf
zplugin light zsh-users/zsh-completions

zplugin ice wait"0" lucid atload"_zsh_autosuggest_start"
zplugin light zsh-users/zsh-autosuggestions

zplugin ice wait"0" lucid atinit"zpcompinit; zpcdreplay"
zplugin light zdharma/fast-syntax-highlighting


# Local Variables:
# mode: shell-script
# End:
```

**Comment by jjzmajic** [comment]
No clue why, problem went away and I cannot reproduce it. Probably some changes upstream.

**Comment by psprint** [comment]
Very glad to hear that.

czw., 16 maj 2019, 07:21 użytkownik jjzmajic <notifications@github.com>
napisał:

**Comment by jjzmajic** [comment]
And the issue is back, It seemed to go away because I temporarily switched back to zplug and the completions were stored in `.zcompdump` I think.

**Comment by jjzmajic** [comment]
found the problem! `_wd.sh` is not recognized as a completion function!
```
zplugin ice wait"0" lucid as"program" pick"wd.sh"\
        mv"_wd.sh -> _wd"\
        atload"wd() { source wd.sh }" blockf
zplugin light mfaerevaag/wd
```
So this works! Shuld this be in the wiki perhaps! I noticed the correlation with the `as"completion"` ice-mod, but it took me a while to find it

**Comment by psprint** [comment]
Great job! Thanks. I'll update the Galery and maybe I'll add a page to the wiki :)

**Comment by sagikazarmark** [comment]
For the record the `atload"wd() { source wd.sh }"` part breaks syntax highlighting in vscode for me. Adding a space seem to fix it though: `atload "wd() { source wd.sh }"`.
