### ISSUE TITLE
Git Prompt Not Working - pure prompt - Centos 7.5

### ISSUE THREAD

**Issue by SeanOBoyle** [zdharma/zplugin#127]
**CentOS Version:**
```
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804

```
**zsh Version:**
`zsh 5.0.2 (x86_64-redhat-linux-gnu)
`
**Using prompt:**
https://github.com/sindresorhus/pure
**Loading as:**
`zplugin ice pick"async.zsh" src"pure.zsh"; zplugin light sindresorhus/pure
`
**Git Prompt Not working - so I added this to pure.zsh:**
```
+++ b/pure.zsh
@@ -388,6 +388,7 @@ prompt_pure_async_callback() {
        setopt localoptions noshwordsplit
        local job=$1 code=$2 output=$3 exec_time=$4 next_pending=$6
        local do_render=0
+        [[ -n $5 ]] && print "\nERROR($1): $5\n"
 
        case $job in
                \[async])
```

**Got this error:**
`ERROR(prompt_pure_async_vcs_info): --zplg-reload-and-run:14: vcs_info: function definition file not found`

**Changing to 'is-at-least' 5.0.2 fixed it:**
```
+++ b/zplugin.zsh
@@ -69,7 +69,7 @@ ZPLGM[RIGHTAR]=";:^[[C;:^[OC;:\\e[C;:\\eOC;:${termcap[kr]/$'\e'/^\[};:${terminfo
 ZPLGM[LEFTAR]=";:^[[D;:^[OD;:\\e[D;:\\eOD;:${termcap[kl]/$'\e'/^\[};:${terminfo[kcub1]/$'\e'/^\[};:"
 
 builtin autoload -Uz is-at-least
-is-at-least 5.1 && ZPLGM[NEW_AUTOLOAD]=1 || ZPLGM[NEW_AUTOLOAD]=0
+is-at-least 5.0.2 && ZPLGM[NEW_AUTOLOAD]=1 || ZPLGM[NEW_AUTOLOAD]=0
 #is-at-least 5.4 && ZPLGM[NEW_AUTOLOAD]=2
 
 # Parameters - shadowing {{{
```

**Comment by psprint** [comment]
The fix isn't doing the right thing: Zshells prior to 5.1 should use the previous autoload technique (the one that's utilizing `-zplg-reload-and-run`) because of problems with signals in those older Zshells. That said, I'm curious what's can be going wrong and I'll take a look at it

**Comment by psprint** [comment]
I've found and fixed the bug, it should now work fine. Thanks!

**Comment by SeanOBoyle** [comment]
Confirmed fixed!
Thanks!
