### ISSUE TITLE
Way to specify load order like zplug?

### ISSUE THREAD

**Issue by jjzmajic** [zdharma/zplugin#129]
**Is your feature request related to a problem? Please describe.**
Some plugins must be loaded after others such as `zsh-users/zsh-syntax-higlighting` followed by `zsh-users/zsh-history-substring-search`.

**Describe the solution you'd like**
Something like `zplug`'s `on:` feature, where I can specify the name of the plugin to wait for before loading.

**Describe alternatives you've considered**
Using the `wait` ice mod, but I am not sure how to test whether a specific plugin has been loaded as opposed to all of them.

**Comment by psprint** [comment]
The wait'' ice mod can be used for this if loading plugins after prompt
isn't a problem. You just have to ensure that the wait'' argument has a
higher value that the other plugins (assuming that the ones without the ice
mod have value e.g. -1).

czw., 16 maj 2019, 07:24 użytkownik jjzmajic <notifications@github.com>
napisał:

**Comment by jjzmajic** [comment]
Oh, that's pretty cool. While I'm on the topic of load order, is there any way to make sure some plugins start after compinit?

**Comment by psprint** [comment]
Rather no direct way to ensure this, just an intended action of putting `zpcompinit` inside a plugin's `atinit''` or `atload''` ice-mod, the one plugin that is to be the border of before-`compinit` and after-`compinit` stages.

**Comment by jjzmajic** [comment]
Ok, at least I know how to do it now - just combine wait and atinit. Thanks!
