### ISSUE TITLE
auto jump `(anon):11: parse error` after e08656d

### ISSUE THREAD

**Issue by fcying** [zdharma/zplugin#135]
**Describe the bug**
auto jump some error
```
(anon):11: parse error
(anon):11: parse error
(anon):11: bad substitution
```

**To Reproduce**
open terminal

**Expected behavior**
work fine.

**Screenshots**
![图片](https://user-images.githubusercontent.com/106934/58610282-8313b180-82dd-11e9-8c93-cb686ce0ea33.png)

**Versions:**
 - $ZSH_VERSION == zsh 5.3.1 (x86_64-debian-linux-gnu)
 - Operating system name and version (uname -a): Linux lin 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

**config**
```
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
# End of Zplugin's installer chunk

zplugin ice wait"0" lucid; zplugin light caarlos0/zsh-mkc
zplugin ice wait"0" lucid; zplugin light changyuheng/fz

zplugin ice wait'0' lucid; zplugin light zsh-users/zsh-history-substring-search
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down

zplugin ice wait'0' lucid atload'_zsh_autosuggest_start'
zplugin light zsh-users/zsh-autosuggestions
bindkey '^K' autosuggest-accept

zplugin ice wait"0" lucid atinit"zpcompinit; zpcdreplay"
zplugin light zsh-users/zsh-syntax-highlighting
zplugin light zdharma/fast-syntax-highlighting

zplugin ice wait"0" lucid
zplugin light zsh-users/zsh-completions

_null_plug_dir=${ZPLGM[PLUGINS_DIR]}/_local---null
if [[ ! -d $_null_plug_dir ]]; then
    echo "Creating zplugin 'null' plugin directory at: $_null_plug_dir"
    mkdir -p -- "$_null_plug_dir"
fi
unset _null_plug_dir
zplugin ice wait"1" lucid atload'PluginFinish'
zplugin light _local/null
function PluginFinish() {
    if [ -n "$zplugin_init" ]; then
        zplugin self-update
        zplugin compile --all
    fi
    source $CONFIG_DIR/zsh_plugin.zsh
    type LoadAfter >/dev/null 2>&1 && LoadAfter
}
```

**Comment by ahmedelgabri** [comment]
I have the same problem & when I commented out all the plugins that are using `wait` it works fine. Here is my config https://github.com/ahmedelgabri/dotfiles/blob/40fdb88faf4ac95f5474200e648c7131a60b9a05/files/.zsh.d/.zshrc#L4-L51

**Comment by psprint** [comment]
I've commited  7f85a69. Did it resolve the problem?

**Comment by fcying** [comment]
it no change use  7f85a69

**Comment by ahmedelgabri** [comment]
@psprint 	no change here too after https://github.com/zdharma/zplugin/commit/7f85a6916e58d8c8c9e5266e3cf7c745f937b9b2

**Comment by psprint** [comment]
I will approach this after a few hours. Meanwhile, could you attach the result of:

```zsh
autoload allopt
allopt > theresult.txt
```

?

**Comment by fcying** [comment]
[theresult.txt](https://github.com/zdharma/zplugin/files/3235765/theresult.txt)

**Comment by ahmedelgabri** [comment]
[theresult.txt](https://github.com/zdharma/zplugin/files/3235779/theresult.txt)

**Comment by kadaan** [comment]
What is the proper downgrade technique to get zplugin back to the state pre `zpl self-update`.  Also, it would be a really nice feature if there was a way to easily rollback a `zpl self-update` to the prior version that was installed locally.

**Comment by ahmedelgabri** [comment]
> What is the proper downgrade technique to get zplugin back to the state pre `zpl self-update`. Also, it would be a really nice feature if there was a way to easily rollback a `zpl self-update` to the prior version that was installed locally.

I guess it depends on how you install it to some extent, but if you [clone the repo](https://github.com/zdharma/zplugin/blob/master/doc/INSTALLATION.adoc#manual-installation), then you can go to a previous revision. But the tricky question is which one. Or try a different release https://github.com/zdharma/zplugin/releases

**Comment by psprint** [comment]
Overall I cannot reproduce but I'm working on it. BTW. @ahmedelgabri you load zsh-users/zsh-history-substring-search with just:

```zsh
  zplugin light "zsh-users/zsh-history-substring-search"
```

i.e. without turbo. Can I ask why?

**Comment by psprint** [comment]
I'll add `rollback` subcommand soon.

I've spotted something in 18ca4ea, could someone check if this helped?

**Comment by ahmedelgabri** [comment]
> Overall I cannot reproduce but I'm working on it. BTW. @ahmedelgabri you load `zsh-users/zsh-history-substring-search` with just:
> 
> 
>   zplugin light "zsh-users/zsh-history-substring-search"
> i.e. without turbo. Can I ask why?

@psprint  I honestly don't remember why, but will try once this bug is fixed & see. 

> I'll add `rollback` subcommand soon.
> 
> I've spotted something in [18ca4ea](https://github.com/zdharma/zplugin/commit/18ca4ea225f0ddaf06e1333dca80b0ec8ff31fbc), could someone check if this helped?

I'm now getting 

```
(anon):12: parse error
(anon):12: parse error
(anon):12: bad substitution
```

Not sure if it's a different error since the code number changed.

**Comment by psprint** [comment]
Ok, I've reproduced it. The reason is a horrible bug in Zsh <= 5.3.1. I'm looking for a way to workaround the bug.

**Comment by psprint** [comment]
OK, I've fixed the bug. Thanks for reporting it!

**Comment by ahmedelgabri** [comment]
Thanks @psprint working now 👍
