### ISSUE TITLE
OMZ completion plugins cannot find zsh functions

### ISSUE THREAD

**Issue by mys721tx** [zdharma/zplugin#137]
**Describe the bug**
`_rust`, `_cargo`, `_docker`, and `_docker-compose` plugins from oh-my-zsh cannot find zsh functions such as `_call_function` or `_arguments`.

**To Reproduce**
1. Make the following `~/.zshrc`

```zsh
source "$HOME/.zplugin/bin/zplugin.zsh"

setopt promptsubst

zplugin snippet OMZ::plugins/docker/_docker
zplugin snippet OMZ::plugins/docker-compose/_docker-compose
zplugin snippet OMZ::plugins/cargo/_cargo
zplugin snippet OMZ::plugins/rust/_rust

# auto-completion
autoload -Uz compinit
compinit
```

2. Install `zplugin`
3. start `zsh`

```ShellSession
_docker:4: command not found: _call_function
_docker-compose:4: command not found: _call_function
_cargo:10: command not found: _arguments
/home/mys_721tx/.zplugin/snippets/OMZ::plugins--rust/_rust/_rust:219: command not found: _arguments
talon% 
```
**Expected behavior**
Not given the errors like using OMZ directly with the following `~/.zshrc`.

```zsh
export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(
	git
	cargo
	rust
	docker
	docker-compose
)

source $ZSH/oh-my-zsh.sh
```

**Screenshots**
<img width="682" alt="image" src="https://user-images.githubusercontent.com/561975/58912688-ab8a1a00-86e8-11e9-8143-310abc0dd471.png">

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Arch Linux, Linux talon 5.1.2-x86_64-linode124 #1 SMP PREEMPT Wed May 15 15:12:46 UTC 2019 x86_64 GNU/Linux

**Additional context**
Same issue can be reproduced on macOS 10.14 with Homebrew zsh.

**Comment by psprint** [comment]
The ice-mod `as'completion'` should be used when loading completions, i.e. the zshrc fixed:

```zsh
ource "$HOME/.zplugin/bin/zplugin.zsh"

setopt promptsubst

zplugin snippet OMZ::plugins/docker/_docker
zplugin snippet OMZ::plugins/docker-compose/_docker-compose
zplugin snippet OMZ::plugins/cargo/_cargo
zplugin snippet OMZ::plugins/rust/_rust

# auto-completion
autoload -Uz compinit
compinit
```

**Comment by mys721tx** [comment]
Great! It solved the problem. Can we add it to the tutorial?

**Comment by psprint** [comment]
It is there https://github.com/zdharma/zplugin/blob/master/doc/INTRODUCTION.adoc#snippets-completions :)

**Comment by mys721tx** [comment]
Thanks! I am not able to edit the wiki. It would be much appreciated to [add the example to there ](https://github.com/zdharma/zplugin/wiki/Example-Oh-My-Zsh-setup)as well.

**Comment by psprint** [comment]
Ok I've extended the wiki page

**Comment by mys721tx** [comment]
Thanks again!

**Comment by jdhao** [comment]
I see two versions setting up docker completion using zinit.

The first, from [zsh wiki](http://zdharma.org/zinit/wiki/GALLERY/#completions):

```
zinit ice as"completion"
zinit snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker
```

This does not work at all (even after restarting the shell). I see the following message when installing the snippet:

```
Setting up snippet: https://github.com/docker/cli/blob/masterDownloading
https://github.com/docker/cli/blob/master` (with curl, wget, lftp)...
######################################################################## 100.0%
Note: Compiling: _docker... OK.
Installed 0 completions. They are stored in $INSTALLED_COMPS array.
Skipped installing 1 completions. They are stored in $SKIPPED_COMPS array.
```

The second from [the above comment](https://github.com/zdharma/zinit/issues/137#issuecomment-498845671):

```
zplugin ice as"completion"
zplugin snippet OMZ::plugins/docker/_docker
```

The message when installing the snippet:

```
Setting up snippet: docker/_docker
Downloading `docker/_docker` (with curl, wget, lftp)...
######################################################################## 100.0%
Note: Compiling: _docker... OK.
Installed 0 completions. They are stored in $INSTALLED_COMPS array.
Skipped installing 1 completions. They are stored in $SKIPPED_COMPS array.
```

The completion works even though I see `skipped installing 1 completions`. I am not sure what does that mean.
However, the completion stop working once I log out and log in again.

What is the problem here?
