### ISSUE TITLE
Ice mod wait not respecting suffixes

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zplugin#143]
**Describe the bug**
When using the ice mod wait'0*' to load plugins, plugins are executed in the order entered instead of by suffix order.

**To Reproduce**
Run:
zplugin ice wait"0b" atload"echo Firing 1" lucid
zplugin light zdharma/null
zplugin ice wait"0a" atload"echo Firing 2" lucid
zplugin light zdharma/null

Result: 
Firing 1
Firing 2

**Expected behavior**
The second plugin should fire before the first
Result:
Firing 2
Firing 1

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - $(uname -a): Linux nicholas-laptop 4.17.0-19.2-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 4.17-15~obs (2018-08-26) x86_64 GNU/Linux

**Additional context**
Integers work correctly i.e. wait'0' fires before wait'1' regardless of order.

**Comment by NICHOLAS85** [comment]
Commit fa26e1c fixed this issue on my machine, thanks!

**Comment by psprint** [comment]
Yes I forgot to mention it, thanks for reporting
