### ISSUE TITLE
Request: Combine "load" and "light" commands into a single "load" command.

### ISSUE THREAD

**Issue by DundarGoc** [zdharma/zplugin#145]
**Is your feature request related to a problem? Please describe.**

My biggest pet peeve with Zplugin is its complexity and trying to make heads or tails of all available commands and features. I believe one contributing factor is that subsets of commands get their own command name. For example, `light` loads a plugin and `load` loads a plugin and enables reporting (I think, you guys will have to correct me if I'm wrong). `load` does what `light` does and one other thing, at least functionality-wise.

**Describe the solution you'd like**
I think it makes more sense to combine `load` and `light` into a single `load` command and remove `light` completely. Using only `load` would then just load the plugin, i.e. what `light` currently does. If you then want to enable reporting then just pass a flag `-r` (for report) after `load`.

What do you guys think?

**Comment by robobenklein** [comment]
I guess this introduces the question of which should be the default, reporting or not?

With separate light/load commands, there's not problem since you're always explicitly choosing which to use, but for example I would prefer the default to be reporting enabled rather than as an option.

As for not breaking backwards compatibility, we can add the option to one but probably shouldn't completely remove the other except from maybe the docs.

**Comment by black7375** [comment]
I also replacement is a bad choice because of compatibility.
Option or flag seems to be more appropriate than full replacement.

**Comment by psprint** [comment]
So what could be done would be an "-n" option to `load` that would denote "no reporting".

**Comment by DundarGoc** [comment]
I'm not a fan of having multiple options that does the exact same thing. I feel like this introduces more unnecessary complexity which I was initially trying to avoid.

I'm also conflicted about the compatibility argument. I get why compatibility is an important principle to have in mind but I also don't think changing a few lines in configurations is that much of a commitment for people to make.

I'd like to retract my feature request. I think my idea maybe wasn't as obvious and well thought out as I initially thought. Thank you for taking your time to respond.
