### ISSUE TITLE
Prompt Not Showing Colors

### ISSUE THREAD

**Issue by Code-You-Fools** [zdharma/zplugin#146]
**Describe the bug**
The prompt appears in black and white. Commands are able to generate color.

**To Reproduce**
Follow the instructions [in the Example Oh-My-Zsh Setup page](https://github.com/zdharma/zplugin/wiki/Example-Oh-My-Zsh-setup)

**Expected behavior**
The prompt should also have color.

**Screenshots**
https://images2.imgbox.com/8a/4b/owqAAVih_o.png

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux Walnut-Server 4.19.56-1-lts #1 SMP Tue Jun 25 14:48:14 CEST 2019 x86_64 GNU/Linux (running Arch with the linux-lts kernel)

**Additional context**
This is appearing using PuTTY 0.71. Haven't checked if it appears on a local console, but as I primarily use PuTTY to access the server I'm not sure if that really matters.

**Comment by Code-You-Fools** [comment]
Continuing to experiment with various themes ends up showing that *some* themes display colors properly, while others do not.

**Comment by psprint** [comment]
This looks like the `setopt prompt_subst`hasn't been done?

**Comment by Code-You-Fools** [comment]
It has - both `promptsubst` and `prompt_subst`.

**Comment by Code-You-Fools** [comment]
What's really interesting to me is that some themes work as intended - `OMZ::themes/mikeh.zsh-theme` functions perfectly, while `OMZ::themes/kphoen.zsh-theme` displays without color.

**Comment by psprint** [comment]
Ah, sorry, taking a closer look you echo the `PS1` variable. Does adding following to zshrc help?

```zsh
autoload colors
colors
```

**Comment by Code-You-Fools** [comment]
Yes it does. Wonder why that wasn't being loaded by itself, though.

**Comment by psprint** [comment]
Cool :)

**Comment by Code-You-Fools** [comment]
Not sure if this should be closed because my issue was solved, or stay open because colors wasn't loaded, so I'll close it for now and if someone wants to reopen it be my guest.

**Comment by psprint** [comment]
The `colors` autoload function wouldn't automatically load by the prompt using it. The prompt should be using `%F` (AFAIR) substitution instead of it. How many prompts that you've tried were having problems with colors, i.e. were probably relying on the `colors` autoload?

**Comment by Code-You-Fools** [comment]
Three or four that I found. Can't remember which ones they are now, though, sadly - this was last night.

**Comment by psprint** [comment]
Thanks!

**Comment by rajyan** [comment]
I was struggling with the same problem and finally solved it. As above, some themes need `colors` which is loaded in `OMZL::theme-and-appearance.zsh`. Also, there are several themes relying on `OMZL::spectrum.zsh`, which solved my problem.

**Comment by myl7** [comment]
I am using oh-my-zsh theme `fino`. `spectrum.zsh` solved my problem.
