### ISSUE TITLE
Edit plugin / snippet after cloning

### ISSUE THREAD

**Issue by mustaqimM** [zdharma/zplugin#147]
**Is your feature request related to a problem? Please describe.**
Allow for editting plugin/snippet after cloning.

After cloning:
```zsh
zplugin ice wait"1" lucid
zplugin snippet "https://raw.githubusercontent.com/nicodebo/base16-fzf/master/bash/base16-tomorrow-night.config"
```
I wish to append a line to the snippet.

**Comment by DundarGoc** [comment]
I think `atclone` is what you're looking for. Does this work?

```
ice wait"1" lucid atclone"echo 'Append this at end of line' >> base16-tomorrow-night.config"
snip "https://raw.githubusercontent.com/nicodebo/base16-fzf/master/bash/base16-tomorrow-night.config"

```

**Comment by psprint** [comment]
What @DundarGoc wrote is one way to do it. The other manual ways (did you mean a manual way to edit a plugin?) are:

 - Use of `cd` subcommand:
    ```zsh
    zplugin cd https://raw.githubusercontent.com/nicodebo/base16-fzf/master/bash/base16-tomorrow-night.config
    vim base16-tomorrow-night.config
    ```

-  Use of `edit` subcommand:
    ```zsh
    zplugin edit "https://raw.githubusercontent.com/nicodebo/base16-fzf/master/bash/base16-tomorrow-night.config"
    ```
The last one doesn't currently work for this specific snippet. I'll fix this till tomorrow.

**Comment by mustaqimM** [comment]
@psprint I wanted to edit it after cloning.

This is how I did it:
```zsh
zplugin ice wait"0" lucid atclone"sleep 2; sed -i '27i\  --ansi' base16-tomorrow-night.config"
```
(because it gets overwritten)
On another note I must say thank you for this amazing project. My speeds terminal loads everything in 0.119s!

**Comment by psprint** [comment]
Great to hear that!

For the code, you might need one more bit: `atpull'%atclone'`, to restore the line after a successful update of the snippet.
