### ISSUE TITLE
No way to execute command after plugin has loaded

### ISSUE THREAD

**Issue by eddyg** [zdharma/zplugin#148]
Greetings! I can't seem to figure out how to execute commands _after_ a plugin has finished loading.

Specifically, I want to run:

    bindkey -M hsmw "^G" _hsmw_cancel_accept

after `zdharma/history-search-multi-word` finishes loading, but putting it in `atload` doesn't work because the `hsmw` keymap doesn't exist yet... and I can't find an *ice* option that executes later than that.

-----

Along similar lines, I also can't find a way to define (replacement) functions before `multisrc` runs. In this case, I want to define:

    _fzf_compgen_path() { fd --type t --hidden --follow --exclude ".git" . "$1" }
    _fzf_compgen_dir() { fd --type d --hidden --follow --exclude ".git" . "$1" }

_before_ calling `multisrc"shell/{completion,key-bindings}.zsh"` so that `fzf` will use `fd` instead of `find`.

**Comment by psprint** [comment]
1. Try to define the keymap yourself via `bindkey -N hsmw emacs; bindkey ....`
  2. The defining of the functions in `atload''` hook should work. Looking at `shell/completion.zsh` reveals that the functions are declared when they don't exist, but that shouldn't be an obstacle before redefining them.

**Comment by eddyg** [comment]
Actually, it looks like the `hsmw` keymap doesn't even get _created_ until you actually use HSMW for the first time, so that's going to be tricky.

It's not a big deal; I sometimes accidentally press `^G` when I'm in HSMW which activates (and conveniently _deactivates_) the `fzfz-file-widget` widget, so I was just trying to make that consistent.

**Comment by psprint** [comment]
Closing as a follow-up issue has been created on the HSMW page – with Hacktoberfest label!
