### ISSUE TITLE
Query on my setup and turbo plugin load output

### ISSUE THREAD

**Issue by katernet** [zdharma/zplugin#149]
Hi guys! I'm wondering if I have my zplugin setup correctly with turbo mode to load omz plugins stored locally? If so, can you see anything I could optimize?

The plugins appear to be working and I have a 0.15s speed increase in zshell load.

Additional questions:
1. With turbo mode, when zshell loads I have an output of 
`Loaded /Users/%myusername%/.zsh/plugins/%pluginname%` for each plugin quickly show and then disappear. I would like to disable/hide this, how can I do that?

2. As you can see by my #comment I originally experimented with $fpath. Do I not need to add my plugin paths to fpath with zplugin? I noticed `echo $fpath` contains `/Users/%myusername%/.zsh/zplugin/completions` does this mean the plugins are now in fpath?

Setup:
In my .zshrc I have the plugins set in an array ala omz style

`plugins=(git thefuck zsh-autosuggestions zsh-syntax-highlighting z)
`

I set my custom zplugin paths:

```shell
declare -A ZPLGM
ZPLGM[HOME_DIR]="$ZSH"/zplugin
ZPLGM[PLUGINS_DIR]="$ZSH"/zplugin/plugins
ZPLGM[COMPLETIONS_DIR]="$ZSH"/zplugin/completions
ZPLGM[SNIPPETS_DIR]="$ZSH"/zplugin/snippets
ZPLGM[ZCOMPDUMP_PATH]="$ZSH"/.zcompdump
ZPLGM[COMPINIT_OPTS]=-C
```

After `compinit`  I load my plugins:

```shell
source "$ZSH"/zplugin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
for p ($plugins); do
	#[ -e "$ZSH"/plugins/$p/$p.plugin.zsh ] && fpath=("$ZSH"/plugins/$p $fpath)
	if [ -e "$ZSH"/plugins/$p/$p.plugin.zsh ]; then
		zplugin ice wait'!0' atinit'zpcompinit; zpcdreplay'
		zplugin light "$ZSH"/plugins/$p
	fi
done
```

Note:

My zsh path: `export ZSH=/Users/%myusername%/.zsh`

My plugins are stored like this within `"$ZSH"/plugins` :

```
./git:
git.plugin.zsh

./thefuck:
thefuck.plugin.zsh

./z:
z.plugin.zsh
z.sh

./zsh-autosuggestions:
zsh-autosuggestions.plugin.zsh
zsh-autosuggestions.zsh
```

zplugin report:

```shell
% zplugin report                                                              ▷
Assuming --all is passed
Plugin report for %/Users/%myusername%/.zsh/plugins/git
-----------------------------------------------
Source git.plugin.zsh (no reporting)
Saving `compdef _git _git_log_prettily=git-log' for replay
Saving `compdef _git gdv=git-diff' for replay
Saving `compdef _git ggf=git-checkout' for replay
Saving `compdef _git ggfl=git-checkout' for replay
Saving `compdef _git ggl=git-checkout' for replay
Saving `compdef _git ggp=git-checkout' for replay
Saving `compdef _git ggpnp=git-checkout' for replay
Saving `compdef _git ggu=git-checkout' for replay
Autoload is-at-least with options -U -z

Plugin report for %/Users/%myusername%/.zsh/plugins/thefuck
---------------------------------------------------
Source thefuck.plugin.zsh (no reporting)

Plugin report for %/Users/%myusername%/.zsh/plugins/zsh-autosuggestions
---------------------------------------------------------------
Source zsh-autosuggestions.plugin.zsh (no reporting)
Autoload add-zsh-hook with options -U -z
Autoload _zsh_autosuggest_start

Plugin report for %/Users/%myusername%/.zsh/plugins/zsh-syntax-highlighting
-------------------------------------------------------------------
Source zsh-syntax-highlighting.plugin.zsh (no reporting)
Autoload is-at-least with options -U -z
Autoload add-zsh-hook with options -U -z
Autoload _zsh_highlight_main__precmd_hook
Autoload add-zsh-hook with options -U -z
Autoload _zsh_highlight_preexec_hook

Plugin report for %/Users/%myusername%/.zsh/plugins/z
---------------------------------------------
Source z.plugin.zsh (no reporting)
```

**Comment by psprint** [comment]
> Hi guys! I'm wondering if I have my zplugin setup correctly with turbo mode to load omz plugins stored locally? If so, can you see anything I could optimize?
>
> ...
> 
> Setup:
> In my .zshrc I have the plugins set in an array ala omz style
> 
> `plugins=(git thefuck zsh-autosuggestions zsh-syntax-highlighting z) `
>
> ...
> 
> After `compinit` I load my plugins:
> 
> ```shell
> source "$ZSH"/zplugin/zplugin.zsh
> autoload -Uz _zplugin
> (( ${+_comps} )) && _comps[zplugin]=_zplugin
> for p ($plugins); do
> 	#[ -e "$ZSH"/plugins/$p/$p.plugin.zsh ] && fpath=("$ZSH"/plugins/$p $fpath)
> 	if [ -e "$ZSH"/plugins/$p/$p.plugin.zsh ]; then
> 		zplugin ice wait'!0' atinit'zpcompinit; zpcdreplay'
> ...
> ```

1. With turbo-mode, you in general shouldn't call the `compinit` directly, but via the `atinit'zpcompinit; zpcdreplay'` that you're doing later.
2. However, you're doing this of **every** loaded plugin. This will cause a significant slow-down of the startup.
3. You've should use the `atinit'...'` with the syntax-highlighting plugin that you use. You can do it in a following way:
```zsh
> zplugin ice wait'!0' ${${(M)p:#*syntax-high*}:+atinit'zpcompinit; zpcdreplay'}
```
4. The `:#` is: remove everything if the pattern `*syntax-high*` matches. `(M)` is: reverse the operation, i.e. keep everything if the pattern matches. `:+` is: if not empty, then replace with `atinit'...'`.
5. So basically you have: If `$p` contains string `syntax-high`, then the expression will be replaced with the `atinit'...'` string, and left empty otherwise.
6. This way the `atinit'...'` will be passed only to the syntax-highlighting plugin.
7. The advice of doing the `compinit` right before a syntax-highlighting plugin comes from those projects, they advice to do it this way.

> 1. With turbo mode, when zshell loads I have an output of
>        `Loaded /Users/%myusername%/.zsh/plugins/%pluginname%` for each plugin quickly show and then disappear. I would like to disable/hide this, how can I do that?

Append the ice-mod `lucid` to the ice list.

>  2. As you can see by my #comment I originally experimented with $fpath. Do I not need to add my plugin paths to fpath with zplugin? I noticed `echo $fpath` contains `/Users/%myusername%/.zsh/zplugin/completions` does this mean the plugins are now in fpath?

Yes, `$fpath` is left untouched except for that single entry. There's no need of adding any entries to `$fpath`.

**Comment by katernet** [comment]
Awesome thank you @psprint !

Is this correct? Is this not calling compinit on every pass of the loop?

```shell
for p ($plugins); do
	if [ -e "$ZSH"/plugins/$p/$p.plugin.zsh ]; then
		zplugin ice wait'!0' ${${(M)p:#*syntax-high*}:+atinit'zpcompinit; zpcdreplay'} lucid
		zplugin light "$ZSH"/plugins/$p
	fi
done
```

> > 1. With turbo mode, when zshell loads I have an output of
> >    `Loaded /Users/%myusername%/.zsh/plugins/%pluginname%` for each plugin quickly show and then disappear. I would like to disable/hide this, how can I do that?
> 
> Append the ice-mod `lucid` to the ice list.
> 

Did I do this correctly above?

**Comment by psprint** [comment]
Yes, it is correct. Have your startup times lowered? What are they? You can check them with:

```zsh
repeat 10 { time zsh -i -c exit }
```

**Comment by katernet** [comment]
I just realised I was timing the built in zshell instead of the home-brew zshell, which I am using.

Before zplugin:
```
% time $SHELL -i -c exit
	0.32 real         0.22 user         0.08 sys
```

When I opened this issue: 
```
% time $SHELL -i -c exit
	0.17 real         0.11 user         0.05 sys
```

After using your parameter expansion optimizations (and the right zsh lol!)
```
% time /usr/local/bin/zsh -i -c exit
	0.03s user 0.01s system 88% cpu 0.052 total
```

> 1. With turbo-mode, you in general shouldn't call the `compinit` directly, but via the `atinit'zpcompinit; zpcdreplay'` that you're doing later.

After now realizing this, I have removed my `compinit` calls and just using zplugin's calls:
```
% time /usr/local/bin/zsh -i -c exit
	0.02s user 0.01s system 89% cpu 0.033 total
```

So that's an improvement of 0.58s ...nice! Awesome plugin manager man thanks again!

**Comment by psprint** [comment]
Glad to read that! You're welcome!

**Comment by katernet** [comment]
Reopening this for the convenience of not explaining my setup again.

With this zplugin setup, zsh-autosuggestions does not work at the first prompt on shell login, simply hitting enter makes it work on the second prompt.

Additionally I have added the powerline10k theme to my local plugins (using a symlink) and this too only loads on the second prompt after I press enter.

I have seen the [Introduction](http://zdharma.org/zplugin/wiki/INTRODUCTION/#turbo_mode_zsh_62_53) on turbo mode, using `atload'_zsh_autosuggest_start'` ice command doesn't seem to work. I've tried the following:

```shell
for p ($plugins); do
	if [ -e "$ZSH"/plugins/$p/$p.plugin.zsh ]; then
		if [ $p = zsh-autosuggestions ]; then
			zplugin ice lucid wait'0' atload'_zsh_autosuggest_start'
			zplugin light "$ZSH"/plugins/$p
		else
			zplugin ice lucid wait'0' ${${(M)p:#*syntax*}:+atinit'custom_compinit; zpcdreplay'} # Turbo mode. Run atinit only when 'syntax' is matched and call compinit with custom_compinit()
			zplugin light "$ZSH"/plugins/$p
		fi
	fi
done
```

This seems to work (wait with no load time). Both zsh-autosuggestions and powerlink10k load ok.

```shell
for p ($plugins); do
	if [ -e "$ZSH"/plugins/$p/$p.plugin.zsh ]; then
		zplugin ice lucid wait ${${(M)p:#*syntax*}:+atinit'custom_compinit; zpcdreplay'} # Turbo mode. Run atinit only when 'syntax' is matched and call compinit with custom_compinit()
		zplugin light "$ZSH"/plugins/$p
	fi
done
```

However then my shell startup goes from 0.03s to 0.2s. 

Any ideas?

**Comment by psprint** [comment]
I've tested now with newest `zsh-autosuggestions` and `atload'__zsh_autosuggest_start'` does seem to work. I cannot see your whole setup, but the code you've pasted seems OK though.

Powerlevel also works OK (tested with the code from [GALLERY](http://zdharma.org/zplugin/wiki/GALLERY/).

**Comment by katernet** [comment]
Thanks @psprint 

Autosuggestions seems to be working fine now using `atload'_zsh_autosuggest_start'` I must have not tested it properly before. Thanks!

I can now get powerlevel10k to load, however it loads a split second after the default prompt on shell login, as you can see below.

![mVHAO9qvD6](https://user-images.githubusercontent.com/37143923/62418916-14275000-b6b4-11e9-867d-27dcbb955202.gif)

```shell
for p ($plugins); do
	if [ -e "$ZSH"/plugins/$p/$p.plugin.zsh ]; then
		if [ $p = powerlevel10k ]; then
			zplugin ice lucid wait'!0' atload'source "$ZSH"/plugins/powerlevel10k/.p10k.zsh; _p9k_precmd' nocd
			zplugin light "$ZSH"/plugins/$p
		elif [ $p = zsh-autosuggestions ]; then
			zplugin ice lucid wait'0' atload'_zsh_autosuggest_start'
			zplugin light "$ZSH"/plugins/$p
		else
			zplugin ice lucid wait'0' ${${(M)p:#*syntax*}:+atinit'zpcompinit; zpcdreplay'}
			zplugin light "$ZSH"/plugins/$p
		fi
	fi
done
```

My zsh code is split into different files and I source them from zshrc. You can see my code here https://www.codepile.net/pile/qr09QxnR 
I have combined all the code and labelled each file. My prompt file is commented out (moved to powerlevel10k) and I have left my aliases out.

I cloned powerlevel10k to "$ZSH"/plugins and symlinked powerlevel9k.zsh-theme to powerlevel10k.plugin.zsh so I can use it with my existing plugins array and for loop. Here are the necessary files:

```shell
. ~/.zsh/plugins/powerlevel10k:
.p10k.zsh
powerlevel10k.plugin.zsh -> /Users/%myusername%/.zsh/plugins/powerlevel10k/powerlevel9k.zsh-theme
powerlevel9k.zsh-theme
```

I reviewed your gallery powerlevel10k example and used `atload'source ~/.p10k.zsh; _p9k_precmd'` however the example uses `zplugin light` to powerlevel10k from GitHub.  

Now, I've wanted to use local plugins so that my shell doesn't need to clone/download any files and it keeps it simple for me, I would like to configure them myself and choose which revisions I have.

1. Is there any way to get powerlevel10k working properly with my existing setup?
2. Is my existing setup unnecessarily complicated and causing the prompt issue? Can you provide any advantages of using `zplugin light` to download/cache plugins from repos over my existing principles?

**Comment by psprint** [comment]
The after default prompt loading of the powerlevel10k is expected. I suggest that you put `PS1="READY >"` into zshrc or to load the prompt without Turbo mode, i.e. without `wait` ice.

As for the `wait'!'` yielding powerlevel10k not loading at all – is the zplugin up to date? You can update it with `zplugin self-update` and see if `wait'!'` starts to work.

As for your questions:

1. Yes, if you don't like the split-second delay – load p10k in normal mode, i.e. without `wait` ice
2. Well, your setup is interesting. I cannot judge. But `light` would allow you to update all the plugins automatically via `zplg update --all`.

**Comment by katernet** [comment]
Thanks @psprint for the answers.
I love zplugin turbo mode, it loads p10k faster than sourcing it (startup 0.03s vs 0.05s), however the trade off is the prompt delay after shell login. I think I will just source it now.
Loading without turbo mode instead of sourcing seems to almost triple the startup (0.14s vs 0.05s), so this is a trade off as well.
Maybe this is something for you to look into 😊
