### ISSUE TITLE
What even is "teleid"?

### ISSUE THREAD

**Issue by DundarGoc** [zdharma/zplugin#153]
It's in the "Available ice-modifiers" at the end when you type "zplugin help" . All ice modifiers except this one has a short explanation on what they do. What does it do? I tried understanding the source code but my zsh-fu isn't there yet.

**Comment by psprint** [comment]
It's the plugin identifier that's used with the `load` command, stored as an ice, for later use, when the user will use the `id-as` identifier instead. The word `tele` means `remote`, a remote-id. I've hesitated before adding it as it's quite internal, even though it's there when one invokes `recall`. I'm not sure what to do with it..

**Comment by DundarGoc** [comment]
Ah ok, I see. I was wondering to see if I needed to fix it in the README but it seems it was intentional. Thank you for the response.
