### ISSUE TITLE
$_ is overwritten by zplugin

### ISSUE THREAD

**Issue by yous** [zdharma/zplugin#155]
**Describe the bug**
By [15.5 Parameters Set By The Shell](http://zsh.sourceforge.net/Doc/Release/Parameters.html#index-_005f), in the document of Zsh:
> `_` \<S\>
>
> The last argument of the previous command. Also, this parameter is set in the environment of every command executed to the full pathname of the command.

But somehow, every time after a command is executed, zplugin sets `$_` to `"following"`.

**To Reproduce**
Run `zsh -f`:
``` sh
$ echo test >/dev/null
$ echo "$_"
test
$ source "$HOME/.zplugin/bin/zplugin.zsh"
$ echo test >/dev/null
$ echo "$_"
following
```

**Expected behavior**
`echo "$_"` should print `test` after executing `echo test >/dev/null`.

**Versions:**
 - $ZSH_VERSION == 5.7.1 (Homebrew)
 - Operating system name and version (uname -a): macOS Mojave 10.14.6

**Additional context**
I think this comes from `sched +1 "-zplg-scheduler following"` in `bin/zplugin.zsh`.

**Comment by psprint** [comment]
I've pushed a fix. Could you `self-update` and check if it helped?

**Comment by yous** [comment]
Yes, now `$_` is preserved. Thanks for the quick response!

**Comment by psprint** [comment]
n/p, thanks for the report!
