### ISSUE TITLE
Not possible to delete snippets through "zpl  delete"

### ISSUE THREAD

**Issue by DundarGoc** [zdharma/zplugin#156]
**Describe the bug**
I don't know if I missed something. Basically it's not possible to delete a snippet with `zpl delete`. I can't find the snippet with completion either.

![delete_attempt](https://user-images.githubusercontent.com/33953936/62203665-e7112f80-b38b-11e9-961d-4572e3176ecf.png)

![delete_completion](https://user-images.githubusercontent.com/33953936/62203672-e8daf300-b38b-11e9-86a9-753a3e724eda.png)

**To Reproduce**
Happens every time.

**Expected behavior**
Delete snippet in question or fix description in `zpl help`.

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux dundar-pc 4.19.60-1-MANJARO #1 SMP PREEMPT Sun Jul 21 12:17:26 UTC 2019 x86_64 GNU/Linux

**Comment by psprint** [comment]
Why not use regular path separator, i.e. slash? It will then work: zplg delete PZT::modules/completion. As for the completion problem I'm aware of it but do not manage to approach it. Let this issue be a placeholder for the (hopefully..) upcoming commits :)

**Comment by DundarGoc** [comment]
Doh, should have tested with slash as well. Idk, I figured it should be the same name as the folder but in hindsight it makes more sense that it's the name of the snippet. My bad.

I just assumed the completion was something you missed.

Of course. It's not a major issue tbh, just wanted to let you know in case you missed it. I'll close it for now :)
