### ISSUE TITLE
Third party completions not working

### ISSUE THREAD

**Issue by JounQin** [zdharma/zplugin#158]
**Describe the bug**

Can not make https://github.com/g-plane/zsh-yarn-autocompletions working.

**To Reproduce**
Steps to reproduce the behavior.
```sh
zplugin ice as"completion" pick"*.plugin.zsh" g-plane/zsh-yarn-autocompletions
```

**Expected behavior**
`zpl clist` no `g-plane/zsh-yarn-autocompletions`

**Versions:**
 - $ZSH_VERSION == zsh 5.7.1 (x86_64-apple-darwin18.2.0)
 - Operating system name and version (uname -a): Darwin Kernel Version 19.0.0: Tue Jul 23 01:19:36 PDT 2019; root:xnu-6153.0.103.151.1~4/RELEASE_X86_64

**Additional context**

**Comment by psprint** [comment]
The plugin doesn't contain any files starting with an underscore. The completions that are being provided are defined within the `plugin.zsh` file as inline functions. Therefore the completions cannot be managed via Zplugin's completion management subsystem.

**Comment by JounQin** [comment]
Is that possible to support it just like `zplu`? I moved from `zplug` a few days ago.

**Comment by psprint** [comment]
Yes. Load it not as a `completion` but as a regular plugin, and include `zpcdreplay`:

```zsh
ice atload"zpcdreplay" pick"*.plugin.zsh"
zplugin light g-plane/zsh-yarn-autocompletions
```

**Comment by JounQin** [comment]
Sorry, it seems not working to me.

**Comment by psprint** [comment]
It seems to be working for me:

    https://asciinema.org/a/VFlg77imHVK0jeTD7bbPqhzJN

Could you record a similar video and paste it here?

**Comment by JounQin** [comment]
https://asciinema.org/a/cVswpvUvovmq3TMylvLYweFpk

**Comment by psprint** [comment]
Could you record the same video for when using zplug?

wt., 13 sie 2019, 13:20 użytkownik JounQin <notifications@github.com>
napisał:

**Comment by psprint** [comment]
How is the situation looking? It seems that the completion is being loaded and is triggered on TAB, however something with its setup is wrong and it reports errors?

**Comment by JounQin** [comment]
Sorry I didn't focus on it previous days, I'll try zplug tonight to see whether is it an issue of the plugin itself.

**Comment by JounQin** [comment]
https://asciinema.org/a/CBcJEwNVO6dUNAJND5jnd7v4S
@psprint It seems it works well with zplug.

**Comment by JounQin** [comment]
You can check the following error detail after executing

```sh
zplugin ice atload"zpcdreplay"                                                                         
zplugin light g-plane/zsh-yarn-autocompletions
```

```sh
_fetch_yarn_autocompletions_result:1: no such file or directory: /Users/JounQin/.zplugin/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions

📦 v0.0.0 via ⬢ v12.9.1 at ☸️  standard (alauda-system) 
in eslint-mdx on  master ➜ cat /Users/JounQin/.zplugin/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions.git/lfs    21:03:50 •54% 
cat: /Users/JounQin/.zplugin/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions: No such file or directory
📦 v0.0.0 via ⬢ v12.9.1 at ☸️  standard (alauda-system) 
in eslint-mdx on  master ➜ cat /Users/JounQin/.zplugin/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions            21:03:54 •54% cat: /Users/JounQin/.zplugin/plugins/g-plane---zsh-yarn-autocompletions: Is a directory
📦 v0.0.0 via ⬢ v12.9.1 at ☸️  standard (alauda-system) 
in eslint-mdx on  master ➜ /Users/JounQin/.zplugin/plugins/g-plane---zsh-yarn-autocompletions                                     21:04:09 •54% 
⬢ v12.9.1 at ☸️  standard (alauda-system) 
in g-plane---zsh-yarn-autocompletions on  master [?] ➜ ls                                                                         21:04:19 •54% 
Cargo.lock                          azure-pipelines.yml                 src                                 zplug.zsh
Cargo.toml                          install.sh                          yarn-autocompletions.example.yml
LICENSE                             package.json                        yarn-autocompletions.plugin.zsh
README.md                           screenshot.gif                      yarn-autocompletions.plugin.zsh.zwc
```

**Comment by psprint** [comment]
Ok, the issue is solved – the command was missing an `atclone''` hook that would run the provided `zplug.zsh` script. Correct command:

```zsh
zplugin ice atload"zpcdreplay" atclone'./zplug.zsh'          
zplugin light g-plane/zsh-yarn-autocompletions
```

**Comment by JounQin** [comment]
Thanks @psprint! It works to me.

**Comment by JounQin** [comment]
Hi @psprint I upgrade from zplugin to zinit in recent days, but it breaks agiain accidentally.

```log
yarn _yarn_autocompletions:1: no such file or directory: /Users/JounQin/.zinit/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions
_yarn_autocompletions:1: no such file or directory: /Users/JounQin/.zinit/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions
_yarn_autocompletions:1: no such file or directory: /Users/JounQin/.zinit/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions
```

I tried to run `zinit update`, and then it will work in that session. But if I restart another session, the usage will break. No idea what is happening.

**Comment by psprint** [comment]
You must run `zinit cclear`.

**Comment by JounQin** [comment]
@psprint Thanks for your reply, but `zinit cclear` seems not working to me.

**Comment by DmitryMasley** [comment]
> Hi @psprint I upgrade from zplugin to zinit in recent days, but it breaks agiain accidentally.
> 
> ```
> yarn _yarn_autocompletions:1: no such file or directory: /Users/JounQin/.zinit/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions
> _yarn_autocompletions:1: no such file or directory: /Users/JounQin/.zinit/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions
> _yarn_autocompletions:1: no such file or directory: /Users/JounQin/.zinit/plugins/g-plane---zsh-yarn-autocompletions/yarn-autocompletions
> ```
> 
> I tried to run `zinit update`, and then it will work in that session. But if I restart another session, the usage will break. No idea what is happening.
> 
> My whole zinit config:
> 
> ```shell
> source $HOME/.zinit/bin/zinit.zsh
> zinit light denysdovhan/spaceship-prompt
> zinit light zdharma/history-search-multi-word
> zinit light zdharma/fast-syntax-highlighting
> zinit light zsh-users/zsh-autosuggestions
> zinit light zsh-users/zsh-completions
> zinit light zsh-users/zsh-history-substring-search
> zinit ice atload"zpcdreplay" atclone'./zplug.zsh'          
> zinit light g-plane/zsh-yarn-autocompletions
> ```

I have the same issue om Ubuntu. On Mac OS works fine
