### ISSUE TITLE
How to disable "Loaded plugin" message on start

### ISSUE THREAD

**Issue by berstend** [zdharma/zplugin#159]
Hi there,

is there any way how to disable/suppress the e.g. `Loaded zdharma/fast-syntax-highlighting` message when starting a new session?

![image](https://user-images.githubusercontent.com/1368633/62889995-ca3d0a80-bd42-11e9-9bfe-7a70f48998f6.png)

**Comment by DundarGoc** [comment]
Something like this should work:

```
zplugin ice silent ...
zplugin light zdharma/fast-syntax-highlighting
```

**Comment by DundarGoc** [comment]
On a second thought you probably want to replace the `silent` for `lucid`. `silent` mutes "plugin's or snippet's `stderr` & `stdout`" and the "Loaded" message. `lucid` only mutes the "Loaded..." message.

**Comment by berstend** [comment]
Awesome! I've just replaced all `zplugin ice` occurrences with `zplugin ice lucid` and now everything is neat and quiet. 😄 Thanks @DundarGoc 👍
