### ISSUE TITLE
Local function not working in promptsubst when loading snippet

### ISSUE THREAD

**Issue by Stefanqn** [zdharma/zplugin#160]
**Describe the bug**
`zplugin snippet OMZ::themes/robbyrussell.zsh-theme` does not print `ret_status` result (the `➜`)

**To Reproduce**
```
### Added by Zplugin's installer
source "$HOME/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
### End of Zplugin's installer chunk


setopt promptsubst
autoload -Uz colors && colors

zplugin snippet OMZ::lib/git.zsh

zplugin ice atload"unalias grv"
zplugin snippet OMZ::plugins/git/git.plugin.zsh

zplugin snippet OMZ::themes/robbyrussell.zsh-theme
#local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
#PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
#ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}git:(%{$fg[red]%}"
#ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
#ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
#ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"
```

**Expected behavior**
as if robbyrussell file is copy pasted (uncomment above)

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux qn-e590 4.19.62-1-MANJARO #1 SMP PREEMPT Sun Jul 28 09:14:58 UTC 2019 x86_64 GNU/Linux

**Comment by DundarGoc** [comment]
It's that `local` at the start that fucks it up.

A temporary solution until @psprint answers could be to manually source it after you load it:
```
source $ZPLGM[SNIPPETS_DIR]/OMZ::themes/robbyrussell.zsh-theme/robbyrussell.zsh-theme
```

**Comment by psprint** [comment]
Yes, it's because of the local. To solve it, this function is needed:

https://gist.github.com/psprint/f2a0db07cc80351e19e30378c6eaa779

And then:

```zsh
zplugin ice atload'deploy-code "ret_status=\"$ret_status\""'
zplugin snippet OMZ::themes/robbyrussell.zsh-theme
```

The drawback that still occurs is that the first prompt will be without the `->`.

**Comment by psprint** [comment]
Actually it's possible to remove also the drawback with:

```zsh
zplugin ice atload'deploy-code "ret_status=\"$ret_status\"; zle .reset-prompt"'
zplugin snippet OMZ::themes/robbyrussell.zsh-theme
```

**Comment by Stefanqn** [comment]
@psprint it works. Is there a good way to include the `deploy-code` function? Mine seems hacky and I see an error on the first command line: ` ~ (eval):1: no such file or directory: https://gist.githubusercontent.com/psprint/f2a0db07cc80351e19e30378c6eaa779/raw/b2a44921580eeadc0185af039821bedb3f561b95/deploy-code.zsh`.

I added:
```
zplugin ice id-as"deploy-code" cp"deploy-code.zsh -> deploy-code" silent
zplugin snippet 'https://gist.githubusercontent.com/psprint/f2a0db07cc80351e19e30378c6eaa779/raw/b2a44921580eeadc0185af039821bedb3f561b95/deploy-code.zsh' 
fpath=( ~/.zplugin/snippets/deploy-code "${fpath[@]}" )
autoload -Uz deploy-code
# ...
zplugin ice atload'deploy-code "ret_status=\"$ret_status\"; zle .reset-prompt"' silent
zplugin snippet OMZ::themes/robbyrussell.zsh-theme
```

**Comment by psprint** [comment]
I.ve added the wrapping `deploy-code() {` / `}` lines (they're legal also in an autoload function file), so now a simple snippet should suffice.

**Comment by Stefanqn** [comment]
yes, that does the trick! - ty.

Is it worth adding it to your doc / basic examples?

**Comment by psprint** [comment]
I think that yes, the thing is quite nice, however I think that a more general use-case would be needed to add it to the doc.
