### ISSUE TITLE
matthieusb/zsh-sdkman and OMZ::plugins/gradle load

### ISSUE THREAD

**Issue by schmas** [zdharma/zplugin#162]
Hi,

This is a question.

I'm using sdkman as suggested at zplugin website.

Now I'm trying to use https://github.com/matthieusb/zsh-sdkman for code completion.
But cannot manage to make it work.

And I also have the same issue with https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/gradle.

I'm loading like this.
```bash
# gradle
zplugin ice wait'0a' lucid blockf
zplugin snippet OMZ::plugins/gradle/gradle.plugin.zsh

# sdkman
zplugin ice wait'1a' lucid as"program" pick"$HOME/.sdkman/bin/sdk" id-as'sdkman' run-atpull \
    atclone"wget https://get.sdkman.io -O scr.sh; SDKMAN_DIR=$HOME/.sdkman bash scr.sh" \
    atpull"SDKMAN_DIR=$HOME/.sdkman sdk selfupdate"
zplugin light zdharma/null

zplugin ice wait'1a' lucid atload"zpcdreplay"
zplugin light matthieusb/zsh-sdkman
```

Can you help me out?

thanks

**Comment by psprint** [comment]
Hello,
for gradle – the plugin is multi-file, so `svn` ice should be used and the OMZ url changed to point to the directory:

```zsh
zplugin ice wait'0a' lucid svn blockf
zplugin snippet OMZ::plugins/gradle
```

Actually, the 2 other files are simlinks, so instead an `atclone` ice can be used to create them:

```zsh
zplugin ice wait'0a' lucid blockf atclone'local f=gradle.plugin.zsh; ln -s $f _gradle; ln -s $f _gradlew'
zplugin snippet OMZ::plugins/gradle/gradle.plugin.zsh
```

For the zsh-sdkman I'll take a look at it today for sure.

**Comment by psprint** [comment]
Sorry for the delay. The completion works after moving the completion file from `_zsh-sdkman.sh` to `_zsh-sdkman`, as Zplugin doesn't accept such files with dots in their name:

```zsh
zplugin ice wait'1a' lucid cp'_zsh-sdkman.sh -> _zsh-sdkman' atload"zpcdreplay"
zplugin light matthieusb/zsh-sdkman
```

However, I'm not sure why the completion starts to work after additional `zplugin compinit` (or just `compinit`) on my box. It's probably because I'm using the `-C` option to `compinit`, which skips the check if number of completion files changed *AFAIR*… Just noting.

**Comment by psprint** [comment]
Update: the `compinit` isn't needed anymore, Zplugin does it now after installing new completions.

**Comment by psprint** [comment]
Also, Zplugin now accepts dots in the file names of the completion files, so your original command now works:

```zsh
zplugin ice wait'1a' lucid atload"zpcdreplay"
zplugin light matthieusb/zsh-sdkman
```
