### ISSUE TITLE
Zplugin Noob: Load zsh modules with zplugin?

### ISSUE THREAD

**Issue by dylanjm** [zdharma/zplugin#163]
Hello, if there is a better place to ask this question, please point me in the right direction.

I have a project I'm working on that requires I use a custom module. In my zshrc, I have this line:

```
source /usr/local/opt/moose/moose_profile.sh
```
This file proceeds to run:

```
source /usr/local/opt/modules/init/zsh
export MODULEPATH=$MODULEPATH:/usr/local/Cellar/moose/modules_9

# if moose environment is available, load the module
if [ -d /usr/local/opt/moose ]; then
  module load moose-dev-clang
fi
```

It slows down my shell start-up time a ton. I'm not super well-versed in modules, is there a way to utilize zplugin to load this, or to load the module when I enter the project directory? I've taken a cursory look at direnv but not sure if it's what I need. 

# Update

I have created a direnv project folder and can now successfully init moose-dev-clang while I'm within that folder. But I'm still curious how to go about sourcing modules using zplugin. There are a few other modules I'd like to load globally such as ccache and icecream. So any direction towards do ing something like that would be awesome. 

As a heads up `/usr/local/opt/modules/...` was installed by homebrew and has module init files for all types of shells.

**Comment by psprint** [comment]
This should work (what's the project's homesite so that I could test it?):

```zsh
zplugin ice id-as"moose" pick"moose_profile.sh" \
        load'[[ $PWD = */project* ]]' unload'[[ $PWD != */project* ]]'
zplugin load /usr/local/opt/moose
```

**Comment by psprint** [comment]
So the module still appears in `zpl list` despite moving out of the directory?

**Comment by dylanjm** [comment]
That's correct and also when I type `module list` into my CLI. I know that's not a Zplugin thing, but it remains loaded.

**Comment by psprint** [comment]
I think that's fairly unlikely. Could you record an asciinema.org video that shows that happening?

**Comment by psprint** [comment]
Any update on this possible?

**Comment by dylanjm** [comment]
I ended up doing a different method where I just load the zsh module on startup and when I get into the directory I want, I manually load `moose_profile()`. I think zplugin wasn't unloading the module because there technically was no unload script to run when leaving the directory.
