### ISSUE TITLE
Zplugin update pulls submodules from master

### ISSUE THREAD

**Issue by sumitsahrawat** [zdharma/zplugin#164]
**Describe the bug**
`zplugin update` tries to pull submodules which do not need to be updated.

**To Reproduce**
1. Load ycm-core/ycmd as follows:
```zsh
zplugin ice cloneonly nocompile \
    atclone'ln -rsf $PWD ~/.ycmd; python ~/.ycmd/build.py --clang-completer' \
    atpull'python ~/.ycmd/build.py --clang-completer'
zplugin load ycm-core/ycmd
```
2. Update ycm-core/ycmd via `zplugin update ycm-core/ycmd`

**Expected behavior**

The update works similar to how `git submodule update --init --recursive` works.

```zsh
# Undo earlier update attempt.
cd ~/.zplugin/plugins/ycm-core---ycmd/third_party/bottle
git merge --abort
cd ~/.zplugin/plugins/ycm-core---ycmd
git submodule update --init --recursive
# (finishes silently)
```

**Screenshots**

Snipped output from `zplugin update ycm-core/ycmd`:

```
$ zplugin update ycm-core/ycmd
Entering 'third_party/bottle'
From https://github.com/defnull/bottle
 * branch            master     -> FETCH_HEAD
CONFLICT (add/add): Merge conflict in test/travis_setup.sh
Auto-merging test/travis_setup.sh
...snipped...
CONFLICT (add/add): Merge conflict in .travis.yml
Auto-merging .travis.yml
Automatic merge failed; fix conflicts and then commit the result.
fatal: run_command returned non-zero status for third_party/bottle
```

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux omen 5.2.11-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 29 08:09:36 UTC 2019 x86_64 GNU/Linux

**Additional context**

Seems to me like zplugin is trying to pull the submodule from master, whereas it is in a detached head state on the commit required by the parent repo. It should not even be pulled, which is what `git submodule update --init --recursive` does.

**Comment by sumitsahrawat** [comment]
Using `git pull --recurse-submodules` seems better than using `git submodule update --init --recursive`.

```zsh
$ cd ~/.zplugin/plugins/ycm-core---ycmd
$ git pull --recurse-submodules
Already up to date.
```

**Comment by psprint** [comment]
Thanks! I've tested the change, it seems to work very well.

**Comment by sumitsahrawat** [comment]
Great! Thanks for the quick fix :+1:
