### ISSUE TITLE
bpick doesn't work with rancher/k3s

### ISSUE THREAD

**Issue by kyounger** [zdharma/zplugin#166]
**Describe the bug**
Can't use this ice and load:
```
zplugin ice lucid from"gh-r" as"program" bpick"k3s"
zplugin load rancher/k3s
```

**To Reproduce**
Use the lines in my .zshrc

**Expected behavior**
Download the latest release of k3s binary

**Screenshots**
n/a

**Versions:**
zsh 5.7.1 (x86_64-apple-darwin18.2.0)
MacOS Mojave

**Additional context**
n/a

**Comment by psprint** [comment]
It's fixed, thanks!

The problem was that it was grepping a list of files with full paths in them, so "/a/b/c/k3s" didn't match "k3s". Using `bpick'*/k3s'` would work, but that's unintuitive, so I've fixed it.
