### ISSUE TITLE
Sudo make? 

### ISSUE THREAD

**Issue by jubishop** [zdharma/zplugin#170]
I'm trying to install jhawthorn/fzy.

I have these lines in my .zshrc:

zplugin ice make"install" as"program"
zplugin load jhawthorn/fzy

and it seems like it almost works, but at the end of the make it tries to move itself into /usr/local/bin:  cp fzy /usr/local/bin/

and then blows up with permission denied.  normally I'd solve this by just putting sudo in front of my make commands.  is there a way to add this to the zplugin config file? or am I just doing it all wrong!

thanks in advance for making the best zsh plugin manager!

**Comment by jubishop** [comment]
Just donated $10 thru PayPal for what it’s worth.  :). Not much but something at least :)

**Comment by jubishop** [comment]
nvm I'm an idiot.  of course i didnt want to install it.  just make works.  thanks anyway!

**Comment by psprint** [comment]
Thanks for the donation! I really appreciate it.

As for the report, it's possible to install fzy – doing so will install the man page. For doing that, a `PREFIX=$ZPFX` should be added to the `make''` ice. The full command could be like follows:

```zsh
zplugin ice wait"1" lucid as"program" pick"$ZPFX/bin/fzy*" \
    atclone"cp contrib/fzy-* $ZPFX/bin/" atpull"%atclone" \
    make"!PREFIX=$ZPFX install"
zplugin light jhawthorn/fzy
```

It also installs the i.a. `fzy-tmux` script.

**Comment by jubishop** [comment]
Interesting!  Thanks so much for bothering to reply.  I will have to study that example to fully understand it :)

It *seems* to have worked to just enter:
zplugin ice make as"program"
zplugin light jhawthorn/fzy

Is that reasonable or will it miss things ?

**Comment by psprint** [comment]
It is completely reasonable. It will just not install the man page and add a new entry to `$PATH`.

**Comment by jubishop** [comment]
Ahh ok that’s very enlightening as to what your version is doing in that extra syntax. Thanks again for the lesson!

- Justin Bishop
On Sat, Sep 21, 2019 at 2:57 PM, Sebastian Gniazdowski <notifications@github.com> wrote:
It is completely reasonable. It will just not install the man page and add a new entry to $PATH .
