### ISSUE TITLE
How to use thefuck efficiently, like dircolors?

### ISSUE THREAD

**Issue by jubishop** [zdharma/zplugin#171]
Having just read your amazing solution for LS_Colors:
http://zdharma.org/zplugin/wiki/LS_COLORS-explanation/

I wondered, is there a way to employ this trick to avoid executing "eval $(thefuck --alias)" on every zsh load?  

i'm currently loading it via OMZ like so:
zplugin ice wait"0b" lucid
zplugin snippet OMZ::plugins/thefuck/thefuck.plugin.zsh

which is great because ice wait keeps me from having to wait for it, but it'd be awesome if there was a way to not have to eval it every time, similar to what you do with dircolors.

**Comment by NICHOLAS85** [comment]
I personally use https://github.com/laggardkernel/zsh-thefuck for this purpose. Reduces loading time by a lot.

**Comment by jubishop** [comment]
Oh you’re right digging into that implementation it never uses an eval I just assumed it was doing the same thing.  Thanks!
