### ISSUE TITLE
Scheduler spams terminal with non-zero exit code

### ISSUE THREAD

**Issue by tris** [zdharma/zplugin#172]
```
$ mkdir ~/.zplugin
$ git clone -q https://github.com/zdharma/zplugin.git ~/.zplugin/bin
$ (cd ~.zplugin/bin && git rev-parse HEAD)
3a2e8e8dbfa60a4e93c4f7d802dbe77ea2a4ee74
$ zsh -f
tristan% source ~/.zplugin/bin/zplugin.zsh
tristan% setopt printexitvalue
tristan% false
zsh: exit 1
tristan% zsh: exit 1
zsh: exit 1
zsh: exit 1
zsh: exit 1
zsh: exit 1
zsh: exit 1
(ad nauseam, until I do something that exits nonzero, such as...)
true
tristan%
```

Replace `false` with `return 123` for a similar example.

Disabling the scheduler (`sched -1`) prevents the problem.

`set -x` suggests that the problem is somewhere in here:
```zsh
-zplg-scheduler() {
    integer __ret=$?
...
    return $__ret
}
```

**Versions:**
 - $ZSH_VERSION == 5.1.1 and 5.3
 - Operating system name and version (uname -a): `Linux 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64` and `Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

**Comment by psprint** [comment]
It should be solved, could you check?
