### ISSUE TITLE
Can't get zplugin to reload local snippet

### ISSUE THREAD

**Issue by jubishop** [zdharma/zplugin#173]
**Describe the bug**
I have a local snippet loaded, i.e:
zplugin snippet ~/.completions.zsh

but when i change .completions.zsh, I can't get zplugin to reload it.  I also can't seem to find anyway to identify it with a zplugin update command.

How do I get zplugin to reload this file for me?  thanks!

**Comment by psprint** [comment]
`zplugin update [--all]` should update the snippet and also reveal the identification string (which should however be the path to the file, i.e. `zplugin update ~/completions.zsh` should work).

**Comment by jubishop** [comment]
Thanks for your help!
(I changed the filename to .custom.zsh):

It initially loads fine with:
```
zplugin ice wait lucid
zplugin snippet ~/.custom.zsh
```

and if I do `zplugin delete --all`, and then load a new terminal, it reloads fine.

But when I try to `update` it, it's not identified:
```
➜ Macbook:~#>zplugin update ~/.custom.zsh
No such (plugin or snippet) directory: %HOME/.custom.zsh
(expands to: ~/.custom.zsh)
```

And when I try to `update -- all`, it's not listed:
```
➜ Macbook:~#>zplugin update --all
Note: updating also unloaded plugins

Updating plugin b4b4r07/enhancd
Already up to date.

Updating plugin rupa/z
Already up to date.

Updating plugin zdharma/fast-syntax-highlighting
Already up to date.

Updating plugin zdharma/history-search-multi-word
Already up to date.

Updating plugin zsh-users/zsh-autosuggestions
Already up to date.

Updating plugin zsh-users/zsh-completions
Already up to date.

Updating plugin zsh-users/zsh-history-substring-search
Already up to date.
```
It also doesn't show up in `list`:
```
➜ Macbook:~#>zplugin list
rupa/z *
b4b4r07/enhancd *
zsh-users/zsh-history-substring-search *
zdharma/history-search-multi-word *
zsh-users/zsh-autosuggestions *
zsh-users/zsh-completions *
zdharma/fast-syntax-highlighting *
```

but I can confirm it's definitely loaded.... thoughts?

**Comment by psprint** [comment]
Ok, it was because of the dot in the filename - zsh doesn't by default glob dotted files, the `(D)` flag is needed to enable this. I'll commit the fix in a half hour (I'm waiting for a git program to install).

**Comment by jubishop** [comment]
Awesome thank you!

- Justin Bishop
On Mon, Sep 30, 2019 at 9:59 PM, Sebastian Gniazdowski <notifications@github.com> wrote:
Ok, it was because of the dot in the filename - zsh doesn't by default glob dotted files, the (D) flag is needed to enable this. I'll commit the fix in a half hour (I'm waiting for a git program to install).

**Comment by psprint** [comment]
n/p

**Comment by jubishop** [comment]
while this does work with zplugin update ~/.custom.zsh it still doesn't seem to automatically update the file if it's been modified since the last loading.  is that expected behavior?

**Comment by psprint** [comment]
Yes, that's expected. You can load as plugin, pointing the load-subcommand
and using a pick ice to select the file

śr., 2 paź 2019, 05:12 użytkownik Justin Bishop <notifications@github.com>
napisał:

**Comment by psprint** [comment]
... pointing the load-subcommand to the directory ...

śr., 2 paź 2019, 05:50 użytkownik Sebastian Gniazdowski <
sgniazdowski@gmail.com> napisał:

**Comment by jubishop** [comment]
oh and by doing that it'll automatically re-load when the file changes?

**Comment by jubishop** [comment]
but i have the file directly in my home directory.  i'd load all of "~" as a plugin, and then pick .custom.zsh ?

**Comment by jubishop** [comment]
if you don't mind, here's what i have right now:

# Custom commands / completions
zplugin ice wait lucid
zplugin snippet ~/.custom.zsh

what should it become?  thanks again!

**Comment by psprint** [comment]
```zsh
zplugin ice multisrc'file1 file2 ...' pick'/dev/null'
zplugin load ~
```

**Comment by jubishop** [comment]
that works!  thanks again!

**Comment by jubishop** [comment]
reading the docs...wouldn't this also work?

zplugin ice wait lucid
zplugin snippet -f ~/.custom.zsh

with the -f forcing redownload?

i get an error with the message:
Snippet not loaded (-f/.custom.zsh)

**Comment by psprint** [comment]
It should work, however it seems that there's a missing space after `-f`? That said, it would output messages about installing the snippet, this points that there could be an `-q` and `--quiet` option.

**Comment by jubishop** [comment]
i can see why you might think that, given the error message, but there's definitely a space.  i just retested.  here's the exact copy paste of the instruction in my .zshrc:
```
zplugin ice wait lucid
zplugin snippet -f ~/.custom.zsh
```

and here's the actual full output of the error message:
```
Copying .custom.zsh...
cp: illegal option -- /
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
An error occured
Snippet not loaded (-f//Users/jubi/.custom.zsh)
```

**Comment by jubishop** [comment]
btw i hope it's obvious i'm only an annoying bug-reporter because i love your framework.  :) .

**Comment by psprint** [comment]
Thanks ;) As for the bug, there really is one - the options do not survive to the turbo mode correctly. so a fix is needed

**Comment by jubishop** [comment]
Sweet thanks in advance!

- Justin Bishop
On Tue, Oct 1, 2019 at 10:07 PM, Sebastian Gniazdowski <notifications@github.com> wrote:
Thanks ;) As for the bug, there really is one - the options do not survive to the turbo mode correctly. so a fix is needed
