### ISSUE TITLE
How to add completion of e.g. `kubectl completion zsh` to zsh via zplugin

### ISSUE THREAD

**Issue by Stefanqn** [zdharma/zplugin#174]
**Is your feature request related to a problem? Please describe.**
Currently I'm unable to get `kubectl` completions working with zplugin. I've tried adding
```
zplugin ice as"completion"
#zplugin snippet OMZ::plugins/kubectl
zplugin snippet OMZ::plugins/kubectl/kubectl.plugin.zsh
```
without success. I'm aware of the [related bug 104](https://github.com/zdharma/zplugin/issues/104), but couldn't get it working.

**Describe the solution you'd like**
I would be nice to somehow simply add the output of e.g. `kubectl completion zsh` to autocompletion.

**Comment by psprint** [comment]
The `as"completion"` is a problem here. It means: the plugin contains `_underscore` files, don't source anything but just install the files. But here, in the example, you want to source the `plugin.zsh` file, so the `as"completion"` should be skipped.

**Comment by psprint** [comment]
I've had a closer look - the plugin uses `ZSH_CACHE_DIR` variable provided by OMZ. If it's unset, then the completion would rather not work (unless under root). I've added the variable to Zplugin.  so the completion should now work.

**Comment by Stefanqn** [comment]
it works! Thank you.
