### ISSUE TITLE
zplugin snippet -f /path/to/dir fails

### ISSUE THREAD

**Issue by jubishop** [zdharma/zplugin#175]
Just reviewing what we discussed on a different, closed issue.  

```
zplugin ice wait
zplugin snippet -f /path/to/file.zsh
```

collapses out the space between `-f` and `/path/to/file.zsh`, trying to ultimately load `/-f/path/to/file.zsh`

**Comment by psprint** [comment]
Ok, I've added the option-retaining in turbo mode.

**Comment by jubishop** [comment]
Awesome.  Thanks again for creating this framework and addressing my bug
reports

**Comment by psprint** [comment]
n/p
