### ISSUE TITLE
Loading OMZ libs

### ISSUE THREAD

**Issue by budimanjojo** [zdharma/zplugin#176]
**Is your feature request related to a problem? Please describe.**
I'm trying to load all OMZ libs using zplugin, but it seems weird.
**Describe the solution you'd like**
This was what I did, which fails (snippet is loaded but they simply doesn't work):
```
zplugin ice svn pick"*.zsh" atload"CASE_SENSITIVE=true"
zplugin snippet OMZ::lib
```
This is what I'm now using, which seems to work but shows me `Snippet not loaded (OMZ::lib)
` error everytime:
```
zplugin ice svn multisrc"{bzr,clipboard,compfix,completion,correction,diagnostics,directories,functions,grep,history,key-bindings,misc,nvm,prompt_info_functions,spectrum,termsupport,theme-and-appearance}.zsh" atload"CASE_SENSITIVE=true"
zplugin snippet OMZ::lib
```

**Describe alternatives you've considered**
Maybe give an option like antigen? They have this `antigen use oh-my-zsh` to source all OMZ's libs.

Thanks.

**Comment by psprint** [comment]
I've pushed a patch for the Snippet not loaded error. It wouldn't been shown if `pick'/dev/null'` would be passed. In general, the command can be:

```zsh
zplugin ice multisrc'*.zsh' pick'/dev/null'
zplugin snippet OMZ::lib
```

The `pick''` ice is still needed because it prevents loading some of the files twice. I'll think about your suggestion for the OMZ libraries loading.

**Comment by psprint** [comment]
The command wouldn't work up until now – I've pushed an extension for it.

**Comment by budimanjojo** [comment]
Thanks for the quick push @psprint! I just do a `self-update` and try that out and it works without complaining anymore. But there's one new problem. It change my directory to `~/.zplugin/snippets/OMZ::lib`
I tried adding `nocd` on the `zplugin ice` command and it didn't work.
Thanks.

**Comment by psprint** [comment]
Thanks, it's fixed now.

**Comment by budimanjojo** [comment]
Thanks! But now I have a weird issue that didn't happen before. It shows me this before the prompt comes out:
```
budiman-desktop% saved
setopt
```
I don't think this is related? But it only happens now after doing `self-update`

**Comment by budimanjojo** [comment]
@psprint Sorry, it seems like this is coming from `powerlevel10k` plugin. It happens when I do an plugin update before this commit is made: https://github.com/romkatv/powerlevel10k/commit/e1f5e46c9cdfb356708f50e3d607eadbf578fb48

I can close this issue now. Thanks for the quick help!

**Comment by psprint** [comment]
n/p

**Comment by jacek-jablonski** [comment]
Hi,
unfortunately this:
```
zplugin ice multisrc'*.zsh' pick'/dev/null'
zplugin snippet OMZ::lib
```
doesn't work for me. I see that OMZ libs are not being loaded.

**Comment by budimanjojo** [comment]
I think he changed it. Currently here's mine:
```
zplugin ice svn multisrc"*.zsh" as"null"
zplugin snippet OMZ::lib
```

**Comment by jacek-jablonski** [comment]
Still not working. Here you can find my whole .zshrc: https://gist.github.com/jacek-jablonski/b0dbb994fe702030956da069165c9264

**Comment by jacek-jablonski** [comment]
It works after installing subversion. Question is if it is possible to do this without svn?

**Comment by psprint** [comment]
It would be possible if the feature described in https://github.com/zdharma/zplugin/issues/180 would have been implemented…
