### ISSUE TITLE
.tar.bz2 snippet download with extra parent folder?

### ISSUE THREAD

**Issue by chhschou** [zdharma/zplugin#177]
**Describe the bug**
A url for a .tar.bz2 file is downloaded into a parent folder with the same name as the file name. The script then complains "(snippet URL points to a directory instead of a file?
to download directory, use preceding: zplugin ice svn;)"

**To Reproduce**
  zplugin as'program' pick'firefox/firefox'
  zplugin snippet https://download-installer.cdn.mozilla.net/pub/devedition/releases/70.0b4/linux-x86_64/en-US/firefox-70.0b4.tar.bz2

**Expected behavior**
Expected zplugin to extract find the .tar.bz file and extract it

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a):  Fedora 
Linux localhost.localdomain 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I am keen to help find a solution, need a bit of hint where to look.

**Comment by psprint** [comment]
Following will work:

```zsh
 zplugin ice as'program' pick'firefox/firefox' atclone'tar jxf *.tar.bz2' atpull'%atclone'
zplugin snippet https://download-installer.cdn.mozilla.net/pub/devedition/releases/70.0b4/linux-x86_64/en-US/firefox-70.0b4.tar.bz2
```

and that's a nice idea to install binary programs.

**Comment by chhschou** [comment]
I've a "workaround", but I'm not sure if this is the right way to do it. I still think there is an issue.
```
  zplugin ice atclone'mkdir ff; \
    tar -C ff -xjf firefox*.tar.bz2; \
    ln -s ./ff/firefox/firefox; \
    _create_and_link_desktop_file firefox "$(readlink -f firefox)" firefox' \
   as'program' pick'./firefox'
  zplugin snippet https://download-installer.cdn.mozilla.net/pub/devedition/releases/70.0b4/linux-x86_64/en-US/firefox-70.0b4.tar.bz2

```

**Comment by chhschou** [comment]
:+1:

**Comment by psprint** [comment]
After `zplugin self-update` and loading `zplugin/z-a-bin-gem-node` you've could also create the firefox *shim* instead of altering the PATH:

```zsh
zplugin ice pick"/dev/null" sbin'firefox/firefox' atclone'tar jxf *.tar.bz2' atpull'%atclone'                                  
zplugin snippet https://download-installer.cdn.mozilla.net/pub/devedition/releases/70.0b4/linux-x86_64/en-US/firefox-70.0b4.tar.bz2
```

This way it's possible to easily use such installed binaries system wide - only adding of `$ZPFX/bin` (i.e. `~/.zplugin/polaris/bin` by default) to the PATH is needed, as it is there where the *shims* are being created.

**Comment by chhschou** [comment]
Thanks, I didn't find this documented anywhere. Can you please explain the pick"/dev/null" and sbin parts a bit more?

**Comment by chhschou** [comment]
I saw a potentially relevant [commit](https://github.com/zdharma/zplugin/commit/967da93597c4a9e940238756b80942c78ad06483) suggesting that the snippet should not be compiled. I thought that is what the 'nocompile' modifier is for?

**Comment by psprint** [comment]
N/p. The pick'' is to prevent Zplugin from searching a file to source.
