### ISSUE TITLE
ZPLGM[BIN_DIR] is not set to ~?

### ISSUE THREAD

**Issue by budimanjojo** [zdharma/zplugin#179]
**Describe the bug**
I tried to install separate zplugin for my root user, but I got this error:
`zsh compinit: insecure files, run compaudit for list.`
And this is what caused the permission problem when I run `compaudit`:
`/root/.zplugin/completions/_zplugin` which is a symlink to the file `/home/budiman/.zplugin/bin/_zplugin`
So if I change the file owner to root, then that error will appear in my normal user and vice versa.
The `ZPLGM[BIN_DIR]` is set to `/home/budiman/.zplugin/bin/zplugin.zsh` instead of `/root/.zplugin/bin/zplugin.zsh`

Is this an expected behavior? Or a bug? Thank you.

**Comment by psprint** [comment]
It's a strange situation. I suspect that you've been copying `~/.zplugin` to `/root`? And maybe also `~/.zshrc` to `/root`, with the `BIN_DIR` being set manually in it?

**Comment by budimanjojo** [comment]
OMG you're right. I have this in the `zshrc` file:
```
source '/home/budiman/.zplugin/bin/zplugin.zsh'
```
I'm sorry. I'll close this now.

**Comment by budimanjojo** [comment]
@psprint but wait. that line was created by zplugin by the automatic installation. Maybe use `$HOME/. zplugin/bin/zplugin.zsh` is a better way?

**Comment by psprint** [comment]
Yes, it might be. It looks like the installation was done from `su` not `su -`, or something similar that doesn't change `$HOME` and the expansion inside the script used wrong path. I'll change the behavior today.

**Comment by budimanjojo** [comment]
No, I copied my zshrc file to the root folder and install zplugin as root. So zplugin didn't add anything to the `/root/.zshrc` because it's already there. So it's not the installer didn't detect the real home directory of root user, but it will be nice if the installer put in $HOME variable in the file from the beginning instead of full path so the same zshrc file can be used anywhere. :)

**Comment by psprint** [comment]
Ahso, true, thanks

pt., 11 paź 2019, 18:35 użytkownik Budiman Jojo <notifications@github.com>
napisał:

**Comment by psprint** [comment]
I've changed the installer, it uses unexpanded $HOME now.

**Comment by budimanjojo** [comment]
Nice, thanks :D
