### ISSUE TITLE
CentOS 7.6 (zsh 5.0.2) cannot load zplugin

### ISSUE THREAD

**Issue by corporategoth** [zdharma/zplugin#182]
I am trying to run zplugin on a CentOS 7.6 box (still very common).

Any attempt to load zsh, even from a shell with it only loading zpluigin.zsh, I get:

```
/home/prez/.env/ext/zplugin/zplugin.zsh:1050: parse error near `]]'
```

I have tried two completely different CentOS 7.6 boxes.
FYI, the version of ZSH that is standard on them is 5.0.2

That block of code looks like:

```
   1043     (( ${+ZPLG_ICE[cloneonly]} || !tmp[1-correct] )) && return 0
   1044 
   1045     ZPLG_SNIPPETS[$id_as]="$id_as <${${ZPLG_ICE[svn]+svn}:-single file}>"
   1046 
   1047     [[ -z "${opts[(r)-u]}" ]] && { ZPLGM[CUR_USPL2]="$id_as"; ZPLG_REPORTS[$id_as]=""; }
   1048 
   1049     local -a arr
   1050     [[ "${opts[(r)-u]}" ]] && {
   1051         reply=( ${(on)ZPLG_EXTS[(I)z-annex hook:\\\!atinit <->]} )
   1052         for key in "${reply[@]}"; do
   1053             arr=( "${(Q)${(z@)ZPLG_EXTS[$key]}[@]}" )
   1054             "${arr[5]}" "snippet" "$save_url" "$id_as" "$local_dir/$dirname" \!atinit
   1055         done
   1056     }
```

This is NOT when trying to load a module, but on loading of the zsh file itself.  As a consequence, the zplugin function is not registered and none of my plugin commands work (obviously).

I believe it's because you left out a -z or a -n in that block (not sure which is required).

**Comment by psprint** [comment]
Yes, it's a missing `-n`, I've removed it accidentally when doing a cleanup. Thanks!
