### ISSUE TITLE
Keyboard input doesn't get processed between plugins loaded with wait"!"

### ISSUE THREAD

**Issue by romkatv** [zdharma/zplugin#186]
To reproduce:

1. Type this command:
```zsh
docker run -e LANG=en_US.utf8 -e TERM -it --rm archlinux/base bash -uec '
  pacman -Sy --noconfirm zsh git curl

  curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh |
    sh >/dev/null

  echo "sleep 1; PROMPT=\"1> \"" >~/plugin-1.zsh
  echo "sleep 1; PROMPT=\"2> \"" >~/plugin-2.zsh
  echo "sleep 1; PROMPT=\"3> \"" >~/plugin-3.zsh

  >>~/.zshrc cat <<END
PROMPT="0> "
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-1.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-2.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-3.zsh
END

  exec zsh'
```
2. Wait for prompt to become `3> `.
3. Type `zsh` and immediately press and hold `x`.

Actual: When the first `x` appears on the screen, prompt is `3> `.

Expected: When the first `x` appears on the screen, prompt is not `3> `.

Alternative way to reproduce:

1. Type the same docker command as above.
2. Wait for prompt to become `3> `.
3. Type `zsh` and press and hold *ENTER*.

Actual: After 4 seconds all prompts on the screen are equal to `3> `.

Expected: After 4 seconds at least one prompt on the screen is not equal to `3> `.

---

I'm not sure this is a bug and I'm not hindered by this issue at all. Feel free to close at will without doing anything.

**Comment by psprint** [comment]
I think that the sleep time is unfortunate – the Zplugin scheduler is executed every second. So for the `sleep 1`, and the additional lags for running a command, it'll be run immediately after the previous plugin stops loading, because the 1 second will already pass and the code in `raw_getbyte()` will already move to processing the next `sched` event without processing the keys. This can be proven by the following code:

```zsh
sched-func() { sched +1 sched-func; LANG=C sleep 1.1; }
sched +0 sched-func
```

It'll ultimately lock the shell. So, the bug report is rather not fixable / not needing fix – if someone has a plugin that loads for longer than 1 second, then he'll be having to face the possibility of immediate loading of a next plugin – which however in real world will not be a problem, unless the second plugin also loads for a long time, and not a reasonable time like `100 ms`.

**Comment by psprint** [comment]
That said I would be expecting a bigger success rate for `sleep 0.8`: https://asciinema.org/a/nGYG8Km8dEn6ZskUzwWbr5FgY

**Comment by psprint** [comment]
Ah, I think I know from where the poor success rate comes: it's because the `sched` event processing works basing on the whole (fraction-less) integers of the seconds passed. So if the first event will be scheduled in `*.5 s` time, then the `sleep 0.8` will extend towards `*.5 + 0.8 = *.3 s`, so this will be again a next whole second and the scheduler will again fire-up immediately without processing any keys.

So, this is not-a-bug situation IMO, because in the real world there aren't sequences of `> 0.5 s` running plugins, there are at worst `0.5 s + 0.0* s + 0.0* s + …` sequences, which will not block they processing of the keys.

**Comment by romkatv** [comment]
Thank you for looking into it and for explaining what is going on.

Hypothetically, suppose I have 3 plugins with each of them taking 1 second to load. Is there any advantage in using `wait"0"` to load these plugins compared to plain `zplugin light`?

**Comment by psprint** [comment]
No, the shell will be locked like in the `sched-func()…` example.

**Comment by romkatv** [comment]
I'm still trying to understand the conditions under which no keyboard input is processed after loading a plugin in turbo mode. If I understand your explanation correctly, keyboard input should be processed after a plugin is loaded if and only if

- this is the last plugin
*OR*
- the plugin's start and end timestamps are identical when truncated to whole seconds

If this were so, keyboard input would be processed after every 2nd plugin when each plugin takes 0.5 seconds to load. This isn't what happens in practice though. Here's what I've tried.

1. Run this command:
```zsh
docker run -e LANG=en_US.utf8 -e TERM -it --rm archlinux/base bash -uec '
  pacman -Sy --noconfirm zsh git curl nano

  curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh |
    sh >/dev/null

  echo "sleep 0.5; PROMPT=\"1> \"" >~/plugin-1.zsh
  echo "sleep 0.5; PROMPT=\"2> \"" >~/plugin-2.zsh
  echo "sleep 0.5; PROMPT=\"3> \"" >~/plugin-3.zsh
  echo "sleep 0.5; PROMPT=\"4> \"" >~/plugin-4.zsh
  echo "sleep 0.5; PROMPT=\"5> \"" >~/plugin-5.zsh
  echo "sleep 0.5; PROMPT=\"6> \"" >~/plugin-6.zsh
  echo "sleep 0.5; PROMPT=\"7> \"" >~/plugin-7.zsh
  echo "sleep 0.5; PROMPT=\"8> \"" >~/plugin-8.zsh
  echo "sleep 0.5; PROMPT=\"9> \"" >~/plugin-9.zsh
  echo "PROMPT=\"done> \"" >~/plugin-done.zsh

  >>~/.zshrc cat <<END
PROMPT="0> "
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-1.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-2.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-3.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-4.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-5.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-6.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-7.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-8.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-9.zsh
zplugin ice silent nocd wait"!"
zplugin snippet ~/plugin-done.zsh
END

  exec zsh'
```
2. Wait for prompt to become `done> `.
3. Type `zsh` and press and hold `ENTER`.
4. Once prompt turns to `done> `, see which other promps appear on the screen. If prompt `N> ` is visible, it means keyboard input was processed after loading plugin number `N`.

I expected to see in most cases `1`, `3`, `5`, `7`, `9` or `2`, `4`, `6`, `8`. In practice never see any of these combinations. Here are the ones I've observed:

- `1`, `3`, `7`
- `1`, `4`, `8`
- `2`, `4`, `8`
- `2`, `6`
- `2`, `5`

A few prompts are always missing. In the last output (`2`, `5`), no keyboard input was processed after loading four plugins in a row (`6`, `7`, `8` and `9`). Such output is rare but `2`, `6` happens quite often (no output after three plugins in a row, twice). How is this possible?

**Comment by psprint** [comment]
The times are to tight – the scheduler takes ~5…10 ms to run, and also the execution of the `sleep` command takes some time. If you change the `sleep` time from `0.5` to `0.45`, then you'll see what's expected: the keyboard processing happening every 2nd snippet.

**Comment by romkatv** [comment]
> The times are to tight...

I can see how this can explain a gap of two numbers (`4` after `1`, or `5` after `2`) but I cannot figure out why there are also gaps of three numbers (`6` after `2`) or even four numbers (`done` after `5`)?

I added logging to every plugin to know when it gets loaded. I then ran `zsh` a few times until I've got the prompt sequence with just `2`, `5` and `done`. Here are the times when each plugin finished loading.

```zsh
1 1571476391.4824023247
2 1571476391.9909689426
3 1571476392.5012941360
4 1571476393.0097448826
5 1571476393.5180583000
6 1571476394.0319602489
7 1571476394.5401992798
8 1571476395.0483226776
9 1571476395.5565848351
done 1571476395.5632114410
```

How is it possible that with this timing no keyboard input was processed after plugins `6`, `7`, `8` and `9`? I think your explanation works for `6` and `8` but not for `7` or `9`.

**Comment by psprint** [comment]
I think that the method of testing where the key is being hold is not without a fault here – by changing the method to quick presses of the key the keyboard is being processed correctly with the gaps being not larger than `1`.

**Comment by romkatv** [comment]
Thanks, Sebastian. I've updated my expectation of zsh responsiveness when using turbo mode. While it would be convenient if buffered keyboard input was processed after every plugin, or if there was a simple criterion for determining when it will be processed, I can accept that zplugin doesn't provide a guarantee one way or another.

I suggest that we close the issue.
