### ISSUE TITLE
[help] zplugin in termux(android app)

### ISSUE THREAD

**Issue by alo0oz** [zdharma/zplugin#187]
I'm trying to use zplugin in termux. But the plugins are not loading. it's showing `No command zplugin found`
What's the problem

**Comment by psprint** [comment]
You must first install Zplugin by: 

```zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
```

**Comment by psprint** [comment]
I think that the testing by holding a key is not without a fault – by changing the method to quick presses of the key, the keyboard is being processed correctly and there are no larger gaps than 1 missed number.
