### ISSUE TITLE
command not found: compdef

### ISSUE THREAD

**Issue by prandelicious** [zdharma/zplugin#188]
I have a program that exports its autocomplete stuff via `awless completion zsh` and the suggested way of doing it is adding this to the end of `.zshrc`: `source <(awless completion aws)`. Whenever I do that, I get this error message:

`command not found: compdef`

I'm loading it via:
 ```
zplugin ice from"gh-r" as"program" atload"source <(awless completion zsh)"
 zplugin light wallix/awless
```

**Comment by psprint** [comment]
Thanks, I've updated Zplugin. The `compdef` wasn't provided for the `as"program"` plugins. It now is, however the `atload'…'` ice has to be preceded with exclamation mark, i.e.:

```zsh
zplugin ice from"gh-r" as"program" atload"!source <(awless completion zsh)"
zplugin light wallix/awless
```

**Comment by prandelicious** [comment]
Awesome! Thanks for the quick response! I'll try it out and will let you know!

**Comment by psprint** [comment]
I'm glad that I helped.
