### ISSUE TITLE
Excessive paging during `update-all`

### ISSUE THREAD

**Issue by agkozak** [zdharma/zplugin#19]
Running `update` now causes my git pager to open and `update-all` causes it to open repeatedly; is this the desired behavior, or should `git log` be `git --no-pager log`? [Since commit 0a6b5abbc3c28a83af83ee20af062021fc985fc4](https://github.com/zdharma/zplugin/commit/0a6b5abbc3c28a83af83ee20af062021fc985fc4).

**Comment by psprint** [comment]
Thanks. I use `export LESS=-iRFX` so I didn't spot that. `--no-pager` is a new option, doesn't exist in my Apple's `git` `2.7.4`, so I've solved this by piping `git log` to `less -F`.

**Comment by agkozak** [comment]
Nice solution! Thanks.
