### ISSUE TITLE
"command not found" for program sourced in atload

### ISSUE THREAD

**Issue by prandelicious** [zdharma/zplugin#191]
I have a prompt that is loaded this way:
```
zplugin ice from"gh-r" as"program" atload"!eval $(starship init zsh)"
zplugin light starship/starship
```
Works fine on initial pull but when I start a new shell, it complains of not being able to find `starship`, the binary.

**Comment by psprint** [comment]
The contents of the ice have to be quoted, otherwise they'll execute immediately, i.e.:

```zsh
zplugin ice from"gh-r" as"program" atload'!eval $(starship init zsh)'
zplugin load starship/starship
```

**Comment by x1a0** [comment]
Just got the same problem. I think it's due to the binary file is under `target/x86_64-unknown-linux-gnu/release/starship` which is not in `$PATH`.
What would be the zplugin way to solve it?

**Comment by NICHOLAS85** [comment]
Use the `pick` ice to specify the file to source/set as command. The following should work as long as the naming structure doesn't change in the future.
```
zplugin ice from"gh-r" as"program" atload'!eval $(starship init zsh)' pick'target/x86_64-unknown-linux-gnu/release/starship'
zplugin load starship/starship
```

**Comment by x1a0** [comment]
@NICHOLAS85 Thanks for the reply! Is it possible to not hardcode the `x86_64-unknown-linux-gnu` string? I am not sure how `zplugin` figured it out and decided to download for that architecture, or was it some Github magic.

BTW I just found the new rust plugin `z-a-rust` which solves this particular problem for me as it's a rust project. Many thanks @psprint !

**Comment by NICHOLAS85** [comment]
You can replace it with `pick'*/*/*/starship'`. The `bpick` ice can be used to specify what release zplugin choses to download. I think it matches by the first linux match. ie `bpick'*linux64*'` would match `micro-1.4.1-linux64.tar.gz`
