### ISSUE TITLE
Colons are not preserved in fpath anymore

### ISSUE THREAD

**Issue by laggardkernel** [zdharma/zplugin#192]
The problem was reported under a commit comment. https://github.com/zdharma/zplugin/commit/ecf0bf3e59e30d13d204d0a76a6b377fd2524fdc

Later, it was fixed by commit https://github.com/zdharma/zplugin/commit/ea9302b5090743cf6e2b590672bffa40fef3706f

But now, the double colons `::` are not preserved in `fpath` anymore. Checking the source code, the fix above seems to have been reverted.

**Update**

The problem may be related with the fix for issue #127.

**Comment by psprint** [comment]
Thanks. Why are the double colons important?

**Comment by laggardkernel** [comment]
It was explained in the [comment of ecf0bf3](https://github.com/zdharma/zplugin/commit/ecf0bf3e59e30d13d204d0a76a6b377fd2524fdc#commitcomment-31833883).

The prezto modules may add sub-folder named `functions` into `fpath`. That's where the modules put their `autoload` files. And the problem is all the prezto modules are put under a folder named `PZT::modules` by default.

A more detailed example was given in the link above with prezto module osx.

**Comment by psprint** [comment]
Thanks! It's fixed now.

**Comment by laggardkernel** [comment]
No, thank you. Confirmed colons are preserved now.
