### ISSUE TITLE
zplugin snippet follow redirect

### ISSUE THREAD

**Issue by chhschou** [zdharma/zplugin#195]
Hi @psprint.

Problem: For some resource, the public URL is a shortened URL which redirects to the actual URL to download a file. For instance `https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US` redirects to `https://download-installer.cdn.mozilla.net/pub/devedition/releases/71.0b4/mac/en-US/Firefox%2071.0b4.dmg`. It makes more sense to use the public URL for a snippet to obtain the file instead of using the redirect URL which over time may point to an outdated resource.

Suggested solution:
I would like to be able to use a modifier to make zplugin follow redirects. With cURL this can be done with the `-L` switch

An alternative is using a script to get the redirect URL then call `zplugin snippet`. This is not ideal because I won't be able to update the snippet, it will create a new `zplugin snippet` each time. I could save the snippet URL, compare with the new snippet URL then clean up and reinstall... 

Happy to discuss the use case further.

**Comment by psprint** [comment]
Hello,
the `curl` call [uses](https://github.com/zdharma/zplugin/blob/4b7e68e/zplugin-install.zsh#L319) `-L` switch. The file is properly downloaded with:

```zsh
zplugin ice as"command" mv'* -> firefox.dmg.bz2' atclone'bunzip2 *' notify
zplugin snippet "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US"
```

What problems did you observe?

**Comment by chhschou** [comment]
hmm... it wasn't doing that before, but it was a while since I tried. I'll try again.

**Comment by chhschou** [comment]
Okay I think I didn't have `id-as` before hence it was doing things that I didn't expect, your code works thanks.

**Comment by chhschou** [comment]
@psprint 
Does update work for a snippet like this? It doesn't work for me:
`zplugin update firefox`                                     

Updating snippet firefox... (identified as firefox)
Downloading `firefox' (with wget, curl, lftp)...
-zplg-download-snippet:113: is a directory: firefox/firefox
-zplg-download-snippet:114: is a directory: firefox/firefox
rm: cannot remove 'firefox/firefox': Is a directory
Download failed. No available download tool? (one of: curl, wget, lftp, lynx)

```
zplugin ice id-as"firefox" as'program' pick'firefox/firefox' \
  mv'firefox -> firefox.tar.bz2' \
  atclone'tar jxf *.tar.bz2; rm *.tar.bz2;' \
  atpull'%atclone'
zplugin snippet "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US"

```

**Comment by psprint** [comment]
Hi!
I would like to inform you that there's is now a [Zsh/NPM package](https://github.com/zsh-packages/firefox-dev) of the Firefox Developer Edition :) It'll currently work only on Linux, I guess, as I don't have OS X box to test it.
