### ISSUE TITLE
zplugin keeps printing the latest exit code with `printexitvalue` set

### ISSUE THREAD

**Issue by hugoh** [zdharma/zplugin#196]
**Describe the bug**

When using `setopt printexitvalue`, zplugin keeps printing the last exit value.

**To Reproduce**

```sh
% zsh -f
% source zplugin.zsh
% false
% setopt printexitvalue
% false
zsh: exit 1
% zsh: exit 1
zsh: exit 1
zsh: exit 1
zsh: exit 1
zsh: exit 1
[ continues forever ]

```

**Expected behavior**

```sh
% zsh -f
% source zplugin.zsh
% false
% setopt printexitvalue
% false
zsh: exit 1
% 
```

**Versions:**
 - $ZSH_VERSION == 5.3
 - Operating system name and version: MacOS 10.14.6

**Comment by psprint** [comment]
That has been fixed today. After `self-update` the issue will be gone.
