### ISSUE TITLE
What is the purpose of ZSH_CACHE_DIR?

### ISSUE THREAD

**Issue by dylanjm** [zdharma/zplugin#197]
**Describe the bug**

Zplugin on startup always creates an empty folder titled `zplugin` in my cache directory of my home folder. 

**To Reproduce**

This behavior is caused by lines 64-66 in `zplugin.zsh`

```zsh
export ZPFX=${~ZPFX} ZSH_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache/zplugin}" PATH=${~ZPFX}/bin:"$PATH"

[[ ! -d $ZSH_CACHE_DIR ]] && command mkdir -p "$ZSH_CACHE_DIR"
```

**Expected behavior**

Not quite sure what should be happening here. My expectation is that in my `.zshenv` I set

```zsh
export CACHE_HOME="$HOME/.cache"
ZPLGM[HOME_DIR]="$CACHE_HOME/zsh/zplugin"
ZPLGM[ZCOMPDUMP_PATH]=$CACHE_HOME/zsh/zcompdump
```
such that `ZSH_CACHE_DIR` isn't needed. It's always empty anyway. 

**Versions:**
 - $ZSH_VERSION :

`zsh 5.7.1 (x86_64-apple-darwin18.2.0)`

 - Operating system name and version (uname -a): 

`Darwin INL610025 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

**Additional context**
Just ran `zpl self-update` this morning.

**Comment by psprint** [comment]
It was added as the result of #174. Is it a big problem that the directory is created?

**Comment by dylanjm** [comment]
Not particularly so, I was curious of its purpose. I've added a line in my `.zshrc` to remove that folder if it exists.
