### ISSUE TITLE
Default ice modifiers or loops

### ISSUE THREAD

**Issue by adberard** [zdharma/zplugin#198]
**Is your feature request related to a problem? Please describe.**
I get the feeling that zplugin is much more verbose that needed on some functionalities 

For example if I dont want any of my plugin to have a depth > 1 or if I want to group the plugins together with the same command
Here is a draft of what I think could be clearer.
```
zplugin ice depth'1'
zplugin light denysdovhan/spaceship-prompt 
zplugin ice depth'1' as"program" pick"mu"
zplugin light fabioz/mu-repo
zplugin ice depth'1'
zplugin light zsh-users/zsh-autosuggestions
zplugin ice depth'1' as"program" pick"ranger.py"
zplugin light ranger/ranger
zplugin ice depth'1' as"program" pick"bin/git-dsf"
zplugin light zdharma/zsh-diff-so-fancy
zplugin ice depth'1' lucid wait'1'
zplugin light wfxr/formarks
zplugin ice depth'1' lucid wait'1'
zplugin light wfxr/forgit
zplugin ice depth'1' lucid wait'1'
zplugin light Tarrasch/zsh-bd
```
**Describe the solution you'd like**
This is what came to my mind in order to simplify
```
zplugin ice default set light depth'1' for \
  denysdovhan/spaceship-prompt \
  zsh-users/zsh-autosuggestions

zplugin ice default set light as"program" depth'1'  for \
  pick"mu" fabioz/mu-repo \
  pick"ranger.py" ranger/ranger \
  pick"bin/git-dsf" zdharma/zsh-diff-so-fancy

zplugin ice default set light lucid wait'1'  depth'1' for \
   wfxr/formarks \
   wfxr/forgit \
   Tarrasch/zsh-bd
```

Or with a global config set
```
zplugin config set light depth'1'

zplugin for \
  denysdovhan/spaceship-prompt \
  zsh-users/zsh-autosuggestions

zplugin as"program" for \
  pick"mu" fabioz/mu-repo \
  pick"ranger.py" ranger/ranger \
  pick"bin/git-dsf" zdharma/zsh-diff-so-fancy

zplugin lucid wait'1' for \
  wfxr/formarks \
  wfxr/forgit \
  Tarrasch/zsh-bd
```

What do you think could be clearer while still avoiding code duplication ?

**Comment by psprint** [comment]
That are very meaningful and interesting propositions for a new syntax. I like them and I'll implement them soon, first discussing it here.

**Comment by adberard** [comment]
Glad to see that you are enthusiast about modifying this precious tool
I could go as far as suggesting to use an old syntax rather than a new one : classic gnu cli style so we could event do very native and familiar looking shell things :
```
zplugin --light --wait 1 --silent  --from gh-r --as program --pick lsd  Peltoche/lsd

export ZPLG_OPT= '--wait 1 --silent --depth 1 '
zplugin changuhen/fz

# or more explicit so there is no 'magic' options passed 20 lines above
zplugin $ZPLG_OPT zsh-users/zsh-autosuggestions  denysdovhan/spaceship-prompt
```

**Comment by psprint** [comment]
Thanks for another version of the proposition. I think that the GNU option style is little hard on  eyes – I find such text slightly repelling at first. However, having the [alternate ice syntax](http://zdharma.org/zplugin/wiki/Alternate-Ice-Syntax/) example, the GNU style could be implemented too, as an available option.

From the previous propositions I think that the 2nd proposition is better. I see only one problem – the plugin might begin with the name of the ice, e.g.: `aston/aplugin` – here the substring `as` would be interpreted as the `as` ice. Or the plugin `zsh-users/zsh-autosuggestions` would collide with the ice `zsh` that I plan to add. However, I think that there's a simple solution to it – to, in case of the collision, to precede the plugin name with a special character. I'm thinking about which one could it be. The easiest would be `\\`, however it has to be given twice if unquoted to be passed through to the function.

I don't see any more flaws in it and I'm starting to implement it today. Hold your thumbs. And in case of any other ideas or remarks, don't hesitate to post them.

**Comment by psprint** [comment]
Implemented! The code was just too simple! Hope that everything is OK.

**Comment by psprint** [comment]
I'll hold with implementing the `config set default` for now, as the for syntax allows to specify default ices for groups of plugins.
