### ISSUE TITLE
Allow passing ice arguments directly to command instead of as seperate command

### ISSUE THREAD

**Issue by tmccombs** [zdharma/zplugin#199]
**Is your feature request related to a problem? Please describe.**
I really like the functionality of zplugin, but the CLI seems very strange to me. In particular, having to run a separate command to set the options, and the unusual syntax of keyword followed by quoted value.

**Describe the solution you'd like**
Have a way to pass ice options directly to zplugin commands rather than have to run a seperate `zplugin ice` command first.

**Comment by psprint** [comment]
The feature will be added soon, and as of the ice syntax, see:

http://zdharma.org/zplugin/wiki/Alternate-Ice-Syntax/

**Comment by psprint** [comment]
The feature has been implemented – it's called *for-syntax*, see: [News](https://github.com/zdharma/zplugin#news) and #198 .
