### ISSUE TITLE
shwordsplit causes error in -zplg-scheduler

### ISSUE THREAD

**Issue by technicalflaw** [zdharma/zplugin#200]
**Describe the bug**
When the ```shwordsplit``` option is set, making the current directory a folder containing that contains a space cause an error in the scheduler plugin.

For example, ```cd /Volumes/Macintosh\ HD``` causes
```-zplg-scheduler:1: bad math expression: operand expected at `/Volumes/M...'```

**To Reproduce**
Add ```setopt shwordsplit``` in ```.zshrc```
```cd``` to a folder containing a space.

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): ```Darwin mbp 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64```

**Additional context**
Setting ```shwordsplit``` Is probably a bad idea, but it should probably be handled too. See http://zsh.sourceforge.net/FAQ/zshfaq03.html

**Comment by psprint** [comment]
Fixed, thanks!

I always code in a KSH_ARRAYS-compatible way, also taking SH_WORD_SPLIT into account, but this time I've slipped.
