### ISSUE TITLE
Zplugin tries to load a snippet "-b" instead of actual snippet

### ISSUE THREAD

**Issue by xduugu** [zdharma/zplugin#204]
**Describe the bug**
Since commit b6c50a29c78bcab10b083a415759aa47384afce3, my snippet `OMZ::lib/key-bindings.zsh` cannot be loaded anymore. For some reason, zplugin tries to load a snippet `-b` instead of the actual snippet.

**To Reproduce**
Add the following line to the .zshrc:
```
zplugin snippet OMZ::lib/key-bindings.zsh
```

**Versions:**
 - $ZSH_VERSION: 5.7.1

**Comment by psprint** [comment]
It should be now fixed.

**Comment by xduugu** [comment]
Yes, it works again. Thanks!
