### ISSUE TITLE
asdf-vm/asdf no longer works due to "-" in name

### ISSUE THREAD

**Issue by chhschou** [zdharma/zplugin#207]
**Describe the bug**
`zplugin light asdf-vm/asdf` is ignored. I fork the repo into my github `chhschou/asdf` and it works as expected

**To Reproduce**
try `zplugin light asdf-vm/asdf`

**Expected behavior**
Expect the repo to be cloned correctly.

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a): Linux

**Additional context**
This is cause by the latest zplugin, It happened after I complete reinstalled zplugin.

**Comment by psprint** [comment]
It's fixed, thanks!
