### ISSUE TITLE
Download binaries from a release on a private github repo

### ISSUE THREAD

**Issue by whi-tw** [zdharma/zplugin#209]
**Is your feature request related to a problem? Please describe.**
It would be really handy to be able to download a release from a private github repository.

**Describe the solution you'd like**
I'd like to be able to specify something like `from"${gh-user}@gh-r"` in order to be able to auth to a private repository.

**Describe alternatives you've considered**
I've considered `make`ing the repo as normal, but it requires the user to have `go` installed for the one I have in mind, which may not be available.

**Additional context**
At @alphagov, we have an internal tool that I'd like to be able to keep updated with zplugin. It's on a private repo. At the moment, it requires the user to have `go` installed in order to `make` the binary. We build binaries with CI on release, and it'd be good to be able to pull them down and use them rather than rebuilding it locally.

**Comment by psprint** [comment]
I've committed the update. It works like you've suggested, i.e.: `from'user:password@gh-r'`. Could you check if it helps?

**Comment by whi-tw** [comment]
This works for an account I have with no 2fa, but isn't a happy puppy when used with an access token for the password - the non-api endpoints don't work with an access token.

I wonder if an api solution might be better. I've had a poke, and it seems doable, just json parsing in *sh is a bit gross, and i'm not sure whether passing the task off to ruby (or perl ☹️ ) is appropriate for zplugin.

**Comment by psprint** [comment]
Zplugin has a

sob., 23 lis 2019, 23:01 użytkownik whi-tw <notifications@github.com>
napisał:

**Comment by psprint** [comment]
Zplugin has a json parsing function from zdharma/zsh-string-lib. It'll be
used for the upcoming npm package support. It's in zplugin-install.zsh.

sob., 23 lis 2019, 23:28 użytkownik Sebastian Gniazdowski <
sgniazdowski@gmail.com> napisał:
