### ISSUE TITLE
Newly downloaded snippets are not being updated via zplugin update --all command

### ISSUE THREAD

**Issue by NICHOLAS85** [zdharma/zplugin#212]
**Describe the bug**
As of 1c46ec88d1c0db9c3113c86188f8db42c17f3578 new downloaded snippets are not updated via `zplugin update --all`. The empty `id-as` ice file is not being created for these snippets which is what is checked for when updating: https://github.com/zdharma/zplugin/blob/855f11259a03d286685bc21901cf03efb932be5e/zplugin-autoload.zsh#L1613

**To Reproduce**
Delete any previously downloaded snippet, allow snippet to redownload, then run `zplugin update`.

**Expected behavior**
Snippets to update on `zplugin update`

**Screenshots**

**Versions:**
 - $ZSH_VERSION == 5.7.1
 - Operating system name and version (uname -a):
Linux Nicks-Laptop 5.3.0-10.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.3-5.1~bullseye (2019-11-10) x86_64 GNU/Linux

**Additional context**

**Comment by psprint** [comment]
Should be fixed.
