### ISSUE TITLE
zplugin deletes lines printed by .zshrc

### ISSUE THREAD

**Issue by agkozak** [zdharma/zplugin#214]
**Describe the bug**

My [`.zshrc`](https://github.com/agkozak/dotfiles/blob/5baff8b0049c97662f94fdefa92c565a19b58a17/.zshrc) outputs some loading benchmarks (when `AGKDOT_BENCHMARKS` is set to `1`). Since `zplugin` commit [fc2df01](https://github.com/zdharma/zplugin/commit/fc2df01ec156cee73a43a854c1acc63223c944b6), as the plugins load, they frequently overwrite these last few lines of text:

[![asciicast](https://asciinema.org/a/CZvM9NyPHPgEoTM1XI6H11Akz.svg)](https://asciinema.org/a/CZvM9NyPHPgEoTM1XI6H11Akz)

**To Reproduce**

Install [my dotfiles](https://github.com/agkozak/dotfiles), `export AGKDOT_BENCHMARKS=1`, and repeatedly launch `zsh` on `zplugin`  commit `fc2df01` or later.

**Expected behavior**

As recently as commit [37dbe96](https://github.com/zdharma/zplugin/commit/37dbe9696520ebf5fd8be813f375d4d4adb6e639), the three lines of benchmarking information printed out and remained on the screen:

[![asciicast](https://asciinema.org/a/NGtkDN3AUchDFzU05DYMgGaOn.svg)](https://asciinema.org/a/NGtkDN3AUchDFzU05DYMgGaOn)

**Versions:**
 - `$ZSH_VERSION` == 5.3.1, 5.7.1
 - Operating system name and version (`uname -a`):
   - Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
   - MSYS_NT-10.0-18362 Sophronios 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
   - Linux kozak 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by moonrumble** [comment]
It started happeninng after following comit.

fc2df01 zplugin: Intermediate code - loading of disk ices for the npm packages

**Comment by psprint** [comment]
It should be fixed now as the committed code shouldn't get activated.
