### ISSUE TITLE
Unexpected behavior after an update

### ISSUE THREAD

**Issue by moonrumble** [zdharma/zplugin#215]
**Describe the bug**

zplugin publish message which was not being published eariler. 

-zplg-deploy-message:13: can't clobber parameter THEFD containing file descriptor 0

**To Reproduce**

zpl ice svn ; zpl snippet PZT::modules/directory

**Expected behavior**

It should just load plugin silently.

**Versions:**
 - $ZSH_VERSION ==  zsh 5.7.1 (x86_64-debian-linux-gnu)
 - Operating system name and version (uname -a): WSL debian

**Additional context**

Following commit is causing the issue. If I reset zplugin to prevvious commit. it works as expected.

fc2df01 zplugin: Intermediate code - loading of disk ices for the npm packages

**Comment by moonrumble** [comment]
It is fixed along with Fixes #214.

**Comment by psprint** [comment]
Great, thanks!
