### ISSUE TITLE
Feature request: atdeletion ice modifier

### ISSUE THREAD

**Issue by pschmitt** [zdharma/zplugin#216]
I'm trying out a few things with zplugin and various python tools I use.
Here's an example of what my config looks like:
```bash
pytools=(ipython pipenv)
zplugin ice as"program" pick"/dev/null" id-as"pytools" \
  atclone"pip3 install -U --user ${pytools[@]}" atpull"%atclone" run-atpull
zplugin light zdharma/null
```
This does install ipython and pipenv on init. But since it's a hackish way of installing stuff with zplugin the deletion of the plugin does not trigger the uninstallation of the python tools.
What I'd like to see is an `atdeletion` ice modifier.

This would make the above look like this for example:
```bash
pytools=(ipython pipenv)
zplugin ice as"program" pick"/dev/null" id-as"pytools" \
  atclone"pip3 install -U --user ${pytools[@]}" atpull"%atclone" run-atpull \
  atdeletion"pip3 uninstall -U --user ${pytools[@]}"
zplugin light zdharma/null
```

which would correctly uninstall ipython and pipenv when issuing `zplugin delete pytools`.

**Comment by psprint** [comment]
Yes, such ice is planned and will be implemented very soon.

czw., 21 lis 2019, 10:19 użytkownik Philipp Schmitt <
notifications@github.com> napisał:

**Comment by psprint** [comment]
It's implemented. I've picked the shorter name `atdelete''` for the ice.

However, `pip3` uses some other option for uninstalling from the user's directory – `pip3 uninstall --user` returns: `no such option: --user`. Also, the command should use `[*]` instead of `[@]` because otherwise the second element will be passed as a separate argument, resulting in incorrect ice being passed and the ice processing interrupted. To summarize:

```zsh
pytools=(ipython pipenv)
zplugin ice as"program" pick"/dev/null" id-as"pytools" \
  atclone"pip3 install -U --user ${pytools[*]}" atpull"%atclone" run-atpull \
  atdelete"pip3 uninstall --user ${pytools[*]}"
zplugin light zdharma/null
```

**Comment by pschmitt** [comment]
Thanks a lot, man!

Here's what I ended up putting in my config file:
```
pytools=(ipython pipenv twine)
zplugin ice wait lucid as"program" pick"/dev/null" id-as"pytools" \
  atclone"pip3 install -U --user --ignore-installed ${pytools[*]}" \
  atpull"%atclone" run-atpull atdelete"pip3 uninstall -y ${pytools[*]}"
zplugin light zdharma/null
```

The `--ignore-installed` makes pip install the packages as "`--user`", even if it was already installed system-wide. Without it, you get permission errors when trying to uninstall it.
Thanks, again!

**Comment by psprint** [comment]
> Thanks, again!

No problem, I'm glad that I could help.
