### ISSUE TITLE
zplugin completions no longer loaded on base install

### ISSUE THREAD

**Issue by davidosomething** [zdharma/zplugin#22]

**Comment by psprint** [comment]
I did full zplugin reinstall (moving away old `~/.zplugin` and cleaning `~/.zshrc`), and the completion indeed didn't load, but the reason was that together with zplugin commands, I've also removed `compinit`. Maybe that's the cause? The completion works fine if there's `compinit`.

**Comment by davidosomething** [comment]
What was the resolution for this?
Added this back before loading zplg

```
autoload -Uz compinit promptinit
compinit
```

but the completions are not found, do I need to manually add to fpath now?
`(eval):1: _zplugin: function definition file not found`

**Comment by psprint** [comment]
No `fpath` isn't necessary, nothing has changed here. If `compinit` is being ran before sourcing Zplugin, then the `2` lines are needed somewhere:

```SystemVerilog
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
```
The lines attach Zplugin completion "on-the-fly" to already initialized completion system.

**Comment by davidosomething** [comment]
oh in zplugin--install i see a symlink command that doesn't run for me
I don't have a "local--zplugin" plugin; does zplugin need to self-manage itself? (i.e. `zplugin load ~/.zplugin/bin`)

**Comment by psprint** [comment]
Sorry, I should take a closer look. The `ln -s` was ran only on creation of `${ZPLGM[PLUGINS_DIR]}`. Now this check wants also `_local---zplugin` there. Also, I've fixed few places and `_zplugin` can be now object of `zplugin creinstall _local/zplugin`. Thanks!

**Comment by davidosomething** [comment]
works!
