### ISSUE TITLE
Don't forcefully override ZSH_CACHE_DIR

### ISSUE THREAD

**Issue by leotaku** [zdharma/zplugin#220]
**Is your feature request related to a problem? Please describe.**
I would like to set some custom paths to point to my `ZSH_CACHE_DIR` before I load Zplugin, however zplugin resets `ZSH_CACHE_DIR`, making this unreliable.

**Describe the solution you'd like**
I would like a new option added to `ZPLGM` named e.g. `CACHE_DIR`. Zplugin then only overrides `ZSH_CACHE_DIR` if said option is set.

**Describe alternatives you've considered**
I know it would be possible to set the `XDG_CACHE_HOME` variable that is currently used, but that seems inelegant and may also affect other applications.
If you do not want to add a new option to `ZPLGM` it would also be possible to simply detect if `ZSH_CACHE_DIR` has been set and to then not override it.

**Additional context**
This change might result in most users experiencing that their "ZSH_CACHE_DIR" has changed location. However, cache dirs should never be expected to remain consistent anyway, so this shouldn't be a problem.

**Comment by psprint** [comment]
I've changed the code so that it keeps the previous ZSH_CACHE_DIR setting if it's not empty. So I didn't add CACHE_DIR field to ZPLGM. Is this ok?

**Comment by leotaku** [comment]
Sure that makes sense. In retrospect, `ZSH_CACHE_DIR` doesn't only affect Zplugin, so having its configuration tied to `ZPLGM` probably would have been confusing anyways.

Thanks for your fast response and fix!
