### ISSUE TITLE
pyenv

### ISSUE THREAD

**Issue by cantao** [zdharma/zplugin#221]
First of all, thanks for the amazing work that is zplugin!

I have copied a snippet from http://zdharma.org/zplugin/wiki/GALLERY/ in order to install pyenv as a plugin:

`zplugin ice atclone"./libexec/pyenv init - > zpyenv.zsh"
    atinit'export PYENV_ROOT="$PWD"' atpull"%atclone"
    as'command' pick'bin/pyenv' src"zpyenv.zsh" nocompile'!'
zplugin light pyenv/pyenv`

Pyenv is installed in `~/.zplugin/plugins/pyenv---pyenv` and apparently it seems to be working fine. I can issue

`pyenv install 3.8.0
pyenv global 3.8.0`

in order to install Python 3.8.0 and make it the default version for me. The commands run without error and 3.8.0 is installed **but** I can't use version 3.8.0.

Further investigation has shown that `~/.pyenv/{shims,versions}` are created and referenced in PATH, but are empty (everything is installed in `~/.zplugin/plugins/pyenv---pyenv`).

I tried playing with `PYENV_ROOT` above with no luck.

Any hints or tips?

Thanks you very much!

**Comment by psprint** [comment]
Turns out that the `PYENV_ROOT` var should be also set up at the moment of invoking `pyenv init`:

```zsh
zplugin ice atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init - > zpyenv.zsh' \
    atinit'export PYENV_ROOT="$PWD"' atpull"%atclone" \
    as'command' pick'bin/pyenv' src"zpyenv.zsh" nocompile'!'
zplugin light pyenv/pyenv
```

It'll then work.

**Comment by cantao** [comment]
Hi @psprint , thanks for the fast response!

Your solution makes sense and in fact PATH seems to be ok, as well as, my pyenv installation (cleared everything and reinstalled).

The problem now is that, even with shims directory coming first in PATH, the system Python is always being chosen. I'ii investigate a little further.

**Comment by cantao** [comment]
Ok, it was all a matter of
`pyenv rehash && rehash`

Closing as solved!

**Comment by psprint** [comment]
Great. Thanks for sharing additional information.
