### ISSUE TITLE
Pyenv with pyenv-virtualenv

### ISSUE THREAD

**Issue by Boolalou** [zdharma/zplugin#233]
Hello,

I want to use [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) plugin with pyenv. I installed pyenv:

`zplugin as'null' lucid  atinit'export PYENV_ROOT="$PWD"' \
    atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init - > zpyenv.zsh' \
    atpull"%atclone" src"zpyenv.zsh" nocompile'!' sbin"bin/pyenv" for \
pyenv/pyenv
`
I don't know how I can install pyenv-virtualenv with zplugin so I installed it like a pyenv plugin:

`git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv`

When I try to use **pyenv activate myvenv**, I have the following error:

> Failed to activate virtualenv.
> 
> Perhaps pyenv-virtualenv has not been loaded into your shell properly.
> Please restart current shell and try again.

To solve the issue, I need to run **eval "$(pyenv init -)"** before to try to activate my virtualenv.

Can I get by without using "eval" ?

Thanks for you help and for the amazing work that is zplugin :)

**Comment by Boolalou** [comment]
Hello,

That works with the following configuration:

```
zplugin as'null' wait lucid \
    atclone'./bin/pyenv-virtualenv-init init - > zpyenv-virtualenv.zsh' \
    atpull"%atclone" src"zpyenv-virtualenv.zsh" nocompile'!' sbin"bin/*" for \
pyenv/pyenv-virtualenv

zplugin as'null' wait lucid atinit'export PYENV_ROOT="$PWD"' \
    atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init - > zpyenv.zsh' \
    atpull"%atclone" src"zpyenv.zsh" nocompile'!' sbin"bin/pyenv" for \
pyenv/pyenv
```
If anyone has a better solution, don't hesitate to share it :)

**Comment by psprint** [comment]
Thanks for sharing. You probably knowing this but there's a package for `pyenv` so that `zplugin pack for pyenv` works too.
