### ISSUE TITLE
New project-name poll (2nd round)

### ISSUE THREAD

**Issue by psprint** [zdharma/zplugin#235]
Hi!
Below are the candidates from #181 that received 4 or more votes. Providing a proposition counted as a vote (except for my own propositions). Finally, I've decided that only thumbs-up counts.

The "zplugin" proposition isn't here even though it received 25 votes because I would really want to change the name. Also, `zin` was too similar to `zim`.

You can still provide new propositions here by creating a post (so this round isn't a closed one, just a clearing one).

I'm still reviewing the recent additions to the previous post and move them here if they qualify. The current number of candidates is 9.

**Update:** I've decided to add one other requirement: that the name is at least 4 characters long. For this reason I've withdrawn the candidate `zpl`. I hope that you'll understand and find other candidate that you like, if your favorite was `zpl`.

**Comment by psprint** [comment]
`zin`

**Comment by psprint** [comment]
`zupply`

**Comment by psprint** [comment]
`zenith`

**Comment by psprint** [comment]
`zeta`

**Comment by psprint** [comment]
`zinit`

**Comment by psprint** [comment]
`zpackage`

**Comment by psprint** [comment]
`zpl`

**Comment by psprint** [comment]
`zpack`

**Comment by psprint** [comment]
`zpick`

**Comment by psprint** [comment]
`zphere`

**Comment by psprint** [comment]
**zoom**

by @itai33

**Comment by tke** [comment]
`zupple`

* hints at the flexible nature of the tool
* can still retain the `zpl` alias people are attached to, and pronounced the same

**Comment by indolering** [comment]
I think zinit is misleading: Zplugin does more than just init ZSH, it's a configuration and package manager.

**Comment by Cueball** [comment]
> I think zinit is misleading: Zplugin does more than just init ZSH, it's a configuration and package manager.

FTR I didn't post the name `zinit`; I just copied it over from the announcement on Reddit (that @psprint made in October).

As per the first issue #181 about a name change, the [reddit post announcing](https://www.reddit.com/r/zsh/comments/dgw2ss/newname_poll_for_the_zplugin_project/f3fru4i) it had a top comment with `zinit` as the short CLI name:

> The GitHub org is Zdharma, right?
Then logically the project should then be Zdharma/Zinitiative 🙃
Which could easily be shortened to zinit on the command line.

So it's short for "Z-Initiative" (I'm guessing?), it's a play on words ('zsh init'), with a pop culture reference. And while you're correct about what zplugin currently, you do generally run it at `init` for each Zsh instance.

I liked it for all those reasons, so I've upvoted it. Do what you like though 😄

**Comment by psprint** [comment]
The poll is now over. The winner is, by 19 votes – 12 more than the next candidates `zenith` and `zeta` (which received 7 votes) – the candidate **zinit**.

Thus, the new name for the plugin manager will be: Dharma Initiative Plugin Manager, with the short name **zinit** – by being hosted at the GitHub org `zdharma` it'll form the `Zdharma` / `Zinit` equivalent of the long, text (non-command) name."Dharma Initiative Plugin Manager", like the original [reddit post](https://www.reddit.com/r/zsh/comments/dgw2ss/newname_poll_for_the_zplugin_project/f3fru4i?utm_source=share&utm_medium=web2x) suggested (only with the `Z`s added in front). Big thanks to the reddit user [DecentHumanAttempt](https://www.reddit.com/user/DecentHumanAttempt/) for the idea and for user @Cueball for putting it to the poll!

I'll start the rename today, hopefully till today everything will be done. The function `zplugin` and aliases `zpl`,`zplg` will be left untouched to not break any configs.
