### ISSUE TITLE
Can't Load "hub" Completions

### ISSUE THREAD

**Issue by rawkode** [zdharma/zplugin#238]
**Describe the bug**
```
zplugin ice wait lucid as"completion"
zplugin snippet https://github.com/github/hub/blob/master/etc/hub.zsh_completion
```

When I run `zplg csearch` or `zplg clist`, I do not see the hub completions. Tabbing on the hub command also doesn't work.

**Comment by romkatv** [comment]
This this instead:

```zsh
zplugin ice wait lucid as"completion"
zplugin snippet https://github.com/github/hub/raw/master/etc/hub.zsh_completion
```

Note `raw` vs `blob` in the URL.

**Comment by rawkode** [comment]
Hi @romkatv, I'd already tried the raw URL too. Unfortunately, it doesn't work :(

**Comment by psprint** [comment]
Try adding `mv'* -> _hub'` ice.

śr., 8 sty 2020, 18:57 użytkownik David McKay <notifications@github.com>
napisał:

**Comment by psprint** [comment]
I'm at a computer right now and I've tested that yes, the `mv''` ice helps:

```zsh
zplugin ice wait lucid as"completion" mv'*ion -> _hub' 
zplugin snippet https://github.com/github/hub/raw/master/etc/hub.zsh_completion
```

**Comment by rawkode** [comment]
Thank you, @psprint.

**Comment by rawkode** [comment]
@psprint Can you explain why `*ion`, so I know how to fix this for others?

**Comment by psprint** [comment]
`*ion` is to match the filename `*.completion`, because using simply `*` could match the renamed file `_hub` resulting in `mv _hub _hub` when updating.
