### ISSUE TITLE
Zplugin module and from"gh-r" conflict?

### ISSUE THREAD

**Issue by lainiwa** [zdharma/zplugin#241]
**Describe the bug**
I reinstalled zplugin with all plugins (a simple `rm -rf ~/.zplugin/`) and now I have an error on loading a plugin from github releases.

**To Reproduce**
Code installing zplugin with module:
```sh
# Install zplugin if not installed
if [ ! -d "${HOME}/.zplugin" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
    zplugin self-update
fi

# Load zplugin
source "${HOME}/.zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# Compile the zplugin`s binary module, if not yet compiled
if [[ ! -f "${ZPLGM[BIN_DIR]}/zmodules/Src/zdharma/zplugin.so" ]]; then
    zplugin module build
fi

# Load zplugin's binary module (`zpmod -h` for help)
module_path+=( "${ZPLGM[BIN_DIR]}/zmodules/Src" )
zmodload zdharma/zplugin
```

Then, the second command prints `-zplg-load-plugin:ZpluginModule:94: can't open file: ./`:
```sh
zplugin ice from"gh-r"
zplugin load junegunn/fzf-bin
```

This message is being printed for every `from"gh-r"` in my config (I didn't test fetching from other websites though).

I tried building (`zplugin module build`) zplugin module with older editions of `zplugin.c` with no result.

As it *did* work well before I reinstalled it, I guess some changes might have been introduced into `zplugin` in recent 1-2 months that cause this behavior.

**Expected behavior**
Expected to work silently.

**Versions:**
 - $ZSH_VERSION == `5.4.2`
 - Operating system name and version (uname -a): `Linux u-navi 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by psprint** [comment]
Thanks. After rebuilding the module the issue should go away.
