### ISSUE TITLE
How to load plugins in a given order

### ISSUE THREAD

**Issue by odelucca** [zdharma/zplugin#242]
Hi.

I'm trying to install [this plugin](https://github.com/bonnefoa/kubectl-fzf). It needs to be loaded after `"plugins/kubectl"` in order to work.

Using `zplug` I would do the following:

~~~bash
zplug "plugins/kubectl", from:oh-my-zsh, defer:2
zplug "bonnefoa/kubectl-fzf", defer:3
~~~

Using `zplugin` I've tried to put those in different lines, use `ice wait` but nothing seems to work. This is my current attempt:

~~~bash
zplugin snippet "OMZ::plugins/kubectl/kubectl.plugin.zsh"
zplugin light "bonnefoa/kubectl-fzf"
~~~

But it is not working.

Can anyone help?

**Comment by psprint** [comment]
The problem is probably the lack of `zplugin cdreplay` or `zpcdreplay` call. Try:

```zsh
zplugin snippet "OMZ::plugins/kubectl/kubectl.plugin.zsh"
zplugin light "bonnefoa/kubectl-fzf"
zplugin cdreplay -q
```

Or in case of using Turbo:

```zsh
zplugin wait for OMZ::plugins/kubectl/kubectl.plugin.zsh
zplugin wait atload"zpcdreplay" light-mode for @bonnefoa/kubectl-fzf
```

**Comment by odelucca** [comment]
That's it! Thanks :)
