### ISSUE TITLE
[Suggestion] name and logo

### ISSUE THREAD

**Issue by untoreh** [zdharma/zplugin#27]
Don't you think zplugin is quite an unoriginal name and clashes with zplug?
IMHO since ice commands are so useful and there is good care for performance `iceplug` makes for a nice name and the logo could be a lightning bolt striking an ice cube

**Comment by psprint** [comment]
Thanks for the suggestion, but it's too late to change name and I really don't think it clashes with zplug, it's the first time I heard about that.
