### ISSUE TITLE
How can I add sub directory of the repo to the path.

### ISSUE THREAD

**Issue by moonrumble** [zdharma/zplugin#28]
For example, I want to add bin directory from https://github.com/tj/git-extras to the path.

**Comment by psprint** [comment]
This worked for me:

```
zplugin ice as"command" pick"bin/git-*"; zplugin light tj/git-extras
```

If pick matches some files, then their surrounding directory is added to PATH, and the files get +x access right.

However the project has makefile. It is cat-ting some files at install. So you could use this:

```
zplugin ice as"command" pick"${ZPLGM[HOME_DIR]}/cmd/bin/git-*" \
            make"install PREFIX=${ZPLGM[HOME_DIR]}/cmd"
zplugin light tj/git-extras
```

Thanks for the issue, I just patched zplugin for this to work, so `zplugin self-update` is needed. Also added this to README.md.

**Comment by psprint** [comment]
PS. make is ran at clone, and at update (if there are new commits). So this is probably needed first:

```
rm -rf ~/.zplugin/plugins/tj---git-extras
```

I probably should add a `delete` subcommand.

**Comment by moonrumble** [comment]
I didn't want to install because I don't need all the command and install doesn't compile the commands in Cygwin environment. It worked after you updated zplugin. 

It took me little time to understand the ice command but it is very powerful.

Thanks
