### ISSUE TITLE
Loading a plugin with wait and silent still prints loaded $pluginname

### ISSUE THREAD

**Issue by moonrumble** [zdharma/zplugin#29]
I am trying to load the following plugin

`zplugin ice silent wait'1'; zplugin light KyleChamberlin/zsh_maven_plugin`

It still prints 

> Loaded KyleChamberlin/zsh_maven_plugin

How can I load a plugin in the background without it printing anything to the console?

**Comment by psprint** [comment]
Ok, I extended `silent` to mute the messages. Had to make a decision, because `silent` does stderr & stdout redirection and this consumes some time on startup, however for turbo-mode loaded plugins this doesn't matter much.

**Comment by moonrumble** [comment]
Thanks. It worked well.
