### ISSUE TITLE
Question: loading commands

### ISSUE THREAD

**Issue by thecontinium** [zdharma/zplugin#31]
Thanks for writing this plugin. I have just started exploring using this and I have a few questions about commands and path.

**scenario**
If I have directories of commands that I want zplugin to manage by adding them to the path, say e.g. one of these directories could be $HOME/bin containing com1.sh, com2.zsh and com3. The other directories would be similar.

**outcome**
I would like to have zplugin manage these so that 
- they are searched for first in the path 
- com1,com2,com3 are the respective commands that I can type at the command line; for the example directory above.

**additionally**
Is there currently a way to remove/delete previously loaded but no longer wanted plugins/snippets/completions ?

Can you clarify the difference between a snippet and a plugin specifically when we are talking about setting them up as commands; ie under what circumstances would you use zplugin snippet rather than zplugin load ?

Is there a way to have just one directory added to the path ( at the beginning if we want ) that holds symbolic links to all commands that zplugin is managing ? 

cheers

**Comment by thecontinium** [comment]
Related to the above questions: When I use zplugin load and then zplugin unload on a command the commands directory does not get removed from the path. Is this correct ?

e.g. if I run 

`zplugin ice from"gh-r" as"command"; zplugin load junegunn/fzf-bin`

it adds this to path:  

`/Users/continium/.cache/zplugin/plugins/junegunn---fzf-bin`

I then run: ` zplugin unload junegunn/fzf-bin`

and get the output 

```
Unregistering plugin junegunn/fzf-bin
Plugin's report saved to $LASTREPORT

```
echo $LASTREPORT gives:


```
Plugin report for junegunn/fzf-bin
----------------------------------
/Users/continium/.cache/zplugin/plugins/junegunn---fzf-bin added to $PATH

```
path still has at the end:
`/Users/continium/.cache/zplugin/plugins/junegunn---fzf-bin`

**Comment by psprint** [comment]
> When I use zplugin load and then zplugin unload on a command the commands directory does not get removed from the path. Is this correct ?

It's an omission, I've fixed it now, after `zplg self-update` it will work. Thinking around to answer your other questions.

**Comment by thecontinium** [comment]
Great - tested and I concur - fixed. 
I see you added to the start rather than the end of path - makes sense. 
look forward to your thoughts on my other questions.

cherrs

**Comment by thecontinium** [comment]
yes - thanks - this works: `zplugin ice as"command" pick"com[[:digit:]]*"; zplugin load %HOME/bin`

Regarding the access rights +x; the behaviour is confusing as it stands. Needs some thought.

Please can you remove the training `/` from the directory` /Users/continium//bin/` that is added to path ?

Regarding delete : both reasons.

Getting the symbolic links working with path would be a big bonus instead of polluting path; where does one donate ?

**Comment by psprint** [comment]
I hope to come up with some clever English sentence so that +x confusing will be minimal.

I don't see the trailing `/`, even when I enter `%HOME/bin/`, but as I rather always add defensive code, I added trailing `/` removal, but can you please double-check that `/` is really added? If not I will revert the patch.

Thanks for offering donation, it will be cool to work on Zplugin. Donate button is on [HSMW](https://github.com/zdharma/history-search-multi-word) page, PayPal may come up in Polish, but switching country to "Australia" switches language to English, and from that point it's possible to switch language to proper one.

**Comment by thecontinium** [comment]
It was really added and the latest update removed it. Thanks.

**Comment by psprint** [comment]
Then great, thanks for pointing this out

**Comment by psprint** [comment]
Added `delete` subcommand ([news](https://github.com/zdharma/zplugin#news)) :). I see you updated the post, I will think on adding option for deleting everything that's not loaded.

**Comment by thecontinium** [comment]
Thanks

Best regards
Matthew
