### ISSUE TITLE
How to add functions to the path which are within plugin?

### ISSUE THREAD

**Issue by moonrumble** [zdharma/zplugin#32]
I am loading `zpl load zimfw/git`. It loads plugins correctly but doesn't add `zimfw/git/functions`  into PATH.

If I change it to `zpl ice as"command" pick"functions/*"; zpl load zimfw/git` only functions get added to path and plugin doesn't load. 

should I be using atinit to source the plugin. I wanted to see if there another way to achieve.

**Comment by psprint** [comment]
Functions are to be autoloaded. Although they may work when treated as commands. Use `src` to source a file when doing `as"command"`.

The plugin loads correctly as svn snippet. It then autoloads `functions` directory (and adds it to `FPATH`):

```
zpl ice svn; zpl snippet https://github.com/zimfw/git/trunk
```

**Comment by moonrumble** [comment]
I don't have svn installed. I use git only. `zpl load zimfw/git` doesn't load the fucntions. 

Shouldn't `zpl ice svn` and  `zpl load` behave the same way?

**Comment by psprint** [comment]
Snippets have Prezto support. The `PZT::` prefix, dependencies, `functions` directory autoloading. `zimfw/git` looks like 100% Prezto-targetted plugin. I might add some Ice-mod for autoloading a directory with functions, will think, adding heavy Prezto-things to plugins isn't a good idea.

BTW. if you use Zsh 5.4 then it is supporting autoload-via-absolute-path, and you can do:

```
zplugin ice atload'autoload $PWD/functions/*'; zplugin load zimfw/git
```

On the other hand, Zsh < 5.4 isn't that much more complex:

```
zpl ice atload'fpath+=( $PWD/functions ); autoload $PWD/functions/*(:t)'; zpl load zimfw/git
```

Reports will not have those autoloads, I think tomorrow if they should be included.

**Comment by moonrumble** [comment]
For some reason, the first option is not working even I am running Zsh 5.4.  The second option works as expected.

λ zsh --version
zsh 5.4.2 (x86_64-unknown-cygwin)

λ zplugin ice atload'autoload $PWD/functions/*.*'; zplugin load zimfw/git
Warning: plugin `zimfw/git' already registered, will overwrite-load
(eval):1: no matches found: /home/apatel/.zplugin/plugins/zimfw---git/functions/*.*

λ git_current_branch
zsh: command not found: git_current_branch
