### ISSUE TITLE
completions not working as shown

### ISSUE THREAD

**Issue by thecontinium** [zdharma/zplugin#33]
the example you give for adding completions :   

```
>> zplg ice blockf
>> zplg load zsh-users/zsh-completions
```

Is not working for me
-    when first run it does not report setting up completions  
-    the completions are not setup
-    zplg clist only shows
```
100.0%
zplugin  _local/zplugin
```

I can fill out more details if you need.

**Comment by moonrumble** [comment]
Following is working for me. You probably have to init the completion.

        zplg ice blockf; zpl light zsh-users/zsh-completions

        autoload -Uz compinit && compinit 
        zplugin cdreplay -q # -q is for quiet

**Comment by psprint** [comment]
Can you do:

```
autoload allopt
allopt > options.txt
```

and attach the options.txt file here? It will show what option has your shell. Also what shows `echo $ZSH_VERSION`?

**Comment by thecontinium** [comment]
As requested 

```
echo $ZSH_VERSION
5.4.2
```

[options.txt](https://github.com/zdharma/zplugin/files/1544256/options.txt)

**Comment by psprint** [comment]
I've added a fix for this, could you check? It was `kshglob` option.

**Comment by thecontinium** [comment]
great - fixed!

what is the zplugin _local/zplugin; completions for zplugin ?

**Comment by psprint** [comment]
It's zplugin's completion, done via pseudo-plugin "zplugin", so one can uninstall this completion.

**Comment by untoreh** [comment]
something related to this is that when deferring plugins with turbo mode and you just have a plain `zpl cdreplay -q` at the of your config, it does not take into account late plugins, so maybe cdreplay should wait for all the plugins to load or compdef gradually as soon as they are loaded or in "batches" every x milliseconds

**Comment by psprint** [comment]
Yeah it's unsynchronized, a current solution could be `atload"-zplg-compdef-replay -q"` added to last completion-related plugin, or just to last plugin (they are loaded in order, if the delays are the same).
