### ISSUE TITLE
Ignore insecure directories whilst loading local completions

### ISSUE THREAD

**Issue by thecontinium** [zdharma/zplugin#34]
I used the following to load homebrew completions

``` zsh
zplg creinstall /usr/local/Homebrew/completions/zsh
``` 

with the following output 
``` zsh
Symlinking completion _brew to ${ZPLGM[COMPLETIONS_DIR]}
Forgetting commands completed by `_brew':
Symlinking completion _brew_cask to ${ZPLGM[COMPLETIONS_DIR]}
Forgetting commands completed by `_brew_cask':
Initializing completion (compinit)...
zsh compinit: insecure directories, run compaudit for list.
Ignore insecure directories and continue [y] or abort compinit [n]? y
```

Does it make sense for zplugin to have an option to stop asking this:
```zsh
Ignore insecure directories and continue [y] or abort compinit [n]? y
```

`compaudit`  returns

``` zsh
There are insecure directories:
/Users/continium/.cache/zplugin/plugins/zdharma---zui/demos
/Users/continium/.cache/zplugin
/Users/continium/.cache/zplugin/plugins/zdharma---zui
```

**Comment by thecontinium** [comment]
It would be good if you could load these local completions rather than creinstall on every login. 
I can’t see how you can do this now; perhaps you can ?
Update would have to work if the local file was updated.

**Comment by psprint** [comment]
creinstall is needed only on installation of plugin. It is done automatically then. From that point the directory `~/.zplugin/completions` has symlinks and completions should be seen. Update doesn't trigger creinstall but rarely a new completion file is added during update.

For the main question, `compinit` is run by the user, so option to skip security check can be specified. I need time to think about if anything can be done with `g+w` write permissions used by package managers etc.

**Comment by thecontinium** [comment]
I have this ` zplg creinstall -q /usr/local/Homebrew/completions/zsh`in my startup because I want a 'record' that I have loaded them. I don't want to do this once on the command line because if I was to start from a clean install there would be no 'record' of my setup. Having this there though I assume is an unnecessary overhead ? 

I am not running `compinit`; this command seems to do that ?

Maybe in this particular example the better thing to do is load the completions directly from GitHub;  homebrew/brew/completions/zsh; what is the best way you would recommend for doing this so that it does manage updates ? 

cheers

**Comment by psprint** [comment]
Yes this is overhead. To know that you loaded completion, there's `zplugin clist` subcommand, it lists installed completions.

Without `compinit` the completion subsystem of Zsh is not initialized. README describes how to invoke `compinit` in zshrc: https://github.com/zdharma/zplugin#calling-compinit

As for the best method to provide completions, I would load plugins that contain them, like `zplugin ice blockf; zplugin load zsh-users/zsh-completions`. Hm, indeed for Zplugin, `zsh-users/zsh-completions` is like an empty plugin, loading it doesn't provide anything, if completions are already installed. But it would serve as the 'record' you described.

**Comment by thecontinium** [comment]
Does zplugin call compinit ; it seems to, if so under what circumstances ?

If zplugin does call compinit I would like the location of the file created by compinit to be able to be defined; is this possible ?

With Homebrew/brew in github there are two completion files {_brew,_cask}  under the sub directory completions/zsh. Do I need to use ice  pick, svn in some way to get these added/symlinked appropriately as completions ?

Thanks.

**Comment by psprint** [comment]
No zplugin doesn't call `compinit`. It has a `compinit` subcommand that removes `~/.zcompdump` and does other things. Zplugin's code comment on the own-`compinit` says:

```
# User-exposed `compinit' frontend which first ensures that all
# completions managed by Zplugin are forgotten by Zshell. After
# that it runs normal `compinit', which should more easily detect
# Zplugin's completions.
```

But this is for interactive use **only**, to troubleshot problems with completions.

That said after disabling or enabling a completion (subcommands `cdisable`, `cenable`), Zplugin does run normal `compinit`, so that the disabled/enabled completion disappears/shows-up.

No `pick` isn't needed. Loading this subdirectory with `zplugin light .../completions/zsh` will not install completions – because there is no clone-operation, no directory setup. But you can still install those completions via `zplugin creinstall .../completions/zsh`.

To know what completions are installed and active, use `zplugin clist`.

**Comment by thecontinium** [comment]
I would like the .zcompdump to be created in ~/.cache/zsh instead of $ZDOTDIR; which I sync across machines. 

Can you add an environment variable / option to enable this within zplugin please ?

**Comment by psprint** [comment]
So you call `compinit -d <dir-path>`? When zplugin calls `compinit`, it shoud know `<dir-path>`, so you propose that an environment variable should be added, used by Zplugin?

**Comment by thecontinium** [comment]
Yes. That’s correct. Any manipulation including, deleting, creation of .zcompdump would use the <dir-path> defined as a zplugin environment variable; I guess if it is undefined it would default to $ZDOTDIR. cheers

**Comment by psprint** [comment]
I've added `$ZPLGM[ZCOMPDUMP_PATH]`, you can set it as [described](https://github.com/zdharma/zplugin/#customizing-paths). zplugin now also supports tilde-expansion, so you can use `~` in the path.

**Comment by thecontinium** [comment]
Great! Thanks.
