### ISSUE TITLE
zplg ice silent working under zplg creinstall

### ISSUE THREAD

**Issue by thecontinium** [zdharma/zplugin#35]
Currently output is still seen when using `zplg ice silent ` with `zplg creinstall`

e.g. with homebrew installed 

`zplg ice silent; zplg creinstall /usr/local/Homebrew/completions/zsh
`

does **not** suppress output and results in : 

```zsh
Symlinking completion _brew to ${ZPLGM[COMPLETIONS_DIR]}
Forgetting commands completed by `_brew':
Symlinking completion _brew_cask to ${ZPLGM[COMPLETIONS_DIR]}
Forgetting commands completed by `_brew_cask':
Initializing completion (compinit)...
```

Should `ice silent` work with all the commands ?

**Comment by psprint** [comment]
Ice mods are for: `light/load`, `snippet`, `update`. Update in general doesn't need them because it uses saved ice mods from memory or disk. I've added `-q` option for `creinstall`, it should be fine?

**Comment by thecontinium** [comment]
Cool. Thanks.

**Comment by psprint** [comment]
PS. Do you think it would be useful to respect `silent` when `light/load` or `snippet` of package that does installation of completions?

**Comment by thecontinium** [comment]
Yes - I think that would make sense.

**Comment by psprint** [comment]
Thanks, I'll add that.
