### ISSUE TITLE
RPROMPT broken

### ISSUE THREAD

**Issue by agkozak** [zdharma/zplugin#36]
My theme (https://github.com/agkozak/agkozak-zsh-theme) shows the exit code in the right prompt when it is other than zero:
```
RPS1="%(?..(%?%))"
```
This worked perfectly with `zplugin` until [commit 0c0f0f85f506b938f0187e33ed5e26b9c8f759f0](https://github.com/zdharma/zplugin/commit/0c0f0f85f506b938f0187e33ed5e26b9c8f759f0). Now the right prompt only appears occasionally. Any ideas? Thanks!

**Comment by agkozak** [comment]
Before this commit, the right prompt worked reliably:
![before](https://user-images.githubusercontent.com/7599319/34284782-6ad44400-e689-11e7-9a5c-0c23c5638233.png)

Now I only see the right prompt occasionally:
![after](https://user-images.githubusercontent.com/7599319/34284805-93897960-e689-11e7-9b06-e6449c85e2aa.png)

It does not matter whether I have loaded my prompt as a plugin or sourced it directly; just having `zplugin` running makes the right prompt unreliable.

**Comment by agkozak** [comment]
Using an older version of `zsh` makes the problem go away.

**Comment by psprint** [comment]
Could you check if it's fixed? Turns out that `sched` tasks should save and restore `$?` value.

**Comment by agkozak** [comment]
You fixed it! Many thanks!

**Comment by psprint** [comment]
Thanks for reporting this, it could be hidden for long period of time.
