### ISSUE TITLE
manually sourcing zshrc throws a warning: function already exists

### ISSUE THREAD

**Issue by rage28** [zdharma/zplugin#39]
I followed the manual installation [steps](https://github.com/zdharma/zplugin#manual-installation) and placed the line which sources zplugin above compinit. On iTerm2 when I open a new window or tab there is no issue but whenever I manually source my zshrc I get the following message

```zsh
/Users/rage28/.zplugin/bin/zplugin.zsh:functions:1626: -M zplugin_scheduler_add: function already exists
```

**Environment**
macOS: 10.2
zsh: 5.4.2
iTerm2: 3.1.5.beta.2

**Comment by psprint** [comment]
Yes zplugin doesn't call compinit and user controls this function, glad you have this in zshrc. For the message, I've muted it, it should be ok after `zplg self-update`.

**Comment by rage28** [comment]
Yup... The message is gone. Closing the issue
