### ISSUE TITLE
How does recall works

### ISSUE THREAD

**Issue by moonrumble** [zdharma/zplugin#42]
Can you provide some examples? will recall load plugin in light mode or load mode. 

I have few plugins which I load with wait 1 second and silent. I believe with recall I dont need to specify the ice multiple times.

**Comment by psprint** [comment]
Recall is for command line. Ice modifiers are saved to disk and to memory (the second occurs when plugin is loaded earlier), one can bring them from that storage, instead of e.g. copying from `.zshrc`.

```zsh
% zplg recall zsh-users/zsh
% zplugin ice pick"src/zsh" as"command" atclone"=./.preconfig; ./configure" make; zplugin
```

The second line basically appears at command line.

**Comment by psprint** [comment]
I can add new command, maybe "zplugin ice-restore", to activate ice-mods of previous command for current command. However I would have to update `zplugin-crasis`, but this seems doable. I just want to ask if you tried `crasis` and if not then why? I'm using it actively and perceive it well but it doesn't have much user attention, maybe you know why?

**Comment by moonrumble** [comment]
@psprint Thanks. I haven't use `zplugin-crasis`. I will give it a shot. 

I just wanted to make my `.zpshrc` simple. I have few plugins which I am loading with `silent wait 1`

It will be nice if I can do,

`zpl ice --starts silent wait'1';
zpl load 1;
zpl load 2;
zpl load 3;
zpl ice --ends`;
