### ISSUE TITLE
Calling compinit once clarification

### ISSUE THREAD

**Issue by ctzen** [zdharma/zplugin#44]
Hi, new zsh user here. In your readme [Calling compinit](https://github.com/zdharma/zplugin#calling-compinit), you said to source zplugin.zsh, follow by zplugin loads, finally compinit.

May I know where should I put these:

`autoload -Uz _zplugin`
`(( ${+_comps} )) && _comps[zplugin]=_zplugin`

Thanks.

**Comment by psprint** [comment]
You can drop those lines, installer adds them so that zplugin completion has greater chances of working in a situation where compinit is called earlier, before appended zplugin block. This happens when user didn't yet organized his zshrc.
