### ISSUE TITLE
track repos without cloning

### ISSUE THREAD

**Issue by untoreh** [zdharma/zplugin#47]
For software which doesn't provide github release, in general you want to track the latest tag from the repo, and download the binaries from a template url like `projectsite.com/download/$VER-project.tar.gz` this is in general useful with software that is too big to compile everytime. So something like `as'track'` could be useful.

**Comment by psprint** [comment]
It might be doable, the url template should be possible to `grep -o` from web page after downloading it. I can approach this today and in following days, but could a `$10` donation be granted for this? It's little demanding project, it will significantly extend Zplugin.

**Comment by psprint** [comment]
Hi!
I've created an annex that implements the idea: [zplugin/z-a-as-track](https://github.com/zplugin/z-a-as-track). Thanks!
