### ISSUE TITLE
Feature request: Clean output for wait"0" installed plugins

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#51]
For example:

```
robo@9bff2679b2b8 ~> Setting up snippet           command-not-found/command-not-found.plugin.zsh
Downloading `command-not-found/command-not-found.plugin.zsh' (with wget, curl, lftp)...
Downloading robobenklein/k...
Cloning into '/home/robo/.zplugin/plugins/robobenklein---k'...
remote: Counting objects: 730, done.
remote: Total 730 (delta 0), reused 0 (delta 0), pack-reused 730
Receiving objects: 100% (730/730), 7.35 MiB | 8.49 MiB/s, done.
Resolving deltas: 100% (295/295), done.
Checking connectivity... done.
Compiling k.plugin.zsh...
Downloading zdharma/fast-syntax-highlighting...
Cloning into '/home/robo/.zplugin/plugins/zdharma---fast-syntax-highlighting'...
remote: Counting objects: 1303, done.
remote: Compressing objects: 100% (63/63), done.
remote: Total 1303 (delta 53), reused 66 (delta 29), pack-reused 1211
Receiving objects: 100% (1303/1303), 513.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (821/821), done.
Checking connectivity... done.
Symlinking completion _fast-theme to ${ZPLGM[COMPLETIONS_DIR]}
Compiling fast-syntax-highlighting.plugin.zsh...

robo@9bff2679b2b8 ~>            
```

Upon opening the new prompt, I am greeted with an install process cluttering the screen, even though the terminal is technically ready. I have to press enter again after the install to get a new prompt.

Perhaps this install log could be moved below the prompt? Or the prompt could be redrawn out of the way when there is new stdoutput from the install process?

**Comment by psprint** [comment]
Yes this is a somewhat weak spot, git output isn't controlled and printing is from background process that doesn't cooperate with prompt. I have a bit of time very now, I'll try to at least control git output, turn it into progress bar, etc. So, getting to work. I also think about suggestions to reset the prompt.

**Comment by robobenklein** [comment]
I'd personally think that either of these two seemingly easier solutions would fit my use case:

A preinstall command, or scanning of `wait'0'` plugins into the install step.

Since the install process is often only run once, perhaps there could be a `zplugin install-all` command that will install all the bundles ahead of time, instead of needing to wait for an interactive session. (E.x. something that could be run from a dotfiles install script.)

Or a list of enabled (and to-be-enabled / `wait` plugins) could be built, and they all should be installed before the prompt shows. (But still loaded/sourced after the wait.)

**Comment by psprint** [comment]
I will think about this. Right now I've pushed git-output decimation (into single line), it helps on eyes when the installations pop-up from background.

**Comment by psprint** [comment]
PS. Had to revert the decimation, build fails, I will track this tomorrow.

**Comment by robobenklein** [comment]
![image](https://user-images.githubusercontent.com/5423266/41922159-78572d72-7932-11e8-83ca-1dba445028ca.png)

(current master commit)

Maybe `lucid` should also hide the download/install output of `wait'0'` plugins?

**Comment by psprint** [comment]
That is unexpected, for me the shortened output of Git is:

![gitdecimate](https://user-images.githubusercontent.com/6049288/41923038-c50d7bba-7966-11e8-8fe0-6c7f43402a0e.png)

Wonder why it behaves differently at your machine.

For silencing, ice-mod `silent` does silence installation messages, although it isn't nice, because command line is blocked without showing the reason why it is.

**Comment by robobenklein** [comment]
Reproducible with docker:

```
docker pull robobenklein/home:zplugin
docker run --rm -t -i robobenklein/home:zplugin zsh -l
# (installs wait'0' plugins now)
```

I would like for these to be installed before the container starts, i.e. during the build step would be ideal.

**Comment by psprint** [comment]
zplg-install command, ran without loading of Zplugin, in build step, that's a very interesting idea, thanks, I will approach this.

The docker image seems to have non-HEAD version which doesn't decimate git output with script `git-process-output.zsh`:

![docker-zplg-version](https://user-images.githubusercontent.com/6049288/41929202-a26cec7e-7977-11e8-97b4-b85aa423f9ed.png)

**Comment by robobenklein** [comment]
My bad - forgot to `docker push`. It's updated now.

**Comment by psprint** [comment]
Thanks, I've found the bug, there was no `setopt extendedglob`. Fix is pushed.

**Comment by robobenklein** [comment]
Already looks much better after that. I suppose snippets are still WIP as well?

![image](https://user-images.githubusercontent.com/5423266/42057679-20205c30-7aec-11e8-8492-031732851f06.png)

Do you think it could also `>/dev/null` the output from submodules being cloned as well?

```
Downloading zdharma/zsh-diff-so-fancy...

Cloning into '/home/robo/.zplugin/plugins/zdharma---zsh-diff-so-fancy'...
OBJ: 26, PACKED: 26/26             
Cloning into '/home/robo/.zplugin/plugins/zdharma---zsh-diff-so-fancy/diff-so-fancy'...
OBJ: 1590, PACKED: 26/26, RECEIVING: 94%          Submodule path 'diff-so-fancy': checked out '0d2492c0cc81c11588040982f9544b6be8541bcb'
OBJ: 1590, PACKED: 1589/1590, RECEIVING: 100%, RESOLVING: 100%          
Cloning into '/home/robo/.zplugin/plugins/zdharma---zsh-diff-so-fancy/diff-so-fancy/test/test_helper/bats-assert'...
OBJ: 116, PACKED: 1589/1590, RECEIVING: 42%, RESOLVING: 100%          Submodule path 'diff-so-fancy/test/test_helper/bats-assert': checked out '3c30cb6424b9760884f8f8b7378a9367b76692b7'
Submodule path 'diff-so-fancy/test/test_helper/bats-support': checked out '88f342e29681cbcb3c183bd47dfbb45965f42eb7'
OBJ: 116, PACKED: 115/116, RECEIVING: 100%, RESOLVING: 100%           
Cloning into '/home/robo/.zplugin/plugins/zdharma---zsh-diff-so-fancy/diff-so-fancy/test/test_helper/bats-support'...
OBJ: 88, PACKED: 88/88, RECEIVING: 100%, RESOLVING: 100%             
Compiling git-dsf...
-zplg-compile-plugin:zcompile:30: can't open file: git-dsf
Compilation failed. Don't worry, the plugin will work also without compilation
Consider submitting an error report to Zplugin or to the plugin's author

```

https://asciinema.org/a/33zx2LDnANaAHDx0lsuHvodbN

**Comment by robobenklein** [comment]
I got the preinstall working by a quick hack - just sleeping for a bit then manually running the interactive scheduler after that time.

`zsh -i -c 'sleep 2; -zplg-scheduler following'`

So now I have that workaround for the docker and new machine provisioning.

**Comment by psprint** [comment]
Interesting, I now see more what you request. The `sleep` is apparently to move `EPOCHSECONDS` onward. This can be done without a delay via:

```zsh
zsh -i -c '() { local -h EPOCHSECONDS=$(( EPOCHSECONDS+10 )); -zplg-scheduler following; }'
```

**Comment by psprint** [comment]
Basing on your workaround I've extended scheduler. If it will be called with "burst" as argument, it will push `EPOCHSECONDS` forward and run all tasks without count limit (normally it runs at most 20 tasks in single time slot). So:

```zsh
zsh -i -c -- '-zplg-scheduler burst'
```

**Comment by robobenklein** [comment]
Sweet! Works as intended.

**Comment by psprint** [comment]
An update on the git-output processing – the output is now redirected in a better way, and it cannot happen that some other message will appear on the same line as the short progress "OBJ: ...", what did often occur and is visible even on the last screenshot here.

**Comment by psprint** [comment]
Just to let know users that felt that something is wrong – the "OBJ: ... PACKED: ... ..." progress indicator was suffering from `tr` buffering whole output, throwing out all text at once. So the progress indicator was inactive to then quickly go through all phases just at the end. This is fixed (by using `perl` and as a fallback special `coreutils` command `gstdbuf`), the progress indicator is finally alive, responsive.
