### ISSUE TITLE
Question: How to prevent automatic search for completions?

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#52]
Taking this example from my zshrc:

```zsh
  # OMZ libraries
  local _ZSHRC_OMZ_LIBS=(
    compfix.zsh
    completion.zsh
    directories.zsh
    functions.zsh
    git.zsh
    grep.zsh
    history.zsh
    key-bindings.zsh
    misc.zsh
    spectrum.zsh
    termsupport.zsh
    theme-and-appearance.zsh
  )

  zplugin ice from"gh" pick"plugins/git/git.plugin.zsh" atload'local f; for f in ${_ZSHRC_OMZ_LIBS}; do source lib/$f; done'
  zplugin light robbyrussell/oh-my-zsh
```

It seems that the `_git` completion gets loaded from `plugins/gitfast/_git`. How can I prevent completions being autoloaded by search? (Hopefully there's a method without using SVN clones...)

There are a lot of completions that get loaded from plugins like these that I never actually use or even want loaded, here's what my `clist` looks like for OMZ:

```
adb, artisan, asadmin                      robbyrussell/oh-my-zsh
autopep8, boot2docker, bower               robbyrussell/oh-my-zsh
bundler, capistrano, cargo                 robbyrussell/oh-my-zsh
celery, codeclimate, coffee                robbyrussell/oh-my-zsh
cpanm, docker, docker-compose              robbyrussell/oh-my-zsh
extract, fab, gas                          robbyrussell/oh-my-zsh
gb, geeknote, gem                          robbyrussell/oh-my-zsh
git                                        robbyrussell/oh-my-zsh [disabled]
gradle, gradlew, heroku                    robbyrussell/oh-my-zsh
hub, jira, kitchen                         robbyrussell/oh-my-zsh
knife, lein, meteor                        robbyrussell/oh-my-zsh
mix, nanoc, n-kill                         robbyrussell/oh-my-zsh
nomad, nvm, pass                           robbyrussell/oh-my-zsh
pep8, pip, pod                             robbyrussell/oh-my-zsh
port, powder, powify                       robbyrussell/oh-my-zsh
pylint, rails, react-native                robbyrussell/oh-my-zsh
rebar, redis-cli, repo                     robbyrussell/oh-my-zsh
rust, sbt, scala                           robbyrussell/oh-my-zsh
scw, spring, supervisorctl                 robbyrussell/oh-my-zsh
supervisord, task, terminitor              robbyrussell/oh-my-zsh
terraform, theme, thor                     robbyrussell/oh-my-zsh
tmux-cssh, tmuxinator, tugboat             robbyrussell/oh-my-zsh
vagrant, vault, wake                       robbyrussell/oh-my-zsh
xcselv, zeus                               robbyrussell/oh-my-zsh
```

I would like to use an SVN clone to get just `lib/`, but I don't have SVN available on all the systems I use.

**Comment by robobenklein** [comment]
Right now I just have to either manually disable them, or what I've resorted to is just `rm -rf ~/.zplugin/completions/_*` after loading the plugin. (Which works exactly as intended, clears the completions from any previous plugin loads, but breaks zplugins'.)

This is what I expected `zplugin cdclear` to do, but now I realize it only actually cleared the replay values.

Is there some other function I can use to actually disable or remove completions from previously loaded plugins? `zplg cclear` only removes based on symlinks, which to me seems like it should be `zplg clean` instead of clear, which I expected to *clear* all completions.

The best solution here just seems to be to add an `ice nocompletions` which will prevent any loading or linking of completions from the plugin.

**Comment by psprint** [comment]
I've added the `nocompletions` [ice-mod](https://github.com/zdharma/zplugin#ice-modifiers). To remove completions of a plugin (but not in a way of "previously loaded plugins"), there's `cuninstall` subcommand. Opposite to `creinstall`.

**Comment by robobenklein** [comment]
Works exactly as desired! Thanks!
