### ISSUE TITLE
Handle OMZ Libs/Plugins that rely on direct path

### ISSUE THREAD

**Issue by SeanOBoyle** [zdharma/zplugin#54]
Some OMZ libs / plugins have stuff like this:
from osx plugin:
source ${ZSH}/plugins/osx/spotify

What is the correct way to load the osx plugin?
I've tried both:
  zplugin ice wait"0"
  zplugin snippet OMZ::plugins/osx/osx.plugin.zsh

and:
  zplugin ice svn wait"0"
  zplugin snippet OMZ::plugins/osx

Similar question for the git fast plugin which has a line:
source $dir/../git/git.plugin.zsh

**Comment by robobenklein** [comment]
This kind of problem was what I was having some trouble with earlier, but some recent changes have made this easier. (Thanks psprint!)

Here's how I currently load OMZ libraries in my shell:

```
  # OMZ libraries
  local _ZSHRC_OMZ_LIBS=(
    compfix.zsh
    completion.zsh
    directories.zsh
    functions.zsh
    grep.zsh
    history.zsh
    key-bindings.zsh
    misc.zsh
    spectrum.zsh
    termsupport.zsh
    theme-and-appearance.zsh
  )

  zplugin ice from"gh" pick"lib/git.zsh" nocompletions blockf \
    atload'!local f; for f in ${_ZSHRC_OMZ_LIBS}; do source lib/$f; done' \
    compile"lib/(${(j.|.)_ZSHRC_OMZ_LIBS})"
  zplugin load robbyrussell/oh-my-zsh
```

We can easily change how this works to fit your use case:

```
  # I can't remember the ZPLG home variable - change this to your install location
  ZSH="$HOME/.zplugin/plugins/robbyrussell---oh-my-zsh/"

  # OMZ things to source
  local _ZSHRC_OMZ_SOURCES=(
    lib/compfix.zsh
    lib/completion.zsh
    lib/directories.zsh
    lib/functions.zsh
    lib/grep.zsh
    lib/history.zsh
    lib/key-bindings.zsh
    lib/misc.zsh
    lib/spectrum.zsh
    lib/termsupport.zsh
    lib/theme-and-appearance.zsh

    plugins/osx/osx.plugin.zsh
    plugins/git-fast/git-fast.plugin.zsh
  )

  zplugin ice from"gh" pick"lib/git.zsh" nocompletions blockf \
    atload'!local f; for f in ${_ZSHRC_OMZ_SOURCES}; do source $f; done' \
    compile"(${(j.|.)_ZSHRC_OMZ_SOURCES})"
  zplugin load robbyrussell/oh-my-zsh
```

(Not 100% sure the compile selection line helps here - @psprint can correct me on that one.)

But that's the gist of the solution, might need some tweaks.

The `!` in `atload` makes sure that that source step gets tracked as part of the plugin.

**Comment by psprint** [comment]
Compile selection via pattern should work OK.

**Comment by psprint** [comment]
@SeanOBoyle I would try to provide the `$ZSH` and `$dir` variables. Surprisingly, I get segmentation faults for `osx` plugin, while `gitfast` has also this line:

```zsh
dir=$(dirname $0)
```

So `gitfast` works OK out of the box. I cannot load `osx` (Zsh segfaults) and verify, however following should work:

```zsh
zplugin ice svn wait"0" lucid atinit"local ZSH=\$PWD"; zplugin snippet OMZ::plugins/osx
```

**Comment by SeanOBoyle** [comment]
In case not obvious -- workaround is changing to:
zplugin ice svn wait"0" lucid ; zplugin snippet OMZ::plugins/git
zplugin ice svn wait"0" lucid ; zplugin snippet OMZ::plugins/gitfast

**Comment by SeanOBoyle** [comment]
I fixed osx by doing this:
zplugin ice svn wait"0" lucid atinit"local ZSH=\$PWD; mkdir -p plugins; cd plugins; ln -sfn ../. osx"; zplugin snippet OMZ::plugins/osx

**Comment by psprint** [comment]
The part of code you added `mkdir -p ...` can be put into `atclone''` so that it isn't ran each time the plugin is loaded, but instead each time the plugin is cloned:

```zsh
zplugin ice svn wait"0" lucid atinit"local ZSH=\$PWD" \
    atclone"mkdir -p plugins; cd plugins; ln -sfn ../. osx"
zplugin snippet OMZ::plugins/osx
```
