### ISSUE TITLE
Loading error on slightly older ZSH

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#58]
Zsh pre 5.1 here...

```
# Colorize completions for commands unload, report, creinstall, cuninstall
zstyle ':completion:*:zplugin:argument-rest:plugins' list-colors '=(#b)(*)/(*)==1;35=1;33'
+/home/bklein3/.zplugin/bin/zplugin.zsh:1748> zstyle ':completion:*:zplugin:argument-rest:plugins' list-colors '=(#b)(*)/(*)==1;35=1;33'
zstyle ':completion:*:zplugin:argument-rest:plugins' matcher 'r:|=** l:|=*'
+/home/bklein3/.zplugin/bin/zplugin.zsh:1749> zstyle ':completion:*:zplugin:argument-rest:plugins' matcher 'r:|=** l:|=*'
# }}}
/home/bklein3/.zshrc:166: unknown file attribute
```

```
zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)
```

**Comment by robobenklein** [comment]
I should be able to get a reproduction docker container for this bug at some point. Right now it's just annoying because my school won't upgrade their Linux systems currently.

**Comment by psprint** [comment]
The `unknown file attribute` error is an enigmatic message that means someone did `local -a array=( ... )`, i.e. used `local -a` and assignment `=( .. )` in the same line. This was added fairly recently, older Zsh don't support this. The error seems to be located in zshrc?

**Comment by robobenklein** [comment]
Indeed, that was the issue. Sorry about the report I thought it was zplugin related because it was from an `atload""` call.

**Comment by psprint** [comment]
No problem, I've spend some time tracking that error and I think it was twice, after that I finally remembered what this error message means.
