### ISSUE TITLE
Prompt not displayed after plugin install

### ISSUE THREAD

**Issue by HaleTom** [zdharma/zplugin#60]
**Describe the bug**
The shell prompt not displayed after plugin install

**To Reproduce**
Use the following `.zshrc`:
```
alias -g C='| wc -l'
source "$XDG_DATA_HOME/zplugin/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin
zplugin ice wait'0' pick'zsh-vim-mode.plugin.zsh'
zplugin light softmoth/zsh-vim-mode
```
1. Start a new shell

**Expected behavior**
I see the shell prompt appear

**Screenshots**
On loading a new shell, I see:
![screenshot](https://i.imgur.com/h8NM6rn.png)

Note the cursor is after a blank space equal to the space of `svelte% ` above.

**Versions:**
 - $ZSH_VERSION == 5.5.1
 - Operating system name and version (uname -a): 
```
Linux svelte 4.16.18-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:27:59 UTC 2018 x86_64 GNU/Linux
```

**Comment by psprint** [comment]
I've added code that resolves this, it should now be OK
