### ISSUE TITLE
$PATH is different inside tmux than outside

### ISSUE THREAD

**Issue by ahmedelgabri** [zdharma/zplugin#65]
Here is my `$PATH` outside of tmux:

```zsh
~  
৸ echo $PATH | tr -s ":" "\n"       
/Users/ahmed/.zplugin/plugins/ap---rename
/Users/ahmed/.zplugin/plugins/sharkdp---bat
/Users/ahmed/.zplugin/plugins/ogham---exa
/Users/ahmed/.zplugin/plugins/stedolan---jq
/Users/ahmed/.zplugin/plugins/sharkdp---fd
/Users/ahmed/.zplugin/plugins/zdharma---zsh-diff-so-fancy/bin
/Users/ahmed/.zplugin/polaris/bin
/Users/ahmed/.zplugin/plugins/junegunn---fzf/bin
/Users/ahmed/.zplugin/plugins/direnv---direnv
/Users/ahmed/.zplugin/plugins/elasticdog---transcrypt
/Users/ahmed/.dotfiles/bin
./node_modules/.bin
/usr/local/opt/python/libexec/bin
/usr/local/bin
/usr/local/sbin
/usr/local/opt/coreutils/libexec/gnubin
/Users/ahmed/.config/yarn/global/node_modules/.bin
/Users/ahmed/.cargo/bin
/Users/ahmed/Library/Python/3.6/bin
/Users/ahmed/Library/Python/2.7/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Applications/kitty.app/Contents/MacOS
```

And here is inside a tmux session

```zsh
~
→ echo $PATH | tr -s ":" "\n"
/Users/ahmed/.dotfiles/bin
./node_modules/.bin
/usr/local/opt/python/libexec/bin
/usr/local/bin
/usr/local/sbin
/usr/local/opt/coreutils/libexec/gnubin
/Users/ahmed/.config/yarn/global/node_modules/.bin
/Users/ahmed/.cargo/bin
/Users/ahmed/Library/Python/3.6/bin
/Users/ahmed/Library/Python/2.7/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Users/ahmed/.zplugin/plugins/ap---rename
/Users/ahmed/.zplugin/plugins/sharkdp---bat
/Users/ahmed/.zplugin/plugins/ogham---exa
/Users/ahmed/.zplugin/plugins/stedolan---jq
/Users/ahmed/.zplugin/plugins/sharkdp---fd
/Users/ahmed/.zplugin/plugins/zdharma---zsh-diff-so-fancy/bin
/Users/ahmed/.zplugin/polaris/bin
/Users/ahmed/.zplugin/plugins/junegunn---fzf/bin
/Users/ahmed/.zplugin/plugins/direnv---direnv
/Users/ahmed/.zplugin/plugins/elasticdog---transcrypt
/Applications/kitty.app/Contents/MacOS
```

Any idea what is wrong? my `$PATH` is set up in my [`.zprofile`](https://github.com/ahmedelgabri/dotfiles/blob/4933fb208ff17c29f3bee5ea67b92d7a22b83fdc/zsh/.zprofile#L41-L57) which gets sourced _once_ inside [`.zshenv`](https://github.com/ahmedelgabri/dotfiles/blob/4933fb208ff17c29f3bee5ea67b92d7a22b83fdc/zsh/.zshenv#L7-L11)

**Comment by psprint** [comment]
Maybe you set up path in `.zprofile` in such a way, that it removes current entry and adds it to front of `$PATH`? Zplugin doesn't do that, it only checks if given path exists in `$PATH`, if not then prepends it. So in tmux, when the previous exported `$PATH` is occurred, first by `.zprofile`, which changes order, then by `zplugin`, which doesn't change order, then Zplugin's paths end up at the end of `$PATH`.

I suspect this is in `.zprofile`:

```zsh
typeset -U path PATH
path=( /sbin $path )
path=( /usr/sbin $path )
...
```
This will move `/sbin` and `/usr/sbin` to front of `$path`:

```zsh
typeset -U path
path=( /my1 /my2 /sbin /usr/sbin )
path=( /sbin $path )
path=( /usr/sbin $path )
print -rl $path
```

output is:

```
/usr/sbin
/sbin
/my1
/my2
```

**Comment by ahmedelgabri** [comment]
Here is how I'm setting my `$PATH` inside `.zprofile`, I don't think there is anything fancy going there? I don't change this anywhere else in my config. So I don't really know where to look.

https://github.com/ahmedelgabri/dotfiles/blob/4933fb208ff17c29f3bee5ea67b92d7a22b83fdc/zsh/.zprofile#L41-L57

I tried disabling zplugin & `$PATH` is consistent inside & outside `tmux`

**Comment by psprint** [comment]
It looks like the `$path` is set up in one more place. The highlighted lines in `.zprofile` you provided end on:

```zsh
  ...
  ${HOME}/Library/Python/3.*/bin(Nn[-1]-/)
  ${HOME}/Library/Python/2.*/bin(Nn[-1]-/)
```

while the `$PATH`-dumps you provided in first post contain:

```zsh
...
/Users/ahmed/Library/Python/3.6/bin
/Users/ahmed/Library/Python/2.7/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Users/ahmed/.zplugin/plugins/ap---rename
...
```

so there's a question from where do `/usr/bin`, `/bin`, etc. come from?

**Comment by ahmedelgabri** [comment]
On mac, I think this comes from `path_helper` in `/etc/zprofile` 

```zsh
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

**Comment by psprint** [comment]
Thanks. I googled and `path_helper` has a known problem of reordering PATH. Maybe you could run a non-login zsh in tmux, i.e. without option `-l`? This would avoid executing `/etc/zprofile`.

**Comment by ahmedelgabri** [comment]
I'll look into this then, I know that `path_helper` is a nightmare already. Thanks

**Comment by ahmedelgabri** [comment]
Ok, I tried this `setopt no_global_rcs` which will not load system zsh files inside `/etc/z*` but the `$PATH` is still not the same

outside tmux 

```zsh
/Users/ahmed/.zplugin/plugins/ap---rename
/Users/ahmed/.zplugin/plugins/sharkdp---bat
/Users/ahmed/.zplugin/plugins/ogham---exa
/Users/ahmed/.zplugin/plugins/stedolan---jq
/Users/ahmed/.zplugin/plugins/sharkdp---fd
/Users/ahmed/.zplugin/plugins/zdharma---zsh-diff-so-fancy/bin
/Users/ahmed/.zplugin/polaris/bin
/Users/ahmed/.zplugin/plugins/junegunn---fzf/bin
/Users/ahmed/.zplugin/plugins/direnv---direnv
/Users/ahmed/.zplugin/plugins/elasticdog---transcrypt
/Users/ahmed/.dotfiles/bin
./node_modules/.bin
/usr/local/opt/python/libexec/bin
/usr/local/bin
/usr/local/sbin
/usr/local/opt/coreutils/libexec/gnubin
/Users/ahmed/.config/yarn/global/node_modules/.bin
/Users/ahmed/.cargo/bin
/Users/ahmed/Library/Python/3.7/bin
/Users/ahmed/Library/Python/2.7/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/kitty.app/Contents/MacOS
```

inside `tmux`
```zsh
/Users/ahmed/.dotfiles/bin
./node_modules/.bin
/usr/local/opt/python/libexec/bin
/usr/local/bin
/usr/local/sbin
/usr/local/opt/coreutils/libexec/gnubin
/Users/ahmed/.config/yarn/global/node_modules/.bin
/Users/ahmed/.cargo/bin
/Users/ahmed/Library/Python/3.7/bin
/Users/ahmed/Library/Python/2.7/bin
/Users/ahmed/.zplugin/plugins/ap---rename
/Users/ahmed/.zplugin/plugins/sharkdp---bat
/Users/ahmed/.zplugin/plugins/ogham---exa
/Users/ahmed/.zplugin/plugins/stedolan---jq
/Users/ahmed/.zplugin/plugins/sharkdp---fd
/Users/ahmed/.zplugin/plugins/zdharma---zsh-diff-so-fancy/bin
/Users/ahmed/.zplugin/polaris/bin
/Users/ahmed/.zplugin/plugins/junegunn---fzf/bin
/Users/ahmed/.zplugin/plugins/direnv---direnv
/Users/ahmed/.zplugin/plugins/elasticdog---transcrypt
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/kitty.app/Contents/MacOS
```

**Comment by ahmedelgabri** [comment]
I also mentioned that I source `.zprofile` inside `.zshenv` once here https://github.com/ahmedelgabri/dotfiles/blob/4933fb208ff17c29f3bee5ea67b92d7a22b83fdc/zsh/.zshenv#L7-L11

so it's like this

```
.zshenv -> if it's the first time to load & we are not in interactive shell then source .zprofile ($PATH is set)
.zprofile -> ($PATH is set for interactive shell)
```

**Comment by psprint** [comment]
My first answer applies here. .Zprofile exports PATH so in general .zprofile should be ran once at login. Second loading of .zprofile will reorder PATH like I described in first answer.

**Comment by psprint** [comment]
If it is sourced for non-login shell then it is always sourced.

**Comment by ahmedelgabri** [comment]
Ok so here is what I tried so far (for all of these I disabled loading of system zsh files in `/etc/*` using `setopt no_global_rcs`)

- Removed the sourcing of `.zprofile` from `.zshenv`
- Removed `.zprofile` & moved everything to `.zshenv`
- Removed `.zprofile` & moved everything to `.zshrc`

All of them had the same result, `$PATH` is still different inside & outside of `$TMUX` so I still think it might be an issue with `zplugin`...

**Comment by ahmedelgabri** [comment]
I made some changes, tests & here is the result:

1. I added this condition to my `.zshenv` file to not load `/etc/*` files inside `tmux` again

```zsh
if [[ ! -z "$TMUX" && "$SHLVL" -gt 1 ]]; then
  setopt NO_GLOBAL_RCS
fi
```

2. added this extra line to my `.zprofile` 

```zsh
path=(${^path}(N-/))
```

3. also added `set -x` at the top of `.zshenv` to see how things evolve & here is the result (left normal zsh, right is tmux session) **This is tested with zplugin disabled because zplugin log was too much for any terminal to handle**

<img width="1675" alt="screen shot 2018-07-29 at 21 04 47" src="https://user-images.githubusercontent.com/63876/43369754-8bfab78a-9373-11e8-8313-916f9bfb0467.png">

as you can see that the `$PATH` is set properly & clean after `~/.zprofile` is loaded fully loaded so this means that when `zplugin` changes the `$PATH` that's when things change, but as I said I couldn't check the `zplugin` log because it was too much. But I hope this can give you some insights & maybe guide you to see if it's a `zplugin` issue or give me advice how to solve this...
