### ISSUE TITLE
Completion for `zplg cd` shows non-directories

### ISSUE THREAD

**Issue by HaleTom** [zdharma/zplugin#70]
**Describe the bug**
Completion for `zplg cd` shows non-directories

**To Reproduce**
If I type `zplg cd` and hit <tab> I see completions which aren't valid.

**Expected behavior**
I only see directories

**Screenshots**
![screenie](https://i.imgur.com/kLoZai4.png)

**Versions:**
 - $ZSH_VERSION == `5.5.1`
 - Operating system name and version (uname -a): `Linux svelte 4.16.18-1-MANJARO #1 SMP PREEMPT Tue Jun 26 15:27:59 UTC 2018 x86_64 GNU/Linux`

**Comment by psprint** [comment]
Should be done, I will close in 1 day.

**Comment by HaleTom** [comment]
Thanks! Works a treat!
