### ISSUE TITLE
Comparison with zplug?

### ISSUE THREAD

**Issue by raxod502** [zdharma/zplugin#71]
I currently use [zplug](https://github.com/zplug/zplug) to manage my Zsh plugins. I am interested in potentially switching to zplugin; however, it's not clear to me whether it would be an improvement or not. Would you consider documenting the advantages of zplugin over the (currently more popular) zplug project?

**Comment by psprint** [comment]
Users reported "10x" faster shell startup. My shell starts in 120 ms for 21 plugins, using turbo mode. But you gave me a task to do a comparison and I intend to do it, maybe today if not then within week.

**Comment by raxod502** [comment]
Can confirm, shell startup immediately became much faster. One must wonder what exactly zplug was doing with all the time.

**Comment by maturanomx** [comment]
So, you switched @raxod502 ? I'm in the same situation. zplugin appears more verbose and confuse to configure, but is there is a difference in the speed, could be worth it.

**Comment by raxod502** [comment]
@maturanomx The code looks more complex after I switched, but I'm not convinced that it actually is. My intuitive thought is that zplugin has sounder design decisions than zplug. I suspect that if I knew more about Zsh plugins, I would be able to make a better judgement here.

But it only took an hour or two to switch, and the startup improvement was absolutely massive.

```shell
# with zplug

. ~/.zplugin/init.zsh

zplug raxod502/wdx
zplug zsh-users/zsh-autosuggestions
zplug zsh-users/zsh-completions

if ! zplug check; then
    zplug install
fi

zplug load

# with zplugin

. ~/.zplugin/bin/zplugin.zsh
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

ZPLGM[MUTE_WARNINGS]=1

zplugin light raxod502/wdx
zplugin light zsh-users/zsh-autosuggestions

zplugin ice blockf
zplugin light zsh-users/zsh-completions

autoload -Uz compinit
compinit
```

**Comment by maturanomx** [comment]
Say no more!, I will try it. Thanks for your time :smiley:

**Comment by robobenklein** [comment]
I would be glad to contribute to a "User Stories" wiki page with some personal examples.

I used to use antigen, so I maintained two branches on a git repo, and I have switched almost all machines to zplugin because of speed and how I started doing things which weren't even possible on antigen. (Like binary providing plugins)

**Comment by moonrumble** [comment]
I was also zplug user earlier. Zplugin is definately faster with turbo mode but witout turbomode it should be the same. zplug had [issue](https://github.com/zplug/zplug/issues/404) where it re-created all the simlink and made it slow. 

I have switched to zplugin and never looked back.

**Comment by black7375** [comment]
Check [this post](https://www.reddit.com/r/zsh/comments/ak0vgi/a_comparison_of_all_the_zsh_plugin_mangers_i_used/).

**Zplug**

> Optimizations:
>    * Negative optimization brought by terrible implementation for plugin manager itself.
>    *  Parallel loading, cache mechanism for loading of plugins

**Zplugin**

> Optimizations:
>    * bytecode compiling for plugin manger itself
>    * bytecode compiling for plugins
>    * Amazing Turbo Mode kills the time-consuming plugins like `nvm`, `thefuck`, `pyenv`, `nodenv`, etc.

**Comment by psprint** [comment]
Finally did it, check out: https://github.com/zdharma/pm-perf-test

![startup-times](https://user-images.githubusercontent.com/6049288/66723016-a5354880-ee14-11e9-9ba3-38b808e7e701.png)

**Comment by black7375** [comment]
It's interesting.

Zplug's parallel load and caching implementation is crappy than I thought.
Is zgen fast when not using turbo mode because of static load(`zgen saved`, `init.zsh`)?

**Comment by psprint** [comment]
Yes, it will be faster, because no code gets executed by the way `zgen` works, however it might be a smaller difference, because of the nuances with the `zgen` testing described in the README.
