### ISSUE TITLE
How to disable "already registered, will overwrite-load" warning

### ISSUE THREAD

**Issue by raxod502** [zdharma/zplugin#72]
**Is your feature request related to a problem? Please describe.**
I frequently re-source my `~/.zshrc`. This worked fine with zplug; however, with zplugin I get the following:

```
Warning: plugin `raxod502/wdx' already registered, will overwrite-load
Warning: plugin `zsh-users/zsh-autosuggestions' already registered, will overwrite-load
Warning: plugin `zsh-users/zsh-completions' already registered, will overwrite-load
```

**Describe the solution you'd like**
Either these warnings should not be printed, or there should be a way to disable them. Looking at the source code briefly, I can't find a way to disable them.

**Describe alternatives you've considered**
It was pointed out to me that I could use `exec zsh` instead of `. ~/.zshrc`, but it still seems to me like re-sourcing the `~/.zshrc` should not be illegal.

**Comment by psprint** [comment]
I've added `ZPLGM` hash field for this, doing:

```zsh
ZPLGM[MUTE_WARNINGS]=1
```

after loading Zplugin (or before, if done as [described in README](https://github.com/zdharma/zplugin#customizing-paths--other)) will silence those `... already registered ...` warnings.

**Comment by raxod502** [comment]
Splendid! It seems to work for me, thanks so much.
