### ISSUE TITLE
setting manpath breaks man

### ISSUE THREAD

**Issue by rebelot** [zdharma/zplugin#76]
zplugin adds `$HOME/.zplugin/polaris/share/man` to `$manpath`;
setting `$MANPATH` explicitly breaks osx `man` ways to dynamically associate commands in `$PATH` to manual pages, as specified in `/etc/man.conf`.

Although configuring `man` in the proper way to find ones right manuals is already frustrating enough that it is usually more convenient to set the `$MANPATH` manually, I think it would be reasonable not to force people to hack it.

Maybe have a warning note appear somewhere that users should find their most suitable way to have man look at `$HOME/.zplugin/polaris/share/man`.

Thanks,
TL

**Comment by p4n1k0** [comment]
Have to specify that this only happens when launching a login shell with tmux from a shell that had defined a `$MANTPATH`.

**Comment by rebelot** [comment]
Thanks for your effort, I haven't tried it yet, but I don't see why it shouldn't work. Thing is, interactive shells spawned by a shell that had `$MANTPATH` defined will break manpages auto-detection.
For this reason I wrote some guards in my `.zshrc`:
```
...
# Remove duplicates from PATH (Unique)
typeset -U path

# MANPATH Guard
unset MANPATH
...
```
(another problem of tmux is path duplication when combined with weird conda/virtualenvs)
Still, I would not set it on OSX and just mention where man pages will be in the docs.

**Comment by xPMo** [comment]
8fb1de0 also breaks in Linux when `$MANPATH` is unset. `man` will search 
```sh
% man man
No manual entry for man
```

I'm not sure of the best way to resolve this without manually parsing `/etc/man_db.conf` or asking users to set their `$MANPATH`.

**Comment by psprint** [comment]
I think I will just remove manpath section, there's something unofficial and non-posix going on in Linux and OS X, better ignore manpath support.
