### ISSUE TITLE
Can't load fpath-based plugins

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#77]
I just recently started on a new ZSH theme/plugin that makes use of the fpath for dynamic loading of it's own and external functions.

It seems that when zplugin symlinks the completions, it ignores all the items added to the fpath that didn't begin with `_`.

How would I go about loading such a plugin?

Testing with this WIP: https://gitlab.com/robobenklein/p10k

(Also yes I know about the `$0/ZERO` tip I just haven't gotten there yet, I'm trying to stick to your 100-commits handbook suggestions.)

**Comment by psprint** [comment]
Oh I see, you don't want to put `autoload ... ...` into `*.plugin.zsh` file because the loading is to be dynamic. It is true that such plugins' aren't compatible with *default* Zplugin. However, one can do `atinit'fpath+=( $PWD )'` (note the apostrophes instead of double quotes) and obtain behavior of a typical plugin manager. I hope this answers your question, I'm little distracted because I'm working on f-sy-h themes available only for patrons on patreon.com (there's a post there from last hour).

**Comment by psprint** [comment]
One more thing, `nocompletions` ice stops the custom Zplugin's actions related to symlinking completions. Basically it stops automatic completion installation. If you have them already installed, `zplg cuninstall ...` will revert this and the state will be identical as with `nocompletions` used from the beginning. So, no symlinked completions + directory added to fpath, that's pretty standard plugin manager model emulated by Zplugin.

**Comment by robobenklein** [comment]
I tried to use `atinit'fpath+=($PWD/functions)'` but when the plugin loads, the fpath is initially empty... ?

I worked around the entire problem by dropping a self-destructing hook into the first precmd:

```

function p10k_selfdestruct_setup () {
  # TODO check if exist then add, instead of type unique
  fpath+=("$P10K_INSTALL_DIR/p10k_functions")
  fpath+=("$P10K_INSTALL_DIR/segments")

  autoload -Uz promptinit; promptinit
  # echo $fpath
  prompt p10k
  prompt_p10k_render_to_vars

  precmd_functions=("${(@)precmd_functions:#p10k_selfdestruct_setup}")
}

typeset -ga precmd_functions

precmd_functions+=(p10k_selfdestruct_setup)

```

If I did that fpath addition in atinit, the fpath is empty during script sourcing and it couldn't load `promptinit` because there was no fpath for it.

**Comment by psprint** [comment]
I've tried `zplugin ice atinit'fpath+=( $PWD );' atload'print -rl -- $fpath'` on some plugin and it worked, removing `atload''` and putting the `print` into the `*.plugin.zsh` script worked too. I'm thinking what could go wrong with this.

**Comment by robobenklein** [comment]
I just cleaned up my environment, so there might have been some bad cache or temporary file that was giving me this:

```
(eval):1: promptinit: function definition file not found
/home/robo/.zplugin/plugins/robobenklein---p10k/p10k.zsh-theme:40: command not found: prompt
```
(i.e. fpath was empty when it tried to autoload promptinit for some reason.)

Now things seem to be working again with just:

```
  zplugin ice from"gl" if'[[ "$ZSH_THEME" == "p10k" ]]' nocompletions \
    atinit'fpath+=($PWD/p10k_functions $PWD/segments)'
  zplugin load robobenklein/p10k
```

**Comment by psprint** [comment]
I've added the theme to GALLERY.md, thanks for the snippet
