### ISSUE TITLE
ZSH 5.0.X: Zplugin load breaks zsh-async

### ISSUE THREAD

**Issue by robobenklein** [zdharma/zplugin#79]
**Describe the bug**

First off, this has only been happening on ZSH versions pre-5.1. Interested in 5.0.2 because my school still refuses to update the linux machines to something more recent. So far, I haven't had any problems, but now there seems to be a difference in using zsh-async from a zplugin load.

I've created a docker container for this problem with my dotfiles:

```
docker run --rm -t -i robobenklein/home:trusty zsh -l
```

**To Reproduce**

Load a plugin that includes zsh-async via zplugin. I tested antigen and it did not have this problem. (Although it took over a minute to install antigen plugins - makes me realize how much faster zplugin is...)

**Screenshots**
https://asciinema.org/a/9gN2KxWBDrux2OBR3C8PxDcxv

**Versions:**
 - $ZSH_VERSION == 5.0.2
 - Operating system name and version (uname -a): `Linux hydra26.eecs.utk.edu 3.10.0-862.11.6.el7.x86_64 #1 SMP Fri Aug 10 16:55:11 UTC 2018 x86_64 GNU/Linux` (yeah, old RHEL)

**Comment by robobenklein** [comment]
https://github.com/mafredri/zsh-async/issues/30#issuecomment-424806562

Issue with `IFS`?

**Comment by psprint** [comment]
Thanks, it was it. For Zsh < 5.1, an additional autoload stub is used (in the mechanism of not using `$fpath`), and it was redefining IFS, because I've used quite unmodified experimental code from Zsh ML.

**Comment by robobenklein** [comment]
Thanks!
