### ISSUE TITLE
[Request] allow zplugin load to use git subdirectories

### ISSUE THREAD

**Issue by cazador481** [zdharma/zplugin#8]
I would like to be able to load up a single subdirectory in zplugin such as
zplugin load zsh-users zsh-completions/src

**Comment by psprint** [comment]
Much new features are coming to Zplugin within one month, thanks for the idea, I really support it and will implement it. Right now I work on my other two plugins, first is finished, maybe you would like to take a look:

https://github.com/psprint/zconvey

**Comment by psprint** [comment]
This is possible via Subversion protocol and snippets:

```SystemVerilog
% zplugin ice svn; zplugin snippet https://github.com/zsh-users/zsh-completions/trunk/src
```

Also, the Ice-mod `blockf` and updated completion subsystem allows to handle `zsh-users/zsh-completions` directly:

```SystemVerilog
% zplugin ice blockf; zplugin light zsh-users/zsh-completions
```

**Comment by iboyperson** [comment]
I know this is unrelated to the issue but what would be the perk of using blockf as appose to omitting it?

**Comment by psprint** [comment]
@iboyperson: Interesting idea, I must digest this now as reverting something upside down is difficult. The motivation is probably to avoid one `zplugin ice` call. BTW., I've added completion management to snippets, the plugins you mentioned on reddit would now install completions automatically. It's the same as using `creinstall`, so your setup has normal state. `clist` now nicely lists path to snippets dir.

**Comment by iboyperson** [comment]
@psprint yes I noticed the snippet completion it works great. I have been following the project closely hoping to eventually make sense of the code so I can contribute to the code. The only thing I have done so far is whip up a logo that I contemplated proposingm

**Comment by psprint** [comment]
Could I have a blink on the logo?

**Comment by iboyperson** [comment]
blink? did you mean link? https://imgur.com/DnMVIjj

**Comment by psprint** [comment]
Interesting, I think it's not yet ready to substitute current logo, but maybe you could develop something more?

**Comment by iboyperson** [comment]
Can you explain what you mean by something more?

**Comment by psprint** [comment]
Just some variation on your logo, some experimenting that could yield something interesting
