### ISSUE TITLE
Snippet fails to load as of most recent commit

### ISSUE THREAD

**Issue by xPMo** [zdharma/zplugin#83]
**Describe the bug**
I have an [OMZ-style theme](https://gitlab.com/xPMo/zdotdir/blob/master/themes/two-dir.zsh-theme) which I load as a snippet, currently it won't load:

```
Setting up snippet           /home/pmo/Repos/dotfiles/ZDOTDIR/themes/two-dir.zsh-theme                                                                                                                            
Copying two-dir.zsh-theme...
cp: failed to access '/home/pmo/Repos/dotfiles/ZDOTDIR/.zplugin/snippets/--home--pmo--Repos--dotfiles--ZDOTDIR--themes/two-dir.zsh-theme/two-dir.zsh-theme': Not a directory
An error occured
Snippet not loaded (/home/pmo/Repos/dotfiles/ZDOTDIR/themes/two-dir.zsh-theme)
```
All remaining plugins load, but the default `$HOSTNAME%` prompt shows up.

**To Reproduce**
Be on the latest master (2ee250f) and load a local snippet without modifiers.  On d5cec1f, there is no problem.

**Expected behavior**
My theme is loaded.

**Versions:**
 ```
% echo $ZSH_VERSION
5.6.2
% uname -a
Linux kbvv 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux
```

**Additional context**
[My $ZDOTDIR contents](https://gitlab.com/xPMo/zdotdir) | 
[My zshrc](https://gitlab.com/xPMo/zdotdir/blob/master/.zshrc)

Also, when `update`ing, `OMZ::lib/git.zsh` fails to update:
```
Warning: updating also unloaded snippets
No such (plugin or snippet) directory: OMZ::lib/git.zsh
(expands to: https--github.com--robbyrussell--oh-my-zsh--trunk--libgit.zsh)
```

**Comment by psprint** [comment]
I've fixed the two issues you've reported, thanks
