### ISSUE TITLE
zplugin report fails for local plugins

### ISSUE THREAD

**Issue by xPMo** [zdharma/zplugin#84]
**Describe the bug**
I have local plugins, and I want to debug what's happening with them. I would like to use `zplugin report --all`, but:
```
...
No such plugin %/HOME/Repos/dotfiles/ZDOTDIR/plugins/my
...
```
I'm using `--all` to avoid typing the plugin-spec. All non-local plugins successfully report.

I skipped around a ton (back to v2.0 even) and it still didn't work, so this seems to be either a long-standing bug or I'm doing something wrong.

**To Reproduce**
Have a local plugin. (Or at least [any one of these plugins](https://gitlab.com/xPMo/zdotdir/tree/zplugin/plugins))

**Expected behavior**
I expect to have a report like all the others given.

**Versions:**
```
% echo $ZSH_VERSION
5.6.2
% uname -a
Linux kbvv 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux
```

**Additional context**

**Additional context**
[My $ZDOTDIR contents](https://gitlab.com/xPMo/zdotdir) | [My zshrc](https://gitlab.com/xPMo/zdotdir/blob/zplugin/.zshrc)

**Comment by psprint** [comment]
I've pushed a patch, it should work now

**Comment by xPMo** [comment]
Pulled and confirmed working, thanks for the quick response

**Comment by psprint** [comment]
I could extend the new [nickname](http://zdharma.org/2018-10-12/Nickname-a-plugin-or-snippet) feature to work smoothly with local plugins. Could a $4 donation be granted for this? I would buy a coffee and approach this, it may be hard. I have a [PayPal button](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=D54B3S7C6HGME).
