### ISSUE TITLE
Loading fast-syntax-highlighting breaks zsh

### ISSUE THREAD

**Issue by ahmedelgabri** [zdharma/zplugin#85]
I updated all my plugins & zplugin itself today & after this typing anything will exit the process. I found out if I comment out these lines in my [`.zshrc`](https://github.com/ahmedelgabri/dotfiles/blob/4820f6dfecefbfb71c99217cb35c7a179d5d84ea/files/.zsh.d/.zshrc) everything works fine.

```
zplugin ice wait"0" lucid atinit"zpcompinit; zpcdreplay"
zplugin light zdharma/fast-syntax-highlighting
```

![zsh](https://user-images.githubusercontent.com/63876/46759784-83b8f280-ccd0-11e8-9cb1-20d8cb74a788.gif)

**Comment by psprint** [comment]
Which zsh version?

**Comment by ahmedelgabri** [comment]
`zsh 5.6.2 (x86_64-apple-darwin18.0.0)`

**Comment by psprint** [comment]
This is a bad news, Z-Sy-F started to use long-prepared Zle pre-redraw-hook, loaded itself within `19 ms` instead of `400 ms`, it was a good change. Now I reverted this patch from F-Sy-H and will write to Zsh ML about the problem. After update F-Sy-H should work again.

**Comment by ahmedelgabri** [comment]
I updated F-Sy-H & it works now as expected. Thanks
