### ISSUE TITLE
Manage locally generated completion files

### ISSUE THREAD

**Issue by idadzie** [zdharma/zplugin#87]
A command line tool I am currently trying out [poetry](https://github.com/sdispater/poetry) generates 
a local completion file via the `poetry completions zsh > _poetry` command.

How would I go about managing this completion file with zplugin without having to add it to the fpath
directly.

In the case of tools like docker-compose; I use zplugin to manage the binary and completion files directly from github. I cannot do same for poetry because the completion file does not exist in its repository.

Please see below for the docker-compose example.
```
zplugin ice as'completion' wait'1' lucid
zplugin snippet 'https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose'
```

**Comment by idadzie** [comment]
```
zplugin creinstall ~/Desktop/poetry  # directory with `_poetry`
```
Using the very latest commit (bac1d20) of zplugin as of this comment, the command above did not work as suggested. Could you kindly shed some light on this?

However, manually creating a directory `~/.zplugin/plugins/_local---poetry` and running command
`zplugin creinstall _local/poetry` successfully installed the completions.

Also using the suggested complete install of poetry via zplugin worked as expected. Both poetry and its completions were installed.

**Comment by idadzie** [comment]
```bash
zplugin creinstall ~/Desktop/poetry  # directory with `_poetry`
```
Deleted my _**.zcompcache**_ and _**.zcompdump**_ and tried the command above using the latest commit (515f8fb) of zplugin as of this comment and it **WORKED**.

**Comment by crazy-matt** [comment]
> sdispater/poetry

About asking for poetry to not modify the PATH, I think it's now possible with --no-modify-path arg, that way:

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME="$HOME/.local/bin/poetry" python3 - --no-modify-path
```
Just post it here in case someone lands here.
