### ISSUE TITLE
add --force flag to zplugin update

### ISSUE THREAD

**Issue by untoreh** [zdharma/zplugin#89]
**Is your feature request related to a problem? Please describe.**
zpl fails to update if the git repository has untracked files

**Describe the solution you'd like**
Adding a `--force` flag which does `git reset --hard` before fast forwarding

**Describe alternatives you've considered**
Manually hard resetting all the faulty repos

**Comment by psprint** [comment]
There's `atpull'!git reset --hard HEAD'`, it would do what you've described, always before new commits were to be downloaded. But I see the option would be an interesting solution. But `--force` suggests downloading something even when there is nothing to download. I would look for a better option name.

**Comment by robobenklein** [comment]
I think for me `--force` wouldn't always force a download, but could force a clean repo state.

Say for example I made some uncommitted changes in a zplg/plugins/myplugin, then `--force` would force clean and reset the repo if it couldn't FF merge.

**Comment by psprint** [comment]
It should be implemented now! Iwent for a different option name `-r/--reset`, because there is an option `-f` used by the subcommand `snippet`
