### ISSUE TITLE
[Suggestion] Simplify interface.

### ISSUE THREAD

**Issue by kwinczek** [zdharma/zplugin#9]
Simplify interfaces:

update {plugin-name}
update-all

status {plugin-name}
status-all

report {plugin-name}
all-reports

compile  {plugin-name}
compile-all

uncompile {plugin-name}
uncompile-all

each pair should be merged into single command, and if no parameter is provided then equivalent to current -all action would be performed.

**Comment by psprint** [comment]
I've implemented that today, it indeed has sense:

```
% zplg update
Assuming --all is passed
Updating snippet git.plugin.zsh
Downloading git.plugin.zsh...

Warning: updating also unloaded plugins

Updating plugin LockonS/terminal-workload-report
...
```
