### ISSUE TITLE
Submodules of Plugins from Prezto are Not Downloaded

### ISSUE THREAD

**Issue by laggardkernel** [zdharma/zplugin#91]
**Describe the bug**

Submodules of plugin from prezto are not pulled down. I'm migrating from prezto, the first thought of my using of zplugin is to enable all the plugins I used with prezto. And I use `paradox` theme from `prezto/modules/prompt`. After enable the module with `zplugin ice svn;`, the subfolders are pulled down, but not the [external themes included by prezto with git submodules](https://github.com/sorin-ionescu/prezto/tree/master/modules/prompt/external).

**To Reproduce**
Add the scripts below to enable `prompt` module from prezto.

```shell
zstyle ':prezto:module:prompt' theme 'paradox'
zplugin ice svn; zplugin snippet PZT::modules/prompt
```

**Versions:**
 - $ZSH_VERSION == 5.6.2
 - Operating system name and version (uname -a): macOS 10.12

**Comment by psprint** [comment]
I've found a bug, `paradox` theme should now work. I'm thinking about submodules now.

**Comment by laggardkernel** [comment]
I cloned the prezto repo, copied and overwrote plugin folders to corresponding snippets sub-folders in `~/.zplugin/.../`. After that, I opened a new terminal tab and zplugin tried to update theses snippets had been modified . Since the folder corresponding folder to the submodules were added by me already, zplugin initialized without an error.

It seems zplugin uses `pmodload` to load plugins from prezto, and the `fpath` is set correctly, otherwise `prompt` can't list themes from `prezto/modules/prompt/functions`. It's reasonable to think that the problem is caused only by missing of submodules but not other else.

**Comment by psprint** [comment]
> It seems zplugin uses `pmodload` to load plugins from prezto, and the `fpath` is set correctly, otherwise `prompt` can't list themes from `prezto/modules/prompt/functions`. It's reasonable to think that the problem is caused only by missing of submodules but not other else.

Yes, it's this block of code:

```zsh
        # Add to fpath
        [[ -d "$local_dir/$dirname/functions" ]] && {
            [[ -z "${fpath[(r)$local_dir/$dirname/functions]}" ]] && fpath+=( "$local_dir/$dirname/functions" )
            () {
                setopt localoptions extendedglob
                autoload $local_dir/$dirname/functions/^([_.]*|prompt_*_setup|README*)(-.N:t)
            }
        }
```

in `-zplg-load-snippet()`.

**Comment by laggardkernel** [comment]
About the `pmodload`, you may forget to set styles once a prezto module is loaded in [zplugin's own pmodload implementation](https://github.com/zdharma/zplugin/blob/master/zplugin.zsh#L709-L717).

```
# from prezto/init.zsh L132-L134
      if (( $? == 0 )); then
        zstyle ":prezto:module:$pmodule" loaded 'yes'
      else
```

This helps other prezto modules to tell whether a module they depend on is loaded or not. Besides, `pmodload` from prezto also use this `loaded` value to avoid loading a module multiple times.

[prezto/init.zsh#L94-L98](https://github.com/sorin-ionescu/prezto/blob/master/init.zsh#L94-L98)
```
  # Load Prezto modules.
  for pmodule in "$pmodules[@]"; do
    if zstyle -t ":prezto:module:$pmodule" loaded 'yes' 'no'; then
      continue
    else
```

Here is another example that `fasd` module from prezto to initializes fasd differently. If prezto module `completion` is loaded, `fasd` module tries to initialize `fasd` with some completion settings.

[prezto/modules/fasd/init.zsh#L29-L32](https://github.com/sorin-ionescu/prezto/blob/master/modules/fasd/init.zsh#L29-L32)
```
  # Set fasd completion init arguments, if applicable.
  if zstyle -t ':prezto:module:completion' loaded; then
    init_args+=(zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)
  fi
```

BTW, I find a temporary solution to download submodules.

```
zplugin ice svn atload'git clone https://github.com/clvv/fasd external'
zplugin snippet PZT::modules/fasd
```

**Comment by psprint** [comment]
On Thu, 20 Dec 2018 at 09:48, laggardkernel <notifications@github.com>
wrote:

> About the pmodload, you may forget to set styles once a prezto module is
> loaded in zplugin's own pmodload implementation
> <https://github.com/zdharma/zplugin/blob/master/zplugin.zsh#L709-L717>.
>
> # from prezto/init.zsh L132-L134
>       if (( $? == 0 )); then
>         zstyle ":prezto:module:$pmodule" loaded 'yes'
>       else
>
> This helps other prezto modules to tell whether a module they depend on is
> loaded or not. Besides, pmodload from prezto also use this loaded value
> to avoid loading a module multiple times.
>
> prezto/init.zsh#L94-L98
> <https://github.com/sorin-ionescu/prezto/blob/master/init.zsh#L94-L98>
>
>   # Load Prezto modules.
>   for pmodule in "$pmodules[@]"; do
>     if zstyle -t ":prezto:module:$pmodule" loaded 'yes' 'no'; then
>       continue
>     else
>
> Here is another example that fasd module from prezto to initializes fasd
> differently. If prezto module completion is loaded, fasd module tries to
> initialize fasd with some completion settings.
>
> prezto/modules/fasd/init.zsh#L29-L32
> <https://github.com/sorin-ionescu/prezto/blob/master/modules/fasd/init.zsh#L29-L32>
>
>   # Set fasd completion init arguments, if applicable.
>   if zstyle -t ':prezto:module:completion' loaded; then
>     init_args+=(zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install)
>   fi
>
> Great information, thanks! I'll include the styles etc. in Zplugin's
pmodload.


>  BTW, I find a temporary solution to download submodules.
>
> zplugin ice svn atload'git clone https://github.com/clvv/fasd external'
> zplugin snippet PZT::modules/fasd
>
>
That's might even be the main solution, or a base for the main solution,
great job, thanks!

**Comment by laggardkernel** [comment]
Here's my temporary fix. Obviously, it's not that elegant and only alleviates part of the problem.

```zsh
pmodload () {
  # set -x
  while (( $# ))
  do
    if zstyle -t ":prezto:module:$1" loaded 'yes' 'no'; then
      shift
      continue
    else
      [[ -z "${ZPLG_SNIPPETS[PZT::modules/$1${ZPLG_ICE[svn]-/init.zsh}]}" && -z "${ZPLG_SNIPPETS[https://github.com/sorin-ionescu/prezto/trunk/modules/$1${ZPLG_ICE[svn]-/init.zsh}]}" ]] && -zplg-load-snippet PZT::modules/"$1${ZPLG_ICE[svn]-/init.zsh}"
      if (( $? == 0 )); then
        zstyle ":prezto:module:$1" loaded 'yes'
      fi
      shift
    fi
  done
  # set +x
}
```

Another thing I found is that, a prezto module defined by `snippet` itself is not loaded by `pmodload` function. 
For example, from tracing result of `set -x`, prezto module `fasd`  `zplugin snippet PZT::modules/fasd` is not loaded by `pmodload`, but it does use `pmodload` function to load prezto module `editor`, which it depends on.

The `zstyle ":prezto:module:$1" loaded 'yes'` in `pmodload` function above doesn't cover the prezto `snippet`s. That's why I say my fix only alleviates part of the problem.

**Comment by stone821** [comment]
I'm new to zplugin. I don't understand how to download the submodules. Is this problem fixed?
When I add PZT:: modules/prompt, zplugin still issues errors about not downloading submodules
The code:
```
zstyle ':prezto:module:prompt' theme 'pure'
zplugin ice svn; zplugin snippet PZT::modules/prompt
```

How can I fix this problem, please?

**Comment by psprint** [comment]
Following code will work for `pure` theme. There is no general solution to the submodule-problem yet:

```zsh
zplugin light mafredri/zsh-async
zstyle ':prezto:module:prompt' theme 'pure'
zplugin ice svn silent atclone'git clone https://github.com/sindresorhus/pure external/pure'
zplugin snippet PZT::modules/prompt
```

**Comment by stone821** [comment]
Thanks

**Comment by david-moven** [comment]
what is the status of this?

**Comment by laggardkernel** [comment]
@david-moven Not fixed. But we can use `atclone` modifier to do it manually.

```zsh
zplugin ice svn \
  atclone'git clone https://github.com/zsh-users/zsh-autosuggestions external; for i in external/*.zsh; do zcompile $i; done;' \
  atpull'cd ./external;git reset --hard HEAD;git pull;for i in ./*.zsh; do zcompile $i; done;'
zplugin snippet PZT::modules/autosuggestions
```

**Comment by psprint** [comment]
I would like to share that Zplugin gained a new architecture, which allows to extend it via dedicated plugins :) They're called "z-plugins". Check out a first z-plugin that allows to clone submodules within the installed plugin or snippet:

https://github.com/zdharma/z-p-submods

@david-moven: The z-plugin does what you've asked – it adds support for the submodules. To address your Prezto-autosuggestions example, this is how it's solved by the z-plugin:

```zsh
zplugin ice svn submods'zsh-users/zsh-autosuggestions -> external'
zplugin snippet PZT::modules/autosuggestions
```
