### ISSUE TITLE
Completion is broken with zsh-users/zsh-autosuggestions

### ISSUE THREAD

**Issue by ahmedelgabri** [zdharma/zplugin#95]
**Describe the bug**
Completion behavior changes after installing `zsh-users/zsh-autosuggestions`

**To Reproduce**

```sh
$ cd ~
$ rm -rf ~/.zplugin
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
$ .dotf<TAB> # trying to access my .dotfiles folder in $HOME, works as expected
$ zplugin ice wait"0" lucid atload"_zsh_autosuggest_start"; zplugin light zsh-users/zsh-autosuggestions
$ $ .dotf<TAB> # trying to access my .dotfiles folder in $HOME, doesn't work anymore
```

**Expected behavior**
To stay consistent & work as expected

**Screenshots**
![completion](https://user-images.githubusercontent.com/63876/50374412-1be72800-05ee-11e9-9f70-c762bfb658c9.gif)

**Versions:**
 - $ZSH_VERSION == `zsh 5.6.2 (x86_64-apple-darwin18.0.0)`
 - Operating system name and version (uname -a): 
```
Darwin Pandoras-Box 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
```

**Additional context**

**Comment by psprint** [comment]
This seems to be unrelated to Zplugin – by loading of `zsh-autosuggestions` the number of functions defined growse, and `.dotf<TAB>` matches some of them. However, could you provide output for:

```zsh
zstyle -s ':completion:*' completer value; echo $value
echo $value
```
?

**Comment by ahmedelgabri** [comment]
> ```sh
> zstyle -s ':completion:*' completer value; echo $value
> echo $value
> ```

The output of this is empty/nothing

**Comment by psprint** [comment]
Ok. Could you try sourcing the `zsh-autosuggestions` plugin instead of loading it with zplugin? Does then the issue still persist?

```zsh
$ source {zsh-autosuggestions-location}/zsh-autosuggestions.plugin.zsh
$ .dotf<TAB> # trying to access my .dotfiles folder in $HOME, doesn't work anymore
```

**Comment by ahmedelgabri** [comment]
Tried 

```zsh
source ~/.zplugin/plugins/zsh-users---zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
```

Same result

**Comment by psprint** [comment]
Is the issue solved maybe?

**Comment by ahmedelgabri** [comment]
Yes, it is.
