### ISSUE TITLE
Ready-to-go examples

### ISSUE THREAD

**Issue by cristovao-trevisan** [zdharma/zplugin#98]
I've moved from oh-my-zsh to zplugin and it's amazing, thank you. Faster and easy to reproduce (work and home computers).
Still it took some time to learn how it works and build my own `.zshrc`.

I think it would be great to have some examples, at the README or GALLERY, maybe a list of gists that can be just copy-pasted.
Feel like more people will try out the plugin and see the benefits.
It would also be cool to explore what other people are using.

[This is my gist](https://gist.github.com/cristovao-trevisan/f41f648ff6c4241265d31511d8616be4), for example.

**Comment by psprint** [comment]
Thanks for the suggestions. Such examples are available on the [Zplugin Wiki](https://github.com/zdharma/zplugin/wiki). So it turns out that the Wiki-link should be more exposed.

**Comment by psprint** [comment]
Ah, I read what you wrote now, different day, different mood, and I see what you mean. An exchange of zplugin configuration files. I very like the idea and will soon do something about it, thanks 👍

**Comment by cristovao-trevisan** [comment]
That's exactly what i meant. Thanks for reading it again

**Comment by psprint** [comment]
Hello,
there is a new repository that is the answer to your issue: https://github.com/zdharma/zplugin-configs
