### ISSUE TITLE
zplugin:source:70: no such file or directory: /zplugin-autoload.zsh

### ISSUE THREAD

**Issue by abravalheri** [zdharma/zplugin#99]
**Describe the bug**
In an ArchLinux installation, with [grml-based zshrc](https://grml.org/zsh/), after installing zplugin manually to a different location (`$XDG_DATA_HOME/zplugin/bin`), I cannot run any zplugin command after the shell is initialised.

```
$ zplugin help
zplugin:source:70: no such file or directory: /zplugin-autoload.zsh
zsh: command not found: -zplg-help
```

**To Reproduce**
According the instructions in [manual installation](https://github.com/zdharma/zplugin#manual-installation) and [customizing paths](https://github.com/zdharma/zplugin#customizing-paths--other), I have included the following lines in my [zsrh.local](https://grml.org/zsh/grmlzshrc.html):

```
declare -A ZPLGM
ZPLGM[HOME_DIR]=${XDG_DATA_HOME}/zplugin
ZPLGM[BIN_DIR]=${ZPLGM[HOME_DIR]}/bin
ZPLGM[PLUGINS_DIR]=${ZPLGM[HOME_DIR]}/plugins
ZPLGM[COMPLETIONS_DIR]=${ZPLGM[HOME_DIR]}/completions
ZPLGM[SNIPPETS_DIR]=${ZPLGM[HOME_DIR]}/snippets
ZPLGM[SERVICES_DIR]=${ZPLGM[HOME_DIR]}/services

if [ ! -d ${ZPLGM[HOME_DIR]} ]; then
  mkdir -p ${ZPLGM[HOME_DIR]}
  git clone https://github.com/zdharma/zplugin ${ZPLGM[BIN_DIR]}
  source ${ZPLGM[HOME_DIR]}/bin/zplugin.zsh
  zplugin self-update
else
  source ${ZPLGM[HOME_DIR]}/bin/zplugin.zsh
fi
autoload -Uz _zplugin
# shellcheck disable=SC2154,2034,2004
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# ... zplugin calls with ice, light and snippet
```

When I open a shell, everything works fine. However, when I try to manually run the command:
```zplugin help```
I receive the error message:
```
zplugin:source:70: no such file or directory: /zplugin-autoload.zsh
zsh: command not found: -zplg-help
```

**Expected behavior**
After including the snippet of code aforementioned in my dotfiles, I would expect that (a) zplugin would auto-boot from a custom XDG-compliant directory in the computers I use when I clone my dotfiles and (b) I would be able to manually interact with zplugin using the command line `zplugin` or `zplg`.

(a) seems to happen as expect, however (b) doesn't seem to work.

**Versions:**
 - $ZSH_VERSION == 5.6.2
 - Operating system name and version (uname -a): Arch Linux, `Linux 4.19.15-1-lts #1 SMP Sun Jan 13 13:53:52 CET 2019 x86_64 GNU/Linux`

**Additional context**
The function `zplugin` seems to work properly during initialisation. I suppose when my `.zshrc` is being executed, the variable `$ZPLGM`  is defined and `zplugin` has its right value in the function scope.

I am wondering if would it be the case that the `zplugin` function considers the variable `$ZPLGM`  empty because because of:
(a) ZSH is not able to export array variables
(b) ZSH uses some kind of "late binding" and does not hold the values of the variables from where the function zplugin was defined, as it would be expected from a closure-enabled programming language (just a conjecture).

By the way... When I include:
```zsh
zplugin ice wait:3
zplugin light "MichaelAquilina/zsh-you-should-use"
```
I run into the same problem described by #80. When I remove the `ice wait`, I have no problems after initialisation (as long as I don't call `zplugin` manually)... So I was wondering if the 2 issues are related.

**Comment by psprint** [comment]
I'm running exact your code, except that I've added the default value (i.e. the `:-$HOME/.config`) to the HOME_DIR assignment:

```zsh
if (( 1 )) {
    declare -A ZPLGM
    ZPLGM[HOME_DIR]=${XDG_DATA_HOME:-$HOME/.config}/zplugin
```

Could you check if maybe this solves the problem? 

Otherwise it works fine. I will probably have to prepare some debug-branch, because also the `zplugin ice wait:3; zplugin light. ..` works fine on my setup.

**Comment by abravalheri** [comment]
Thank you very much @psprint!

After you comment I checked, the how the `zshrc.local` was being sourced, and in my modified version of `grml` it was inside a function. This way some of the variables in `zplugins.zsh` were not defined in the global scope, just inside the wrapping function itself` . That was the source of the confusion. Sorry for the trouble.

As a side effect `ice wait` is now working as well.

Thank you again and congratulation for the awesome project!

**Comment by jdorel** [comment]
Hi, I am having the exact same issue (`command not found` and `ice wait` issue), and the comments do not appear to resolve the issue for me.
I am using ZSH `5.7.1` and here is the configuration I use:
```
declare -A ZPLGM
ZPLGM[HOME_DIR]=${XDG_DATA_HOME:-$HOME/.local/share}/zplugin
ZPLGM[BIN_DIR]=${ZPLGM[HOME_DIR]}/bin
ZPLGM[PLUGINS_DIR]=${ZPLGM[HOME_DIR]}/plugins
ZPLGM[COMPLETIONS_DIR]=${ZPLGM[HOME_DIR]}/completions
ZPLGM[SNIPPETS_DIR]=${ZPLGM[HOME_DIR]}/snippets
ZPLGM[SERVICES_DIR]=${ZPLGM[HOME_DIR]}/services

if [ ! -d ${ZPLGM[HOME_DIR]} ]; then
  mkdir -p ${ZPLGM[HOME_DIR]}
  git clone https://github.com/zdharma/zplugin ${ZPLGM[BIN_DIR]}
  source ${ZPLGM[HOME_DIR]}/bin/zplugin.zsh
  zplugin self-update
else
  source ${ZPLGM[HOME_DIR]}/bin/zplugin.zsh
fi
```
Also if I try to `echo $ZPLGM` after this configuration, I get back a long function.
